' TODO: Documentation

$puml_ext_include(utils/data-structures.iuml)

hide empty description

skinparam ArrowColor Black
skinparam StateBorderColor #525252

skinparam ArrowColor Black
skinparam StateBorderColor #525252

skinparam StateBackgroundColor LightBlue
skinparam StateBackgroundColor<<Failure>> LightCoral
skinparam StateBackgroundColor<<Error>> Gold
skinparam StateBackgroundColor<<Success>> LightGreen
skinparam StateBackgroundColor<<Missing>> LightGray 
skinparam StateBackgroundColor<<Init>> LightGray 

skinparam NoteBackgroundColor Ivory
skinparam NoteBorderColor Sienna


!$end_counter = 0

!procedure $_prefix_line_callback($line, $prefix)
    $prefix $line
!endprocedure

!procedure $_prefix_lines($prefix,$lines,$sep="\n")
    $_list_foreach_void($lines,"$_prefix_line_callback",$prefix,$sep)
!endprocedure

!unquoted procedure $link($source, $links) 
    $_prefix_lines($source, $links, "|")
!endprocedure


!unquoted procedure $command($title,$target,$cmdname, $desc="", $tag="", $links="")
    !if ($tag == "")
        !$tag = $title 
    !endif 
    $tag: |_ **Target**: $target
    $tag: |_ **Command**: $cmdname
    !if ($desc != "")
        $tag: ----
        $_prefix_lines($tag+":", $desc)
    !endif
    $link($tag, $links)
    state "<&transfer>  $title" as $tag 
!endprocedure 

!procedure $_simple_node($title, $desc, $tag="", $icon="", $stereotype="", $links="")
    !if ($tag == "")
        !$tag = $title 
    !endif
    $_prefix_lines($tag+":", $desc)
    $link($tag, $links)
    state "$icon  $title" as $tag $stereotype
!endprocedure

!procedure $_simple_terminal_node($title, $desc, $tag="", $icon="", $stereotype="", $links="")
    !if ($links == "")
        state "end##$end_counter" <<end>> 
        !$links = "--> end" + $end_counter
        !$end_counter = $end_counter + 1
    !endif
     $_simple_node($title, $desc, $tag, $icon, $stereotype, $links)
!endprocedure

!unquoted procedure $action($title, $desc="", $tag="", $links="")
    $_simple_node($title, $desc, $tag, "<&cog>", $links=$links)
!endprocedure 

!unquoted procedure $failure($title, $desc="", $tag="", $links="")
    $_simple_terminal_node($title, $desc, $tag, "<&x>", "<<Failure>>", $links)
!endprocedure 

!unquoted procedure $error($title, $desc="", $tag="", $links="")
     $_simple_terminal_node($title, $desc, $tag, "<&x>", "<<Error>>", $links)
!endprocedure 

!unquoted procedure $success($title, $desc="", $tag="", $links="")
    $_simple_terminal_node($title, $desc, $tag, "<&thumb-up>", "<<Success>>", $links)
!endprocedure

!unquoted procedure $init($input, $desc="", $links="")
    [*] --> _init_
    $_prefix_lines("_init_: |_ ", $input)
    !if ($desc != "") 
        _init_: ----
        $_prefix_lines("_init_: ", $desc)
    !endif
    $link(_init_, $links)
    state "<&excerpt>" as _init_ <<Init>>
!endprocedure
