sprite $logo32_apache_kafka [20x32/16z] {
XP9L4WGn20M9U_h-jzsYoBhrnyJGnuX8MSmaJmoKAWzaoA62bpiTDPda9zToNkvKbfC0KHIBu3OicBflG1DzMi1mfm9zjUUaIuIedsmXeotjzdM3OkPTlpHz
07OMFo59rC_0wB1FZWGh-hpHzxfHpy7MCi9HmUbdqyNMeSlJtjwCOIebytNX1DebLO3gnkcoOjGDi66fq0kOGTo487wJ7pHeztuVD3ZzFcjLV8Rqg6a7K6F7
NVkoMELvHk-p_3Fp13aqyE__K94dojmZoWCN
}

