sprite $logo24_apache_kafka [15x24/16z] {
TP17We0W3007iG21pFzVkrqzBQJt15fcvtdTDHsFweJmLGEwvLR3tfp0qQy2PUhQOAXPW0XWTvJJ1em0BYjai8NEIl_rRfgfowbc6NPekd6q2rAuAP0Mm5iT
ZaBNoZLQeQHgXkjtZD9rR3GxX_qUu_mR0yO4gb6RxLcXgujtmNeTx_h_7AUvbeDNpsoFyWa
}

