' Octicons{height=24px} (https://github.com/primer/octicons) MIT License

sprite $octicon24_alert [24x24/16z] {
XT3LWSKW503Hu1AP_glTVNw3p-V1sTOPqsUmFJ_WwB3ZaMzOyKhL7jyUAzPyCgLdk1v1BjZokgIXlAiwnKybxX775uUAex-UIa_oCH-tnLrtgWxvc4V1si0x
9nyZ-t--AVGylkzOxmCwqIqFF2dRJMs3_W4
}

sprite $octicon24_archive [21x24/16z] rT4b0i0034FHjCr8_VlVTcRCTiyLeg9BvQDIpzc0TMI-BmVE-kZm7bt8Q0_hOUdPTidiClwpPNAK5ysLheq

sprite $octicon24_arrow_down [15x24/16z] fSor0K0n409GuBjc_sdZrj-hJe4HruIjNLsoMjibPXwvFMAry7N3IsXgrJz7s5wx7SMPknFD7RiR7TyKEkWNPeHT

sprite $octicon24_arrow_left [15x24/16z] Ow02O4JXCN4ZyvXv-P5uhFpyI5nsVYGk8oS_0W0DuKS2G4FGkRWLenk5i0ZJ6GX7eda1tOCK0m

sprite $octicon24_arrow_right [15x24/16z] Ow0OCA9okPbGkFoyp2XSVdvML2u_EvY109oCA5n-RYOKBj10D2wcOeHHA1RXTWOlCnulC39G0G

sprite $octicon24_arrow_small_down [9x24/16z] fSQr0S0m4C10vHqcxJzj6DpxggDONTTSr3ofhjMwJh5wMeFQKmrqQiTfTEGIIt2hABS3

sprite $octicon24_arrow_small_left [9x24/16z] Ow02O8JIp3mGcfMV7opCmS_FpyB2mip33m5m1bmAeXYk7M4WnG

sprite $octicon24_arrow_small_right [9x24/16z] Ow0OCC8OFCnG1Zy_Av1aOM7Xv-VdO0HomO276SPWWab15KErCo4Cf1m

sprite $octicon24_arrow_small_up [9x24/16z] fKd30G1130pMKV_Tdl6FXf0Vl9cCBh5YdTmZekzSTeueG7uA9ovbvr9uBtUnur-KKY0z6m

sprite $octicon24_arrow_up [15x24/16z] fSor0G0W40D0t27xJujhpLLv9V_eKx74xbb0kEOEWDkLGMDcfJ2eNWaiebOC1sjFZq2v44Bth6lYvrgq-5jIqL3ogG

sprite $octicon24_beaker [24x24/16z] {
ZT254OKm54JHPxXi_zMYyUJB7TivEEI3KJDZ-ZT3MdGs3FPq3qg2nL6weUrix_ZpFhVKhkwxrinrywkRKvzwVpU6HXPm-4N3w3NV0l6JaTLxxv77plV2k-el
lwslhwM_twoecc-VKAVn9QjNxMjUXEW4
}

sprite $octicon24_bell [21x24/16z] {
VS-54GCW341HKbp__jFMBOUyKuYR8x5cLiZJNm22_hADXsR___Zu_Lu6ys_bfxt_7F_ywpEfp_BwH9Fd63JxsMTgwj7YF0VgQyuyoS7Kr0uc5cR3hPW3-pb6
gQyDDKazokTn0m
}

sprite $octicon24_bold [15x24/16z] {
bS-r0KGn30DGCnru_sa_OnbLUk70KAJN_2e4RsxXdS4i-bbC6mtMHBVUtCgRSXENpRWnLTMx__owI67dDoBNUxxFYtJnWs3TV7Dj-fnzaTP7Nr-8HV7weD_F
g524mSm
}

sprite $octicon24_book [24x24/16z] rSm50W8n40F0R0aEb_-_zjpTPUfTmLhiezG3xfzUVmJ5rFFrpQyUA6H4fAY-VsF4ed_6qdygGaGpTfK-S_wTsdo06rDF_Panb3mSLXS

sprite $octicon24_bookmark [15x24/16z] lSw54S0m30D0XJdUVzjUM1Fq3ytsmYXYMLXJdSE0mA61aItYY6kDng3lEZqYEJe6sckoURkj7_zP-L-scI87m9qWAWmgZg0Q7AQA1_CV

sprite $octicon24_briefcase [21x24/16z] jSW53e1030NHDXbS_lrFYsiXXhpLZdt2SqcvdoC2H8p3jKLQHIrrHcXahR0G3RsF4LB6R9nccJP3r9zgNRMqDytUwG4

sprite $octicon24_broadcast [24x24/16z] {
PP05igOX30GdWalkVzkjWPzzrdX_CYbmqTJ6QiK4tx4UrSqyZqZueaGINBHDVReEsaSE_MokLdC3IUkSBRX8Yp4YdAOqpfr95bcuJ2hP1YXVbp1SMkQVAiSx
7OIf6a1r7WJm7Ks0N024OXfW0y0kpbYV08PTpxHmq1jzTtReOaO4q_tynr0OkG3BEveB_9Fd_BV3uj1WE1clT8-l6Sq1v7OD_r6EjyrPPZwUzKHGB0VHI7Xr
KlUCY-xovNKLFAHzUJTyv_c_tFlvmxlFnpy
}

sprite $octicon24_browser [21x24/16z] tSW52i0m40NH1GRY-VS_RLsNea7x66ni35LUfGTqTWXTsDK1VGjuGS8yVZXhm0kTBgzZOsO

sprite $octicon24_bug [24x24/16z] {
hT054W8n04FHIcfhkVzfaKmX-1X__NKz_2W222e1i8Da4-yaxP8sLoyLDknRVELCDLuTdEldOYC0DEPd7vnv8DSKmbKmrn5DFhXLUn_Sw-rpktshAJWx7dyE
x0tp5ydiwiTzLBBNUCUwFTrdG4FbkcD7glkXzxcE7le3OzxVNu13C3XY-6zd
}

sprite $octicon24_calendar [21x24/16z] nOv55a8n300JgElzRqlglcQ-T5wZy8RX9ed8La5DabwYY6F0aZCibqL2kkIvC0v9bplfact8T7dibowBx2-1RBpiKVvwaVsXd3ZBYLVv9nveW2_RGRZn0m

sprite $octicon24_check [18x24/16z] lKwd0G0n4Fh-GR7_jEaL5NL8-c65Muc7K8BybS0cSIi1FYlnatpM3YIg4OCgn4B9LmYHA1mM2

sprite $octicon24_checklist [24x24/16z] {
hSn50iD034DHsM7q_KzRKgfn6NzmtaBuLpQ6cklYTTHTrAnRinzl_IVFFTY9F-nqnItlr79VsekTRWnoHCkTOxC3xSQBSsTZ52RojtMn_CW7EBFSO4SIm-aT
9yH0LPyoRT_cI-ASExvi3m
}

sprite $octicon24_chevron_down [15x24/16z] lSUt0G0W30D1aQ7I_jEIhH7yrH_SoaCxCZBPlpgPDzck6ZTnBU6weZvz3-dwINwIdrI0Smi

sprite $octicon24_chevron_left [12x24/16z] Oo0JC2AORBnCS2O_FoyZdCdFXc2o8fWiM9dC3AXiX1gS75Pa3Xkw6n1kGxYPT

sprite $octicon24_chevron_right [12x24/16z] Oo0TC2AOJBniS55UVduuXuqVYSEAp671oM46SJ3PB9XCX9a8kn1kG74Rmira0W

sprite $octicon24_chevron_up [15x24/16z] lSUn0G0G402n0r3PVre0ME3J1M7gcytsMrvVMzzB_MSUtxyMWD1_jjuQcM8hDh4bYvWA

sprite $octicon24_circle_slash [21x24/16z] {
VT5NOiKm24JHCTYeOTtzhpQzIKdUV1vLG8zYxcwB796y9kFuicjon-bd9FFwi4AUdyitHQy9slUXW93aT7rV13SkTUodNKQNKHQJAXROQZAYiPb4oxcRPhxY
Og_Os4sqm3OpmgYhgM3gs687NNBofwdZ7ptutjU8lNK-ADzDphN9-pWU3sxFCm
}

sprite $octicon24_circuit_board [21x24/16z] {
dOw53aD120I7mdFx_w-jd6Ifn3gnpTm1oqyymi12ECjrNG5n9LvECkFW9KpkStC3mD33MDm1wsgyi6KnZhBsDUj5bh3Kd_RzynhBpXx6tijzQjTZllv4vONA
Yr0bkLnUxkjd5D7Box6eV7PY_k4MkvMpaJ5-yG
}

sprite $octicon24_clippy [21x24/16z] {
VOy73iGW30InsFJY___s5aJR8DsaCd8D_uXnKdQvN_QH-s5sx4CUY2C4laYkSdfYPwhjdZWf-S6GncEH0qKgHI88AB9aciYI1f6TAEankuC1XfQ-PLUoXdIw
HalV1bVIfyY2raHcxau-Sywxtnk4xQN4wyAJCdy
}

sprite $octicon24_clock [21x24/16z] {
VP475eGW30KbYQ7pxtzQkt5BdaCVEanl43FJbmdQiDCqc9i7keg8TepvSX5DhgeqnAEYoC-aaA5RmIX74y1H5l2UqPSab2t5oUIr1IdeHn8qRzLBMYstyIT7
U-I9xDAc3vF8jf6CInBKZcH4q7ruWr3icaO1Um_YFPtxoFvt-1_dim8
}

sprite $octicon24_cloud_download [24x24/16z] {
bP254GCn40DpO0RrNssUcNT8ioVZxmaI4JfO3kW8lDK6y4QD1tIj1MaeSi9wHQuyDyAwRfSAajSXibtj6dC12lTR0hAviQ8G0LRt5nSu2vbhEezhZfYo0hfS
yDGJWeCSF0NeS6xBuDkWDdVlaOoUmVSn3-jOj6NmRP3jdmx-G41FE0uMVHWiUarOz7SQ
}

sprite $octicon24_cloud_upload [24x24/16z] {
hOvNOi0W3CKOPZGrwFwtBIlxCzNNGtYPVyOdBLlq3siJK85aRtuZk_RhCjjL9-9AiQK3oy-HI_7ks4aul08wdf8BVWJfDTv79HcJeMZt0c8c6H7oF4reoB4m
S-hpGwlMcKGI95c-wgg_pnVYCV_qDg1stjEOleK2wjRzZUc1txJ6lUT_y5_v0m
}

sprite $octicon24_code [21x24/16z] jT350S0W50DGt27xJrltvlfn7euI2_gkRsjXgqFJjnKWh0QKIpFGpLAR3kJ3qcw7fgqLTxiqxXljTgbNxh9R7KMsd1t4hiGkJv_9FeH-dLYO0G

sprite $octicon24_comment_discussion [24x24/16z] {
jOy55iCW40MNyEE1kVzj-x2wjnbyi5rxGQTpVDEUI-RgXPqZFlMA5AxyDYenNdjK9ZlxKxv3aipLcozHgMSGaaDNQOgGthpsgKjzoikPKsQCfzq8wWAPM2xN
9nZ3R7U0kzeUQ4lwPmu
}

sprite $octicon24_comment [24x24/16z] xT0d5e105CNGJAF3s_zgwVsVKLYkZ0nP8Hf-oP8L80f3yUX_zrf4g7K9-sT5wZwU0ZkbklTOqfAjJ2QJyNmr0G

sprite $octicon24_credit_card [24x24/16z] Ow0IOE7Xnm9uMFZOMR00TZv-5gocy5CBu32V774qW-7YQ7uYqXnCSOXs8jt3WTstN8miM04Z0uq1

sprite $octicon24_dash [12x24/16z] OnWWm884-740P3K3vKu

sprite $octicon24_dashboard [24x24/16z] {
XSy55WCX30JGA0vp_zls8NMRTkrZ2VqDYwgyeLUi97bawnZHpK810X5fM1pHZ7OaC56el3dpuvvfio5lWAqLhIpctfXuairllyxoESr0Emc9TkguRoqLSJwp
4YCULFEngbmcyCC09iyWay9s9JRzLDNwTkFjurI5Uj-7CyQrwraK2hr6vzm4UVKuIP5UM7RB6VRiPU_07Vh8wTg53FXzatBVLogQpxMiyVHyuWD01u0iTzqp
Swl9hte1
}

sprite $octicon24_database [18x24/16z] rP350O1G34DhtoNxJuixBC0xrINq3OjE26-kHHn48zA6R6kMnJBQ501T0AR0lUQBzWfeUmPks_kylUZzGYr0zRhlKb__kUkk_3SZ

sprite $octicon24_desktop_download [24x24/16z] {
jT055iD020PXo9juThd_QUi_TM-_Pp3nM282I-zsbjX2dTXQg3rRhkvizLNNglzd9XAdtJZ9wfgKrJKgFtkkm2l_iEU6FkuPRkVHEHXsPsbpE_2oxKMxD7Fi
p8sTSfBRGsi
}

sprite $octicon24_device_camera_video [24x24/16z] pSYr0GC134MnPpY6l_-qOOwxe4hn9ZdhQawEsc7LhPKz7_K88FKCh5U1M5Jfz5zyL0bQLG2VweTEKgzR0mUnoFAMSMJ1Xsq1

sprite $octicon24_device_camera [24x24/16z] {
hSy34WGm30NG7zJ8_K-xLZ4xwXl7mIcKx24I1jvUWdu9actTmtYmXJxOJGtgDmCyxgGiOGebAQWFuGfgZpHqY0S4Uo0QuehNOC4u_lqBq_ZAQsu1sq3Wxs76
z48Xa33WRDALG9pidxeFT-txC0wv0W
}

sprite $octicon24_device_desktop [24x24/16z] vT2r0S0W50HGtE7sdpRkkNJfU1NwJVp45135D6y8ts1e57HtpkU3Bm5Kb6OJbbVxJkwPPCMaxlkTobXaTJkMnhmYS2C

sprite $octicon24_device_mobile [15x24/16z] O-7ZHm0UC0y1e3m4O65009PXoCK6U9aOc7WHN5QWGbPiN1uKnNpme8Jm

sprite $octicon24_diff_added [21x24/16z] jSwr0G0n30H1iwLe-w_scHad59xPvCEIDygQ4bQxWGT5uCkY3HKWL6nV38p2Pd5p_SUSe_j5OKrjMBDcIma

sprite $octicon24_diff_ignored [21x24/16z] dSYt0SCm301195jPs7zRTSzOySgJAO-Uov6Z8qDwaOjfJmPPZgplKRAS2TaSoP7jaHpP7gbSbS4roP5Oo3r7XyP8PUO3

sprite $octicon24_diff_modified [21x24/16z] hSw53S0m40F0fp9u_sdBN2kYdFZHGdbykJJuQn3o5SXLDBTlqLe0hRsAEc0rwBDOObS-YorsBItITVg8Hqg7F-KgrlXhDFvKc1a

sprite $octicon24_diff_removed [21x24/16z] Oy0Ac5dG0JC39pycuEHdmT3BmZ_mWen8BcU4289816319uYfVH1wamDRTC0TZk81R

sprite $octicon24_diff_renamed [21x24/16z] dS_L0SKm20LGYFlTVzhdsiRF9mvLINKaAU0iGD6HmaPGruAmjI02LuB8yYV8wWPt-XjK-B3LOBszlcXyafrzaxQ23cU1rHbJpHK

sprite $octicon24_diff [20x24/16z] {
bSi53iCm40LHRpjb-FS_RI4BCeWoYUb9stuXxtLebU7T2hi2UIex9xulHAT2qJ82opgqCADGXA4uZelz8CpW8g0tv8Mji_ijsc_8wytmtB1brhV5dXVwDkEj
lhlzx0i
}

sprite $octicon24_ellipsis [18x24/16z] OnXGmCY21XWv-D409pys05JApyx2mWvcW07GD7uM1WOMC0DJ15CNDe1fEwOB1pR4

sprite $octicon24_eye [24x24/16z] {
hL550i0W35iwD_Z_Qt67tiY6rTiiau7zVDvhfqPwoO2xr6oom9x4ftl21hEtin0_mPsUf70sAIevt_AoVT-MpV3P4o6tKS2U7mvfOUoS_ZCN9pWuEHU7ozlM
YM3Mz8NK5pi7Vcxbd2zYU9aC3G
}

sprite $octicon24_file_binary [18x24/16z] {
bSu55eGm40JHpgFMPUv_MgHd1PV2Fv14qof-LOPxz3ft4kWN9akFB2Dg9TfyJkhkBxHdBftevBVUXOKPwVz5-KhypodzKg1JeF-NDFmB2peaqzazIvxdrtED
KVV2gA993G
}

sprite $octicon24_file_code [18x24/16z] {
dSq54iKm24LH8ExxN-qNmhpQQ6_zD4BFd4TEeQnJyI_B4_9A4104106PeB3kuasYtI1n2P6i28dAkf6AWP6AZBAb3DcYPB3bJ_o_2K68xGP1xoMlMuNzBQP7
Nm
}

sprite $octicon24_file_directory [21x24/16z] Ow0CiF3mGm0t8qAGZvq50lXP489mDeeW9k1ZuSScoZyo00_M4E738aPXn04

sprite $octicon24_file_media [18x24/16z] {
TSo54O0m0CNGkXwN_QV5-NZGlefvvuFoApGkfKK8HeML92A9I2AIXB3-HIJ0yWb_ebqI9N7sAJK_982zYHqWhsSVaW3i-h-9Ooa7M6YHogKGe7EhyguyeTdm
o9fN4m
}

sprite $octicon24_file_pdf [18x24/16z] {
PSfL0iL024FH8CD8XVslzWdKUpzFWdUYHnBG_9BznJM6QIP0WrBONP2qYOGa7SBOA8LsGV4Kh4ufwiT7xbBcrkyo5tQzYZZ1Lhb8Rm3CU-jc8R8IMElYcO9w
jsMOilQKilfGGaHSFM8SQO3X8GqFCTob-QD6-eZmwWi
}

sprite $octicon24_file_submodule [21x24/16z] jSu53eDG383XRlatlBt_QN5u7a6-M5ENU-XjqtrSKYisXakUSP1CAPRBMaahJdCa4Gxo1TYITd3NEVx17CGg5bMOTDvAzfcaeabIaNic

sprite $octicon24_file_symlink_directory [21x24/16z] fOw30K0n34IlThB_jDysNXaV_g4pzoGnEydf7jQpS_gld7j8yv6Nhp7kmAcXwS094LSUBz7XblqmuYUVwnthJ07fmgPdXDjFj-P0fztgo_rPGMsVdG__g04

sprite $octicon24_file_symlink_file [18x24/16z] {
hSrL4iH0549HY3lxN-q8zOeU-SsDdxJWltv8lM6LMjDRD20DfaWe4eg48Wlz61Mv3cy-H7X9OnDEbzujBE6kQYnPfNsHz5x9qcaYu3abanVtkYL-HOycH1N1
7RBefvN3JyHVJm
}

sprite $octicon24_file_zip [18x24/16z] bSy73iGW44FH0SpkgFh-juqefghnqv-I07QN09Miv5pw5I7c6OLqRoA9WIQQNudwLn1bhb-LmFcLvFmA3r_n7tV9MfCaiBmM5qa4G2m2bXPH3-8yye2ZO5SV

sprite $octicon24_file [18x24/16z] nSi33W0n04JHshZ_QTTRA-oFNsP07IOX_83oIUmMJq28F1GaK910b_YdG9UGfsz5_ILPf2qa13_n8RBtjIh25ob8YY2eEW4

sprite $octicon24_flame [18x24/16z] {
TP050aCn24EXxhd_RJVIplVpjGz7hgH5lr5htwYYVFi0_ZCFWFH12e1y_pxzCkYZ_VXfDR1K0YA16mRiaD095a4J8rRGJL1bjz3vtWeky-EPTE2fGkxRYup6
HkQBLFjNoI-IAjDhMRMS0f5rAVRHHUcp5Sr5901wI3WRYOZF3SGJdps_6bN-wWO
}

sprite $octicon24_fold [21x24/16z] {
hT310K0m40NH3GF0zj-jdm30oG0U8BRcxhRt0-OWXFoaZSUQvOXH1sNKPAKs8xLNG9162q2bdMR8B5LPAXjqSjVTahAtcE77MAoqlJBgRc7JtN0shLtf_MY3
tksg2QWGBUboUFe0NeRkJmJiima
}

sprite $octicon24_gear [21x24/16z] {
VT3L0OGm44NHbucYj_zgTt67ynSPrISVJ3SzxVqZODhbsiiLe9X2cpMAGCUi1w86nfdJQ8oaII4r05bRVD8eJT6J1egq1ZMIB7M7PWpeisUY5QlxfS_Ny3RP
lT17IvbxyuupMwDxPjqMdviWcrRdvEkidKs1LosTRinxVVe3
}

sprite $octicon24_gift [21x24/16z] {
nOx50SCm34ND9Df_svhBbqBoZNf2zLxMcVdgpL8E42l27D2ik5olc0nLOFA4BhQxaAktnWcrw1PVsZ_uZeeyg6OuSKDnVx32LNb_w0ryJc_mILJ3nTsbYrMd
Guntmm_e-6xqhDMNkW
}

sprite $octicon24_gist_secret [21x24/16z] {
hSnL0WCX34NHIqWOdxV_tJPrVkezE17-8XpmWDwg9HQjz4ndHgVfhD6fVbPvhWow6ihrptk5Zncu9x3BHyno24a1hYaiTsa1Ifu5MFBqoArrdotFiDosmgd2
eMnv6aeZZFT3C2avKiAL9gZhgO6KJiLhvKS7
}

sprite $octicon24_gist [18x24/16z] fSz50e0W54NHHzj__wkbcvbS-rY0DI6712wQkaXYIDAEiBohmby5g9Td2N32TmOAaY5J54soV5KdYPGXIwG8MG9nWElTMOpo63baFldHq2VnAmS

sprite $octicon24_git_branch [15x24/16z] {
TP054i1020EJKwhy_xUTNDqonkA0fsAy00UpaGTQ0f8Tg0YdewhkKOvc0zbljPQ1R4ZkIQaJbR7XrhCSgDgU1yg8EB6wyyJeFc15XbXSkGq7RofRXwOnOiUf
f80cBUddnKMhFWwS_yxde3CVh_lJ0W
}

sprite $octicon24_git_commit [21x24/16z] pOz50e0W50NfXhd_QUtMlSpcTppH1JQKOEyfNPcf-f9J3P9FqDIPZA3dVeXBR2OihEjcPqwmieufRjoJd-CVXpvU-dh-M-R_Z

sprite $octicon24_git_compare [21x24/16z] {
nP674S0W3CJe7Rp_jdcE3WD4rsJ5wMn7BflgLHUUd4kyDHhHGPHh3GHTDNDi5uYbHk3F9d3FDNaa4bWZ-Bnx7UKHsHpto7wAyeoo7V9754IUm_tn9Hqr_Fub
UUZL8XQEa1dG_jciFDTiqJ__4SfsFW
}

sprite $octicon24_git_merge [18x24/16z] {
TT350KGn20HG9kxflzjTFXTYStmHX2wnbfQWfjIW9JaYbxJmERgMUDn1IQc3TDoSqnoI3vdna1dbAsD5yf-6D-0g5IpEzlb5Ec4Xn4-uso5219VAK7SayeyM
hYM-RYCyjl7OsB7LS_Fl_
}

sprite $octicon24_git_pull_request [18x24/16z] {
pP255SCm30ND3FjlM-bTsz02-G7VExFCF_uWi0P3x2YbMn7xPuf0A28aBQgPLiVbJPhzZaaoXXJMQTzrRD_RoO0jp5xA_Z3cp_p92upUObW4J3KmyD9gJ0py
7FDSXyeJ-9aF
}

sprite $octicon24_globe [21x24/16z] {
VP47TiKm20JfkA2_zxzj7WyvFHdtOQrA_o6gmj_KcMb2XtzuvVRk6LYsNIxjYfEz00Gr0SXKkG30Em7Kk4cY8nTmZ5CC9mc0DVB0HgBlHgIXUF2pxoM4EXER
e-R1mdN66daLXbH3-JHxdtY8xA4cW3FmJb9RIxXyo3qlWT251n-PrynZepElViI7PI9PCNbigXSgQV3NqwWkfmUEQYaU_7tZbEa_tW
}

sprite $octicon24_grabber [12x24/16z] Ow0Iu4S2B4W0btfaDSXwARAB1W

sprite $octicon24_graph [24x24/16z] usTXm0geByx8miA8JPo57yYciJY494SSnXxyuh0GHf1uumK7OC4167

sprite $octicon24_heart [18x24/16z] hSg53GH024JHmTUt_shFbUZ9Ymq_u4iIe-bvQ1qX07oV-NF8lZAx3OcTnCXbj5oQv-AS2wE_XmvmVW7qDIZEx1aCL_h-SIRhV2_14u-z1-CLzKvuHuG_Em8

sprite $octicon24_history [21x24/16z] {
VP474WGX20HHaIrCy__VNirjZhtHDWBoHKmfnPC9kO4q2qAKJqUth6eT8rD2nT1KPhHXeeJ3mxwGmoXHvKX1eeIUZe4YkDa9-z4men9XIQzIu6tSv6X7AOJI
SPDmGpnBRXGndUHyf89uaZoy99IJP9WY1W-RP4AMHPWwLTrIH_90DzsIl13iN8vpuRxu0G
}

sprite $octicon24_home [24x24/16z] {
dT053iKm30FGu4YBSl_JZgrV4dsFdqSj_Pzr7NF4LLYcDImIAxnaegjmUC5taV0Veu23KS31ADQI-s9DfIgQwyEzNuMQXTVkONRVkiorpylNxzUkc9dTyJuk
dV4zJYbTxjkUX9LkGL-MgVHfWVjM-kPmoIfAY5eHy3Wd
}

sprite $octicon24_horizontal_rule [15x24/16z] fSu52W0n34JH2Nm8FlS_xRhxjW-fH5M1a8B-0jtTT3TtJtTOd-Fb-JbQQnDoU2QTvzfrZV7oY3q_OayLMW

sprite $octicon24_hubot [21x24/16z] {
hOv5OW0n30FbsDvmzF_VjijuQ-TW1k4_44kbbsHoAKLcLrNFZ7jP-n5Ax8ePes7ZoC9iRzK0v8WxCIDGRF1ac31C6IqwIRV5ne4yPGSTEXIoM2SyTmEvLMPB
mXeDxTYTxO3nj_Xuj1QV74Mn6RaLvu17_BtUeZs9utXz4_0tVW
}

sprite $octicon24_inbox [21x24/16z] {
jS555WGX34317pf17vFxdtRSa6rNiHTq503noyW5ZiQe7M2PKJP8niWIL6Ma5Jmm2ewuC1ANuCmyQ6FMD6PcEHPZPgKdLU57L5FtkyPFym_bG_shcxvOzxDa
NnNHbR1p0m
}

sprite $octicon24_info [21x24/16z] {
VL454i0m2AjGQepy_xLJRhvnbiPgxcz2f1WkZES1ompiToujIugqICcu0Y63iIElW56FaA_WHKHRbsJsXkXSn-OJoEP5Sy5ATgTZ14QudnXSOP386uigkd4A
L2DL10Q17Kbz8IiZtiW8te-qand1DJjJ1zRz0zfnpTWrspNV7iHAzgSZGJP82is9KbOe7I4MB2Fs7JiVOjYPrva
}

sprite $octicon24_issue_closed [24x24/16z] {
XP470eCm24N3qj3rxt_R1XTqYWDzOTFEX5Y4wPsAOv4kbTAWRgeMEdtuXddxeuuRxzOtQFegVBpYow4hMFN8O9Y6njmg3m8ESqekaUw1eIZYxLpWUpg69MyE
ls1QWsdoY1hfFddp7a5A75BTMtNEl4MYmhSwGtYr_EYhH_cVSp3uzxdTw7FEd7EkU-brBtMFBZ_sVYPF
}

sprite $octicon24_issue_opened [21x24/16z] {
VL655e0m27I0MBZx_w-rU_Uy9LtL7qHLvSL97bWHdYvUdJ6wcVc8N1-y1c77rmBDzd5qjr7guCkZw3SImFRsqFMI5rCM9LcSNCmZX3ZamnHuX-fc7hykSi7C
GPcNkPbTvbUW2mAdAR7aQPci8QnrjCby77nm73C
}

sprite $octicon24_issue_reopened [21x24/16z] {
VP655KGX30IH9JZRVxVtmdrtP38ucA_FUU_ToTZGg5yJEsDexkmI0EaSGILXX0tB43H6bSpCTfyeKrIoQgGmwqAlJ1obOr5MkqiJkMrjbuxYSPM6kOsR7ErH
vXK1hEI5xk5s68_3GIeKkbqkrdYMepHrWbmk99FpNFlLTOe15SDW5o34pZul_Jz8bkS8zlFXxjyF
}

sprite $octicon24_italic [9x24/16z] hOl50S0W34M1IBrl_sdhBZVY-HBk8N7TDQHvHxOZUElXEqHrFJgwi9dAbG5R3WDPZX9YHkr_Z

sprite $octicon24_jersey [21x24/16z] {
jSvLWeKm40NHYdNZT_-xdSRbUrxX1qX2L1Kbe2bYhwgwnXQd9OuJPugs1ig9RIBjQ85fHn_152sPhBnZtm6r6pr3KjbHnjtKZidB0zj8bAU1HqaELMF2fFay
LocE1FAgUfmn1H9OxvtwIpndV-9pdIS--myigfzyXbwVnl87
}

sprite $octicon24_kebab_horizontal [20x24/16z] tSU50OK020N00txOxZ-jxH1AllF0YdRumdTeusOxptEIssivEModgEqDEFZTSX0RlZYP5H2LSF0jjG8

sprite $octicon24_kebab_vertical [5x24/16z] Om039cP61bP-VXv67dv-VcPE8C74oCd3oe06m69WMR0wi0wmNZ0WoIW

sprite $octicon24_key [21x24/16z] {
hT254SGW04HHt67xhpOUbdFzOvaNNBnCQYslI4KiHJMQnbe1z81beIo5p4LsirWoouU1xHY8OPXzJaVfc75kn946pDwn8cyD-jRYzJZ3kzCEe16wUNDXdCau
TsX_M76jj7yr0m
}

sprite $octicon24_keyboard [24x24/16z] jS_L3KC13CNG6ybbyFxJbXaV7laxa86mzeCrsnaVpBQI3r2YXjSaGEev_37dDQzpwYdrunorrHmW-FUl2w9FVvtzdJFtesNnKMLaUm

sprite $octicon24_law [21x24/16z] {
VOq7aiCm30C9XucRfFt_R-_0II_UAP2MBGvHAjwPWEbTNe3Bkpm3vtXdxlERoO4PUR_wpvWJo7duemZ_s1H0Q0DmkwXbW6D65IkwIx7E5PgTe-Gy2pdihrBe
BjpQmO_xgDEoqfL6SIfvecY9sQ_ZEoOZ6ooAQ9PQt1TtBD-PEapl3dYpApVMkrC-KFpY3m
}

sprite $octicon24_light_bulb [18x24/16z] {
VSvLeaGX283X7mzYo_vNUsEOhk_583avhArHLI2avYshsjoPIDWznIrx1P1LkKXkG1tSg2V43-uqut3kvVxyevFamfrImPKxCuFTppfSU1pM2u1DBdHBB9q9
rvl6k6XvNttVKNVikmZNO3UkF2XN6eGlQbGbhjBoFyOTARDfN7y1
}

sprite $octicon24_link_external [18x24/16z] dSe53i10449Hjc7Txd_RJjtrnyWB-1LJbRfHnugbX3LnkHy4VYzc_-d03xA00JjP0y19L1wWeq7Gv0ww9e72Nd0bhFyaMMwoXQLkAiIlMW

sprite $octicon24_link [24x24/16z] {
lSg50SCm30J05vX1-qyRLc20zXBRWiS_i1uO7zpjqjyRjkXbjDUY9i2b2aVl31jvAURLlZU1zSGUyG2PG3LFESiTpGZe6Gg3WD2FEZQ0HiIX1W2v1oNKFLvm
2kMyJT4K85oqmQK4zsd468vD09URBxXbl2Hp2HyakXF2xwq
}

sprite $octicon24_list_ordered [18x24/16z] {
XSz50iGm243H7wHUkFzfnwSkRvVWx8cnvfbiM09jJfhlJ-HatETubusof6OcNDD-qCsFLYEeJGIyXJ4d0nAw_f5e1CGcCaQ4Sgsu2ojMDy66ZwjBMpnhY9o1
fDB4fAdRRYpRmmetdW
}

sprite $octicon24_list_unordered [18x24/16z] Oo0BSF9pW4auuE3dvmMAmFb0BgOQ1Ye19XOcC0a7JBpyF40HNeHTF9WYcBemJQPUQF1ZX0OdLK83

sprite $octicon24_location [18x24/16z] {
NT15Oa0n20JGYH52XFlVjeLlj6ypn0Kcjx7MQ1ctn2fKAuboWYbx5hWyTh4uX1UT34X7m8AYlZOJPTzJIsVVItzv5tTfbc8zObMLLIstzMplMKoMP3rNnJHW
M9LX1jrd8TsX6QiXQ0je9-6LZetl-8hhFD_ftgLw2eTNkQpjtbOpGdMFtBe0__vbCC03GPf4Co7AvsJyLGfkFm
}

sprite $octicon24_lock [18x24/16z] nSi53WH024FH4iRjt_-qw-xHVR46MXrucREuhZ87-VOmIvdNaqCnoGhuyL9OfXsRbEFb4Whp620TGu8VBs5nPuK1uLPUW6u500KUBnPkB_zT5Huq2mzCJxO

sprite $octicon24_logo_gist [38x24/16z] {
nSw74eCm30DG9t8SJDpg__-svDXqtgoOvjx9o3-IYaVpgkaJmkrcggNUVHeqlqQPm_hMXxZimVmScnnYUbPUbweYJtbIXUa7LUFyjJSd6ybc8Zemt3sB-qcr
hjgWW4ujmEW0aiHSYPuqAusdZOiAJicpCdzI-yQyAZ0___sJ4YFTzAYCwQpcTxLe1mNgi-f9BBkIDhvM4dPGO7tJrPTKNqPbAm2ATpLu4fXEuxm3j9pd4cja
kA6_JsMv1k--bCBPv0zv
}

sprite $octicon24_logo_github [68x24/16z] {
tPA7aiCW34HND8CCzl__xMb96CRfoPIxoqkLLlCeOtmPOIcjwX9mYJZdG9o10zvxcPLRzpCU26iMJBarUwdxdezsIyAisZwG7YKsHTvnvDt8CSIafsW1dFsu
rnqShmw3nE9T1ySyBdZP8JAEWecg1WGsLoqNZb1A0U1jHkZ8oY_fgTBR0QmRcPEjEnhXCA9zZyt9Fb2WCWLQh-NWQ1mVt7BKtFgHshK3uXc9F754G3OBU9O2
RcSwZdSQl55lEVpfEbT-RI3XfcFUwMr7iXCnw0Nyfmxju-jJnthFiJ20KXASNouSyT8n7iSq70cGPZ-S7qo7iAXwuU1EDsL41z5sth1lGx4D1rAlBnpSCfaE
Ka0abiOY2f1pzZ1YPUgj15bovlPuNWtMXTYSpxRPX8dW9GH_c1y
}

sprite $octicon24_mail_read [21x24/16z] {
RP075eGW30KJEll0kVzjLuXTHsb3-m_PSSN9amZ4kzB2eEXXmi992oQN74xoOZSGv2JWPhrAu904oOmwX71AXdjiNp5vTAuo6BhBLA-PjL0J18dquvfEj03Y
AbN5MYScxJcYZkg8Ed0DQ4wkKZCzTR9Uf6ya5KqqlqlDytoxAUkKler4HwRc0yoT9-CC2cz-6jweVF47
}

sprite $octicon24_mail [21x24/16z] {
jSr70iGm24DHcU02ARh_RKVJKzRvosS3kAF9pqq8NWjcmR6IyiMmpnPPI_hEdDaewMm_Q-no8NmR7nkRuuEmpF8waOOlgh6OJcXWXpvtDlRPTzWrtTWqtxze
-Hfpg97sGjyQ_hNDXGihzbN9uBKeVgtWXXu
}

sprite $octicon24_mark_github [24x24/16z] {
NP49heKm201vqDLFcVlVzeV4HkkuThe2ScDjkizcSb23cwYFLUU5wruYE0YJH27MOzSYDBr34RjOSowcIW7FBO7Z50fKaVXw0oBVeD_nM0E677IWJQ2Ste3f
U_bp8N_yCTudq4vVWTa0F_q5D2FVt-6OBFeVGxVL0R2ok-M9tTAQmrx0AJ9Ol_G_O6-en4_I9l3anRYAtZ44WBthkCVZ-ZhRsZu-GUh-tFm3
}

sprite $octicon24_markdown [24x24/16z] {
jT053e0m50FGiXMNtl-sV9hW45_HlVbGEfaVoUZqcH_M70_98JuDsKgjtrhY0P0MjV6XHBzt1mTyEgeVnwVdU5983QVUVQxGk6NQE6btzPHzt7myFM9N2-ph
9ndlVKUPiZypptx_dTlVEPVE2W
}

sprite $octicon24_megaphone [24x24/16z] {
ZSzL0eLG24LHqjOp_z6-0Bltvxe9lKhrJBa2vCZMDm8xsUn4a_F43e0cvnAfscBoqFA_Nonqyb5z25iyb0pOULOTtAB-u8YE-pDkzyxZWjVznkERcQvy6YjQ
UmuyUm5mUgpCJjBqDlbKNbAWWfuuILFJmSyoCthN5m
}

sprite $octicon24_mention [21x24/16z] {
VOu5bW0X34CJYXJD_M-xRygw_L6W4LoOMz-pbuHtM2MlfVgH4nVRA-EIrqhtHmtliAzdDgdY4zmEO3c-K9HG3cEWT3ThpvyATeczAM-Q8HgUn32QV19Zm6UT
pxVU8na0jErHvvQoE48VeqQh7Ba73wT5JjRLzJkVOz9YahTnt_3dXsSIQSv5q6KeGkYbOqcxwzXx1dCcOExb5fZuIPBZ9rcT-85jDIEOh0-ymx8KkE4pDBD4
_CSB
}

sprite $octicon24_milestone [21x24/16z] Ou01Vdv-E9km8070p88Am6ByQ80JACW2PGEP255CGNvsx2gPCCp4QZiX0DGuqWG1

sprite $octicon24_mirror [24x24/16z] {
TSu54eH034JH3kDOt_-sMmcf3VfNUQE8f6VWMTx8BdULpi8wjdoVF0JCABua9WFgaB4bU4adkyEMnEHmo5WJ8AjD3hSb5PdGXdksiKptOTyc-U_Ap4UDpExA
b_AtV-_pVUxtFJsQtNqQtCh3fR5AcjTySQbief2MEOMNlK_myZgcm-qVehBrgcuh8zkLIA6Hj1y
}

sprite $octicon24_mortar_board [24x24/16z] {
lSv55WGn24LHdFZV_shRSzgdzOOt0dHO6Y7Vc0kNPkhJs0fUAiPNzFRGRjPmhned41NNWYYmIo8T2hosKfak8JtcnXbAZr0lhoGwqFrbKq55lUuW5sIhsmCO
09gBU0FmuexTYoSWVvpZoV7g95xQdAtiXRR_Y4tf-Cu
}

sprite $octicon24_mute [24x24/16z] hT7L0O1G34FHu4xstnPtxb-3dmBF59ww_EN61ZQmWHTFj2Hzi6SOweN7KldeCukutawzxxvOix3yzAMmC3dzXzgbVlAuhWBF6nHuNU8p0G

sprite $octicon24_no_newline [24x24/16z] {
pT255GCW40DG9FSEVTb_sagWtW5m-3ZXl93Bd2N_iBEO5VeR0GZUqxtv7AYtJ39Jx2pCOYulPR67KiG4G7BQvc1Jh20NVtahPVFxFa3CB8lJsxdx9kBnkkVF
k_x-mzdX2W
}

sprite $octicon24_note [21x24/16z] jOq33W0n54GxIVrr_zjkiBRwug7xXcTRmrwJNvFK_BPiXo9cNGoYjmb_huv1dDVzlNSiHJ_hRkeln6nR2lmMk0Pq

sprite $octicon24_octoface [24x24/16z] {
hSz7Oe0m34HHZIM36ypzRnj9wOd3Af_-QBRyMxFRTx0sVG-IImMQGNGvGAHmK_dRiU6dxyoTJp5kixRt5gCTAX6G1nrEott1JINJE9zkdNJ2nHfSUK54oNxc
O8rSuOkqdDBf8kaCftiU3E-JQ-4jfvHMyykr8HmjBv8QLRwbR7aysAoyOx76Grx3CUdTDxrH8P-Xg9gf5iXpBm
}

sprite $octicon24_organization [24x24/16z] {
hOx50GGn30DbM0ou_sgFj4olcvSyYG5Fg1ikQ2CYAuvOV1dnnLFj1QIB7z-o-OOYz2Ez0SBKq0TnG9dwetUcGfzOsU8hFQi1YyyW3VDnFcmzdvr4VmlQvMQR
fv0aW6IUJpsHnGld2rVDrFK7khXYH8fBVBZs0ymdsgtFMDcq9iEVU0C
}

sprite $octicon24_package [24x24/16z] {
hP454WGX30IH18Vv_s-FMSxTkYpLICnyZVL1tBLqMbeKpJsAFJf90BgwzQZMuEsCQfx6-jWm4Z_QOZK2-lsxWHQzuvtfjG2yINpbbp7HRxysTER5H0qbFR6I
K8DJG4v-iPaFlMDVjvxyszjRhp2sWGDS_ZXUFGGS7iHAxElQQIyWtCk3FNx73W
}

sprite $octicon24_paintcan [18x24/16z] {
TSq7biGW30JHHi6W4Szz_zkkIPldEvS96CIZzt31LYhpChkIjQoGgPWqiypGyAcDL1FVP8LGyOrIFCTMRUpLncRfSMcoLpVpsfbwHNyn19i4NvtyMSWdVPz5
tdOJudMiN5tm11Zn3Gt_5iDK7D1Lnbq3HXY_olpqE2M066LOPVYdU9o2u3U1mHgtPZX47u8tFW
}

sprite $octicon24_pencil [21x24/16z] nT0r0e104CNGMJPOzUz_MjpTIVdAsDLyoioGD5KdBIYL1aEXr34YrSh8QXrRepEJt8BnlvcmniP8NDi8ZOdPybR0sv5o

sprite $octicon24_person [18x24/16z] bSv50e0W50JGeJ7d_gUr9SstWj-u8vGIMS1nuH1PRcniuI4qAXxKduZaGTvFHizDZq25CK7BHOj8z5kJ27_7WzjZcWaDm31Zmhs1yYpuWOKGYAgk5ahd12ep

sprite $octicon24_pin [24x24/16z] {
dO_50GD130EzNaRrNssObEFJSyOe-vBSF0VcHLmG3hCY03D22_0HN3mLMZum8jq1EE5TcGaNaLcXGeAciE0fB7I1J_xFUOQx-xeyuJhSSnPpK_IpX8QRp_PV
RdydojbS0G
}

sprite $octicon24_plug [21x24/16z] nOz50eGm54E_pU3a_gV5BUqMUMWZ5NcOYCX501ngCC6YOoCMLh42iPPfk60_fABLML6qArMgHFpNyxlbrUjOB32BA3NLDr5yQf58P_-U4G

sprite $octicon24_plus_small [11x24/16z] Ow0AOE4dZia21Epy89AH7mvOY3K11XXP6AWE

sprite $octicon24_plus [18x24/16z] Ow04iF3pimo020i4iFFpiqEP_4G0J5q3vGjA

sprite $octicon24_primitive_dot [12x24/16z] Ow0UOERWvULW1ZFP-S607SA4SPZvuO2P0y7cu4MmUP7Po6gGzIARYR0BsGtK0m

sprite $octicon24_primitive_square [12x24/16z] Ow0Iu1zaW5h-0W

sprite $octicon24_project [23x24/16z] O-RXnmGSZ3piB9Y07mWPC05O6AWBbHmLXZB1W69X121H66UaOOzYPXO-Vap0oG

sprite $octicon24_pulse [21x24/16z] {
jP053iH030EzZDhv_skFiOsu7M4ujWx11oDPaj58CHhfkvm3Z4PmaakRHiAzzfFD054Ho7-DPBTuPtbGeJSO_B2UpLtv9vdL0RoKkFDpAsf3XAejWUaCeQPt
Efah
}

sprite $octicon24_question [21x24/16z] {
VL474e0m25EAz3hp_zUgZNj6kzYGxW_Yd9EBfBUCXcpzBXigYgcg5THXbNbaNQ-QuNanXFu8563puH2PoET0-mZNDcbX0O1gcNU1vms4COKOX1VCEv1eO04j
a5FTXHr2hjqEW5NMl0kreeMdC60Jggwz8p3H1G9h9Qq1iNKjBFuGidYskGlNDjy6yZQwro6_q_5Et3ic
}

sprite $octicon24_quote [21x24/16z] {
bT053iKm30FGSbVC_M_xhJYVUQAdW1VL_Vlv5whxx3WB4OP89Ok81ArjwBZKLWJyW9BM4jGqw80YOw36P2Wpi8iChneGQ_6wma3BcLH6qPDGeIf8sOw5zyT8
Dq5fqOeoYxUYxh78KngvcMdzQlJEcuejyO9EPN2eglt9NixtozCaHlB060ZdO_Jkh-y4
}

sprite $octicon24_radio_tower [24x24/16z] {
VT23jGHH403HQWmNbN-q7slEFNfiGGKlee1ouiLemS64ugOWFT0EC5X09b2UzZqRX2imwmAifuDv9wGDgLhG9hZ_TlujphUyt-ga73bPncd7oMXpcqEwBjPj
3ZUJm-34cwEP6hneXOFDYyKP9bUUXSxTaoPF1lLuFEh8axrBdABjULGwzfz1YwVYFPxe_9nrk9KRt4JNBM87Mtu1
}

sprite $octicon24_reply [21x24/16z] jSY34GG150JH-JWi9_zerpQxrFNGv9ZdN38k6PUCIyQloypA0fzPMQWr1Xpb9rG7gkQVg9mGlLQZvLclpNt909sYL-aKRJyQPadynJpxOw7V4YfUA0S

sprite $octicon24_repo_clone [24x24/16z] {
fP052iH040GZ3V6P___sM2cuPeEci6QaLXIPC8bqbxAWr3SLjYXZKEeYrFNt-gon_j73VGOFk8SyUBJboxlceoj2U82C1yXu07AWrpSP6tLDXgYBLtZztlfl
u8dUZpH2_yuBZw43hREMtkJy
}

sprite $octicon24_repo_force_push [18x24/16z] {
XSm54eH030NHaHyS-lwttS8JrhhyHRGGcbQGhrs0v1EtD4ynB4e5gfSy0LDsqh7MtMBicVyyCCJFBT1w4MkwfR1NBgaI85N_sP-lQHEnrcejRvAbTft6gmyo
FQyMBV7pijw4gxN_yW8
}

sprite $octicon24_repo_forked [15x24/16z] {
ZSl50GD1243HZwmB_LSROsquPPI7K9SPTo3hEAx26OmEFW8PR0Ao0ncKQfd58nmWWqgBc02O8WpeFqxrG5fIfoDr-nPyoB_ibyy-WIx0eYUz1mQlrNjsoDcp
xbchwmq
}

sprite $octicon24_repo_pull [24x24/16z] {
ZP652WDH30HpTE3yzl-_jfudMnry2B7bKCT6tDaaMiRZuIL52weUTVwKVg3wWM1-UWFDRHzKcREFUOtPvrqzylx_xUFx8x_N-fYlDDv9Fz8nfYVUz-5vgVbj
XF7cBI_Fz-XsNhDF1tFmpjyUWhaB
}

sprite $octicon24_repo_push [18x24/16z] {
ZOm73W8n40DJBD7N__yjScXRWBjHYoOxXZ5mbO3de8lccPG1i-du631NA1LSrNCrRYEPCy_H74WUl045FcOOXOstcT0Bc7xPvmBBWE80qPVfm46_gQhccYk3
nMLJuognnzm1
}

sprite $octicon24_repo [18x24/16z] rP3L0O0m50EHmoNxJujJoGQzh-SITcMih18fmrrHfQ0xWZnIOv4Ikvo1Z46YyYxoQMWTxigBeA7hlFDMBdx3L957sZiQl1C

sprite $octicon24_report [24x24/16z] nSw53O1040J0VTwz_svnNsBOn2xdk28L8qAbN5KWL5tpefic-JzY_W_nv5s-lrZL6TzPsQ9IxG1DhXj5ZLDTshDjDDtbkpJDqpGKJqEIN0i

sprite $octicon24_rocket [24x24/16z] {
RT254KGX34NH1BVXzL_jwiT2xlZ18ItsKL6R0AymFh50auWxa0Hxm9Bji2T709M91MTygq8fuPVStGtkVDm48pV8kazbS1GRoCs_d9FEtCRU1uz3Yw6pC6Oh
JshfTah1S1v-_OxJ6LPnGDzci6omJF0R
}

sprite $octicon24_rss [15x24/16z] {
fKxL0S9G3EHfZ7BxJuj4W7utxhdR1Hgz_QS03Xg_lFN9q2XKYS2d4zsqdGRatlno5LJYChNe7_jZXs1vFj7IxnYdX8RXvKUUsURR62FEH5ispFVPrpOZu2qD
E-Tqa6Klq0i
}

sprite $octicon24_ruby [24x24/16z] hScb0KKn40314q5r_LVx6UQHoyhPM5b9Ad0lltgM7xUWbcN7-MY-Xnp9W2CPLnuCEHYoGtR83jaXEsI7x90TiWDUrXq

sprite $octicon24_screen_full [21x24/16z] Ow0CiF3m0m6S2-Bmil2oim01GWqGiFFois1gvWSAygC2KWH1zi9jXxFf9aYXux462BQWuyCIo7mi54OS

sprite $octicon24_screen_normal [21x24/16z] ZP750O0m300hXxso_xGur58vj74n5R0cO7c-GYH4Qa8W4ruIaIs9kPqIKyNpuODC0hyK2H095owML4ZugGhhxW7KajJYgwW3KKStE7bzSHKE

sprite $octicon24_search [24x24/16z] {
dP453WGX301RD0Sqy__Ndg_xJWJg9ZzyBbQoboc-0GRKYIL1SYBYFfz17Idw_seXTcf7K-dGHYTanaaz-V-Zo9X2boPEz17t3mmJVS1lwCDEdjMwwtrs4-jy
hlKzD5tT6zJ1uEj_poNKpZ3SfNxkefrXnat3GrODwtfHhxB12m
}

sprite $octicon24_server [18x24/16z] Oy04p2meW9c1anyDSFApCC0HaC_0meycmiAEAW8671ZcCBAW0KPCvx3meMhYO-5XP-678OWGfbsO8fYwC4t6j1tJXPY-8C9sgeK6

sprite $octicon24_settings [24x24/16z] Ow0YOE67qFmiK2xvuZ20ASx80WBC6EAS_630J4WSR0IQERYz0pE0ZmNYJWHWXfZB2nDd1fl7YAeUhemJhWzD7EuUD7DGmuVQuKmz

sprite $octicon24_shield [21x24/16z] {
hOy53aGX30KhkDx_jD-wQ8ZlH1bg3mHa4mqZ34ZxAdXDlv9KPzBJKF-3Gq2tkG0lOPNgasgL-fFwr1xtHO_hYzfdUMHtxTSyqhIkDfiUIMqh7UuayDAXNcIM
7pq36XTlEUpYB0XsSGszz3Oeo6442-oou_Qu0G
}

sprite $octicon24_sign_in [21x24/16z] {
hSvL0iGm24LHqhZlVxSJ67cCM-zNEOqHbQbhZbPspkfG78nkif8aumd16eMtDPWRd8x8jdlqKqHZIFn70ghUeDv-Vz7x9pr-FBSZei9ewccAJZAdbrPiHyn0
pK3D5jy7
}

sprite $octicon24_sign_out [24x24/16z] {
hSz50e0W04HHMycv_sdfhfL_-SQ0IwACx9jF0E-LmnKSfdVVOfN7fN6_9DyhHt9-zExbRZmS2VZsof7Ynzhxxwp_kpxd-bxRhovHTmI_8rmkoxxzRUxLBAt6
fRMuDA01
}

sprite $octicon24_smiley [24x24/16z] {
TL854iGm24n2AlG8-__VNe2wx0Wsi5XQGIEBy4ZfWa41OHP0XyDR14pPj4mCALi9RQTqQXfMmPBFDVEYdY4jt4UWYL62qWs4JgxiQl0M8XEiFMRQ120R5J1v
0ercfsvRl7OXne2HnRd3Jrtyt6Q9ykBvQOO4WPZ_2HQlG_K4yZh6Mt416I-PqBDRi_LfSrqJgiyLUwXdT-mXzbR6y4vbtLjtwRBjfXnx_hZBnns_x_xr9ty
}

sprite $octicon24_squirrel [24x24/16z] {
ZSvLOWGW30JGWGINkVzfAqZgtNq_I1HFyY8UFuH1aiNZgyn3yCwTUEJL7G3Xt85E4m5T2VxhVuLdA2Id09Lc8X5XtHpov_p68oFHH6ZbuEBYNbuRgyCxuJkD
TtK7I8z-9pAb5SNYrAQLiYTUalVitlakm4H-Cd5bVk5ny2jzbEywF-amdZJ3qiEawT7XqakymoEl
}

sprite $octicon24_star [21x24/16z] {
fSx7bSC020JG0GIAlEc_sbqdbBZP_qO6NvZH6GtDmgKtahJUI2wzyTmgQXvplf8vXviAZ9r1arUf07JZsQRlhIiFgzIjcMKMb629y-TbEP8yeEZhgh--q4eE
P3e0Jt8uxiJxgCHnoGL57B_x1m
}

sprite $octicon24_stop [21x24/16z] jT6r0OLG50JH-mMNxRzQVD25Z0aFF8_x_hIpGbHirdnZxjkW68eHYab2PmDH_UE4yTUhoC51UXvkD--EwIy4FHcA-UVm3-Vh0G

sprite $octicon24_sync [18x24/16z] {
dT155iGm40DHoTCGrlrlE_qStgQMFoZZUxGSnpG2R1r2Hz4MG_4aQOeSTomfIABYK382AHbwRIrPGIcmPvvrFrqRdX6Z1hoRvNXayREmfxXcl1iqWa_W9gSq
3sxO2udelzLsC2c1iMJOLsJjkuQF6NqmIsnfXNknxokcnNvYt_i3
}

sprite $octicon24_tag [21x24/16z] {
hSm50a8X44NHgL_a_bThwxNxqGSOUHIBJVoISbasoUMSyx1VewDMjjzritCqbisRxH45qJsgkmgwnsDGpn1QubgvUw5Hv4OrZN9KRABEZQ4OYg4O6XXQH_bB
rW
}

sprite $octicon24_tasklist [24x24/16z] lOu30aGn34JJr9pxdtRvRRyo7cgmWgQmY6BI3V2Scr7ZI9asMw6cQC2G-Rkx-TzlcEhDmDZzXRlkBfoP9X7_HtNeP2fqo2l-SP_7O7HmCphBIlvftW

sprite $octicon24_telescope [21x24/16z] {
XT5L0e0m30FGTCkAa_kV5dTzVtK4An4x8oOqx2ZyYOx9STQbUBaI4AKQ9ww8N4hOXKeg4IGTsqQ4LzpQIaqQmoPfLiRhg8f3YjDsvG6xGWa-fVPz9hM6CPM9
XuLkKp5NXOrXb4gg8ivgKgnm4bjGkBJcFYRFhQOm9i-jgSIKFBN6C2LFl-_w1ti
}

sprite $octicon24_terminal [21x24/16z] fP2r0S0m40C3Pjn_sa1fVBhoKT8XGwNQarIngiUMgiRbIYnwFobUsO_5lzeLksfVXDV_sboIgZ-g5N-gdvDcCysYKwNs57N8U04

sprite $octicon24_text_size [27x24/16z] {
jT57OiGm241HP1XP_T__j2aGqfV9trZrJR7yTnqeybi5mEItZ3COyf6gNkar-onUm4hFhizY1V1hVcFH9Tiye8OtHUuFKU5gxF2gprEyMM8k6gWVIF5Gtyvt
S3P5zQFpHImmzQKMOdvg1JM8KWHQQmFkpaSbl8zc2IZ41WzxoQzKyHIQVzFjKuk_n2ik6jISmgUtPj90OpfSYSp7Vzqp
}

sprite $octicon24_three_bars [18x24/16z] Ow0IO6910qny_6Y05rC4KzVmjejo

sprite $octicon24_thumbsdown [24x24/16z] {
RT350S0W343H034q-qzRz-RV-eh37WyxgvesIeZO6k4PwL20K6o9uLcq26fhyAuGcESYlbFrFPdlmQBhOCdtGhwBYEjKzljM2I_dkhyFvXuFYkjdfsl5iV_O
3jBeCRLlIs63JrbyJxPDqwz72-iiSZrOTDVX0fv7I_2h5ke2_u8qXhCP
}

sprite $octicon24_thumbsup [24x24/16z] {
RT050iGW34JHGKBGpVrFktMVNtzrSEMq9v1QbQ5V3WPu2zIHwiUzES2PfuuYz3b8-Ur5btNiBqx3CTVXzwVDTLdsubpPU3-K8QxQN4lk-T2URGclf1brLUvD
k5kWxinJ3mRgqhYhGfatmVQ_pz_rvlS1QKFYaMJBrvl6xwXfc642
}

sprite $octicon24_tools [24x24/16z] {
RP453iH03CGcMSRy_xNbA7lNMZIooyK1Ey82nMTuaKIccoGBTT4YUaRG2Qfo4abF6AkUNA-GZtsDycYqHW3DowiM1qHfuJwNLmsMXqx8fizRNWnMxN73-R3Y
JA_4mlsbJmAvKmVyGwsEBrqBE80B_Ubw2fvIi59KoqyeJJ-J1jCMCYwuTC93iU2kJsP1tyv-f_sOmyGPWF_WWKp_RvXR07O
}

sprite $octicon24_trashcan [18x24/16z] rSY50S1020F00AbBzf-sxZB07mx-12UEKwL5O6QLhbg2ubNHJnzSpAVhhW921Izf0CHRflkXhNb-5kTUwY8mCPxcnyi8

sprite $octicon24_triangle_down [18x24/16z] pSYt0G0X0CIm-q2gs7zRt9e5GALorFTllemf8w4SBi95k0WNuI9Sn9qM

sprite $octicon24_triangle_left [9x24/16z] Oo0CM60qFupcXz7yC9eVHlF3Q7uOpG-b4Go4548nZ8Km4CP2M0fZ8Ho66m

sprite $octicon24_triangle_right [9x24/16z] Oy0DM60CVXOO0yRYXx7uOIn-68iVnkA7iVXXB7G62vfY5ZG3MT0iPO4xZ3

sprite $octicon24_triangle_up [18x24/16z] pSYn4G0G40110ABllrjpwJNWDzoIrBsEYEkW59I2Kb0AIa7r8RryzG

sprite $octicon24_unfold [21x24/16z] {
VS_L0O0m54FH58BBstzRwi7lvq6QeZRWsMGJdcPIsKDRqXlPuff7bBXRY15fePsZ3VIvY8w-mIPCMtFvlDace2faKQcoWNQEsNgetgkCP5Ll6bzqjCTucnrv
6q-wnzqLjUUXCgbCAbCE_nq
}

sprite $octicon24_unmute [24x24/16z] {
hT5L0WKH043Hgvlzh_PrZFep8u-6yvyEubqGFRUcNmLPPSTVn-QUNwwI89cENqvqgDhnmvL3Da5L49xoTTaKqU0igbqTvp6F4D2zwu9EgBpo_F3LFE4HTkkk
zYbV-npF5Rxdsjx3_jx6Uzwzoxdl3W
}

sprite $octicon24_unverified [24x24/16z] {
TP653G0n24LRvAp2_jiUgKlwOkY7W6dWvz3ii2WynopWAuaNmJQ181EXo0LP25b4Df8K9DEHEfOb0Ka-jPPfbE9fGDhaqc9tgvUtgdjB3278L-F2gjBma7GI
w7eSJAzoNmi_FQpnRhv4lGZJt9LqlxVRMbFtxA8qRDFlCDN3wMx7Ev__SlxZ-Uy9T0wxzmC
}

sprite $octicon24_verified [24x24/16z] {
TPA73S0W30J9EnMmVlzfqwXEnAaVoDrLn0TnVnRUBDPDa8ClXs2g0PG6bUIL7pG5uOyt58pQe2JUy4Ox1wKy_Z3wPkEHwhPwVVj8KVPeD2aX2KIZ6Vpp-wag
zfhXYQDuskWrnItvmUWbrwam-gXzAJgT-WBJGzF4S6xZEO_tyjtZSEyM2VsTN
}

sprite $octicon24_versions [21x24/16z] nT053e1030NHtnItkVzfSOSuxBxuH2hwbIShrwvaLsfIaOWJIn8vYKqncG45A46QecQC4aMBxokzB_zwvlj3DfRiJ3yO

sprite $octicon24_watch [18x24/16z] {
ZP556aGn28D3_NjPSF_JZj2qu_8lSH9SEJmO1f5T58ZoHsGuMocDFX0OcJMFZDaSs0m2w8n2ZM27UPx3ro5M2KKchACzHjfWUOmKxiY56L6NbGkpIvCthDg-
o6wwSC7-yiNhfozg_A_Xg_BRdIFcdW4
}

sprite $octicon24_x [18x24/16z] Ow0UO4LdSlApmGJO-3b1mlpyC24s89CLH8E5u0mu2quXX602226804888O0fWgaBqsHCsp5TYEaB39zYXWRr

sprite $octicon24_zap [15x24/16z] NSV50S0m300nEypPVzeoNVMJV2aMiMonXasFJSK2DWsMiMcnwNPstoF_PztktibYaZ63IS0K4uz9momc4LDi1G
