' Octicons{height=32px} (https://github.com/primer/octicons) MIT License

sprite $octicon32_alert [32x32/16z] {
hT750SD034HHC-vg-kysCLiO_1V3kscAlzOIjG6NU5RwFYq-kLnZhVOyRPuSxh3NsKw7KsdnWBFHu0gtAktptMV53PQMDomrqZFtBBW7T_JgyDpv3AFsYHsU
kPeXAMSpj62kPY2O4J-yRb27Nxxb3BFlytvupvSPSkIvw13MK-pqoXiAkIr-x04
}

sprite $octicon32_archive [28x32/16z] Oo0JiFBnum1y22bC09J2PI9GbWPo-Do2pmyWlTXD118qb4Ds1JuvMhbbL8uFHvA0f7eSgOLi

sprite $octicon32_arrow_down [20x32/16z] pSt70S0W30D0qJliFsrw0jW3a7kwI5YgFVut2uq9I7IK057cKH40P1r7LUAanvd6pVQHnIlqoYvzbPqeNsKdwrVPwLxPMOlLTW

sprite $octicon32_arrow_left [20x32/16z] OnXum8aXmiZDZox4nCkFBiR2puykniQF8SR93mQefgC2iEbe06Ww1c3Zno-6qCi790dRWTKj23SJzXi3n2R2OGMnYN3Oqny

sprite $octicon32_arrow_right [20x32/16z] nP2t5O105CF86Rp_jCIA9_MdyaVRLM5cgMMjMSlUi9QZOoqPf9RlK_wiDMhF9zJUJo63rxZB7wR5DRitpy2pyapdgZmN

sprite $octicon32_arrow_small_down [12x32/16z] OnX0m0y4nBAv-E60Yu4NnkHbO622iPc0gjWWJ3O6k1Okg3cy8CLGm0HI30DiR0m32G

sprite $octicon32_arrow_small_left [12x32/16z] OnXOm0LdCV7omvXi_FmmDXS_4C3aOG0eZvMDh0QX5s4ccbq8DmmW

sprite $octicon32_arrow_small_right [12x32/16z] OnX0m8N4vkTbGh3v-TcGsFnS81eAGEhu4O0DXOrG0zVBYM8cfbr0-G45

sprite $octicon32_arrow_small_up [12x32/16z] nSj50W0X34FHZ2la_gV5_fvj7qvJHJfFpcQrLmd9JiBhvYNiuIICTOIHHXYqk17czq0L

sprite $octicon32_arrow_up [20x32/16z] nSs74S0m24DHGNhL_jEcn_An0E-g2tnawtj4BTc6AoUvEsgsyR8PAWiV2sJYPrAIHQ-aj2KfkvUaR5QIidn9KPmVIFvTgXC

sprite $octicon32_beaker [32x32/16z] {
jT1LWeCm001H96vp_zFkrkFrpW_o8BOKmJ8k-u-YwpdFGNt_diFx_ldyyBRlXFmGs5jtgFoWS0rlf79jYQrsWxbvVinH_x11nHg_L7bq-PZeIWLB1idiOUIX
E9jXUpwROUx2AvEsivkPsxCpxSHgxlheSUxn6HTfnaaS-1y
}

sprite $octicon32_bell [28x32/16z] {
hTB50SCm44HHYtcd_sh389Xm_lKP1Blz8IVY7fa0miLK7Ag6KCIbE8kgkDNKQ2VYc35K-yLZAlIBdrDNyXFqYoshjQk1f2y7miptl-C_JCpAzKn8qYs5xr1p
izrIw68gjtOvPrguV94ZlcpxkVbBP9uoCoL74hLHp43kQGy
}

sprite $octicon32_bold [20x32/16z] {
jSu73aGX20HGi7VlVziDcJNv4pTz_wJ9Km7vU_OtQuuQsP3fOHn_B8SGKrbs7CS2sbGxAvlYCvaisFNkHxzsBAewdwPjhjT-mybbvHWbF_fPmm7a_OeLoYOJ
1Ld3PpBhMDYS5P7CpSUC7498kMFjU-SkbsKXMxCbbHVo0G
}

sprite $octicon32_book [32x32/16z] xT950eHG30FGZ01PDVS_BUxk_bRVfIqEvvWA1AY2EO2fZ5IP0H8Ab8Y2L9ilUglEArNlzSyll_-zV_cygOVLwhF6_YWKzTU3nAa4

sprite $octicon32_bookmark [20x32/16z] {
tOzL0aGX2007V6d0_K-xNSh6_uv9m-Q1eFg9MTIjQzIf1bM35aBXjOVC2_cch7hNQFK7CnVclYg0ZbLXgBp1EbJs9CMzI7fHsMptvnyfggNNs0pGZRiB5sI_
QrhYGMeNrKh7wbw40Ib7
}

sprite $octicon32_briefcase [28x32/16z] rSb50e0m44FH8Ela_gV5dP4Lqb_lmsUrr11RowWfMYRjUsujvSIT39G02-RVNvbPRdld7yCAZ06rz0alrmC

sprite $octicon32_broadcast [32x32/16z] {
ZL87hiKm22CjtObz_zj-XKnU_qBgI6p03EccPmIPddELjuK399bIVkFuX1NalGLZRZU9pS4NUOKfs4MU4tmJ7pbNy9wyKtZfIJt2HXHORv2ujH30gW6qu4ji
-kDYAGY33rxcJ4Ppq8VKalOexY5xaxtedSmHWWNG8ZGQt0cnbBNcA9kneapsK4tucHs3T1P8gD4lI_3az2BZJHRLzPtAqzyiZqZgxxzmeFoD-8CF37qowvEg
BpRb2mjA5WQNLf_oiMRMw3N3DRg0qioch7n3xU-OZyUd-GYezPviR-iXndvutE-7d4oB-Fx8adZD-waUL_3s--rnjz_6zpWsUTd0X_qVz_Dxcv_Vi2y
}

sprite $octicon32_browser [28x32/16z] Ow0pOE7Znm7u45AO02Z5m824uG34moD70S3bWw4WDog7BotXIuFqpWy

sprite $octicon32_bug [32x32/16z] {
pP950eGm0CIcSi3v_skHh5JNDJYPUlKMvetH2CouVvMU0Bhq_2V0GpKmbxNyDCFawnvDuD8OmlE6lzZwvHwWgpte6xVN2k4fr_HekyzSOrDlct6_4t2yfvuo
JYU81q-5IYZRl-bJ4tpWjd-zVN3b-1pYzlpSdj_BwrEiRoCr5tQOdz049g-_OGK
}

sprite $octicon32_calendar [28x32/16z] tOr50i0W40E3d9F_lxRknRanBJ2mXawaiCTZdgllIxgT7g32CN5_ENkzVT_TUdNIxMSiJ3w68AKnARJ2iPvv-JNQl5oiRnuLWO1d9EJHo0m

sprite $octicon32_check [24x32/16z] rP6d0O004CIGSTb_MnGzEEgxxrU67mTqMUcoqcMvlmnTLhgiRCkRR5kUywMyRGH0kZmtE9Um9M-BlXqZ

sprite $octicon32_checklist [32x32/16z] {
pSs54SD050DHXJNqrN-r8TFjX3bhzZlGprjLKAtebR2Y9zqrVJ_gxBR_x_vq-wexySdwLSd8YKNVICx4dKiJ7mJSUSC2TpQntJBS7NXYUAa7WqyzO1NMFs6j
E81ycicdcNoQhU-r0m
}

sprite $octicon32_chevron_down [20x32/16z] tSYv0O0W0C10VgZ8_jFwQrn1q-N29nlzVNti14rgC7Q2UbFTRnn6EQbmM3WnxvGl2g9quKnftYHAeYHAeYHAelINLW

sprite $octicon32_chevron_left [16x32/16z] lP2d0G0X40G_a1JRVxVeOJISkxJfkLPZi4q6ssImJMVRs5QsXUsFTcxjzwZNlV349ptIAp_ogpoKrz5Q

sprite $octicon32_chevron_right [16x32/16z] lT0d0a0X30FGFm55xdzRT9-7kdHbN0TgZ0gJKM5fzD1eDduRduqtDYQDXmQOVVx1XnxquWU_v45U-si1

sprite $octicon32_chevron_up [20x32/16z] tSo53S0m30NH7uuetd_QedMb2PeJFuDcg_SlcVKlWJS28V1EOu1GZ8wG9Ibn3e5EMKVvnCEAlC9Y5LL_s7IhTVso5G

sprite $octicon32_circle_slash [28x32/16z] {
fT87SWOX28PXn1H_1DxxdpRDc8RfRDzdnlh9VwiF3mWV_QDS1-oAwxUY3f1kDXF0zRMv17PREe3icm1hhwqq0nPgmgsyhGkGJytwYS0VHmXMo0okHG9Q8MaG
qc4KMayTq0ya2iF94uaaC_0ZoIJ0ZYG6O8Ms1VD8ueIJXVPO1kY9EemEbmF905rhLgX1hBKk96kjnQ7GBVZUsqgfNsVYDKlw_B6oz363yr8o-7LsLovdGCpL
zh_g7W
}

sprite $octicon32_circuit_board [28x32/16z] {
hT3L0OH054FHu9xNVxMhoDnr8J_86Or-JEauvVmMmVX4C63Gc7kRffJwi_NpUoPb7UYCU9-JgRAhxUGkbSqqIOxmJFFxzChIDKkiMRmuop3JVExa3laOMt3V
oR5Rk3x3FXdUXsd5FadiZ4GZiKzIopv9x9F4FacCNr3fvwGVSmG
}

sprite $octicon32_clippy [28x32/16z] {
fP853aCn3CMIyLRm_KyxNhIdpws5aGiXwyKJ91zN5Q2EoaHoJzp67BYPW_rnh7oehoY2eqI7uKdufAS9my-v2HvkX7NEHbZd23OvvI9E5IDl_XGMgBkWJXv4
cL7nveoRUtCkbxaQujdnVahFEkPN6QN6HYgnhGy
}

sprite $octicon32_clock [28x32/16z] {
fT9NbiGm20LHB7NWI43jVxMJvtMEhj_hYB2rTO-43E_diarKRe-b1K356540qKIz0E__pmQg_nCm5bFB07wn5Upjf3rKiwz2120CCzl2i7Ep0LkpXENI5aZh
u7Pfvj0S-ZNhu47PDRDY9d7TWeHntGPmREhNahXkGHv_InrRCO__OIly_GVz-raEJJDJcfbchOvchJDIEgCxPtjd9-xiqlqTlB-xglbCoEdDrlO9
}

sprite $octicon32_cloud_download [32x32/16z] {
hT05hiGm30PXbuEU-v_suLhHhsNuXEs4xNFMxD3RCL-iIoFawJnl0Atawa0_6x02TVuVsQ6PcXns2nKExGSa6npNtlH71hpkunHGjFFBD_kLEf3bCZdd1loU
QMuGNKm9cAs3bvmtExT3tdLhrUaDR03vBE3KExsSTLtVjQFdEw1SxjCHz-ib_ucUVpM0pMpkXEZnxUjutxFkTJTnVhxdUeAGhW_Gh9BcSqdpkQJvN8hyATy
}

sprite $octicon32_cloud_upload [32x32/16z] {
pT45RiKm383XSXFJV__JZhqNsCG32ztFIWtB_ucZ1hZTsvUw6nbrdVa4CAaQW4y51w3RUwM33Rm6N9-Pmjtx3QL9W-ZT-WyL2BqUNO2C3iJvbXK7whkKyjPY
hTNWhQVDWFJIzB4MO5iSGcezFxXjz89wvQ-JsmB73HeU2WG27HbAw-raaCyzte_9s_xkx6_ozSxvNEfRfDUQ-tcPUdCoqZEF8_VBxA5vy6_x-tt__NW6
}

sprite $octicon32_code [28x32/16z] {
rTB50SKW00FGEaxsd_OhBhbJmHuEssAFa34bHKCt80C1TqKNyC50m5NGYTfm9Zfye8J-2BIxG0Mw_P-nWIgqlwG9rA3v97IW3lK_2jIWP4Rw97CXQs1h9tj6
zfgS4JbRTYSMUzu
}

sprite $octicon32_comment_discussion [32x32/16z] {
rT950i9G60FXu5dzS__JuX1SgxFir_Qf6cjUt5NpU9XKST1TqBPdreyz_DZpTEnUa7mmAZw_UM7FStYqvmOVvB7ByDBbDov3PYtvxawPp3fCxgJpHuFrD7Z9
UiDwmth3ijfh0m
}

sprite $octicon32_comment [32x32/16z] xT8b0i104C30bAjs___R7geoqyME3RihHKUI4fFXiGIJAYCP-RmdZty0xT0VyQy1BY5ct73BICOZZ_aaCyFCC3DCoprr

sprite $octicon32_credit_card [32x32/16z] OnXWmCh7ZmVm0QNn0g0qFjFv-Gd83p0Wv3xwo6Dp5I5vMjXFkZpbzXDANmJI9ml340S

sprite $octicon32_dash [16x32/16z] OnZcW9z2CDp31m

sprite $octicon32_dashboard [32x32/16z] {
hPC7SeKm34InAUvwzxzjnkKB9YX_MfQk7IsgspzYZwM1r7XOR10K4dwpvs2bvbJcc-_M51STXvEV7pv19tnZwMJWAUdEBWcNUij-iseyrxz1tBB2KgZmIKDW
UIk_owqO82YpJ2C1THVrdDe5sg1xVFiANR4tQ6w6k8yu_PE-W3feDyfG4EKEeQEipqPTjuL9vyzdeVMuiaR7W4QRu2kVmT2NxQ7_Za_kwMWKpS-0XwZrCH1W
r_g-e4Gm1DIk_NrX1xddunMY4vqVQxvscJDgp-SMj0tMV0S1ehqVkSwty_j-_RsVhSH7h3y
}

sprite $octicon32_database [24x32/16z] {
xP150eGm303ZG6F__-sw-vwPkay3Vu0oUsHrLuRFWeTPZRuZ581pswd5c71xaDYMsauaxsg56tGxLVryVilZFVzGBwPtdeyal_gNyzRiDWxR2VRk8N27ZDvJ
Fkl9NsUll_rN_osF_l-m0G
}

sprite $octicon32_desktop_download [32x32/16z] {
rT852iHG48FX0Cyjzp_jkcMztlxeyC5WWSH3aAPsqtZfqNcftVYzyy3wVwjte1IU7K7vnH64Nnr1-DKHX5yTGVZL4OHV7I6CkwV1jHzisdV6Gv6d8jvdUCcy
PSTRxbLDuKF5OAJs
}

sprite $octicon32_device_camera_video [32x32/16z] tPAr0O004CHmX-m_BUxors5fKvqu3nDKxAY2MVfbKN6WcdJCEOFr2YmVWU7T7Ci75PPFCIdvDoKW-v7zwdtqlleVwb_gdyx7QG

sprite $octicon32_device_camera [32x32/16z] {
nP853a9H30IdWZOfzpyjxYnk4_coyfI_aptRqebW9MzfcRv17sJDMcQBCWZz3YC77rrJorXZfMM8wgu0QJ2spIDCo2DYzng8EVYXjN2rqiDXm3tzNl-z-TrP
txtzkRk_zy_dVVgEVEz-ycSM
}

sprite $octicon32_device_desktop [32x32/16z] xScr0GD140Im3Ovf-g_MVcPcKYew6GiO48OR200D01xztwyMHfg5uQOAZOIcRWmPHbq42e9Qc4E5OxIHFm

sprite $octicon32_device_mobile [20x32/16z] O-7ZHmDy824CGNwY0GCQ642nKJ6yW9UTdHTT2AGBJP0T9CQELmnJBn-c7NpOqXe

sprite $octicon32_diff_added [28x32/16z] Oo0JiF3num1y22bC09J2PI9GbYPoGuc77boqa1jQuKBlz88lxU9By-Jc8m

sprite $octicon32_diff_ignored [28x32/16z] lT8d0eH00CNGNRgQV__ROaFeDVRP_2xMbAnK9cHCVYibtzYG12Q2YMIcGIQ2YM0YcGWcWeba81b9PhAHR2BRyFqJjgrtjvx_NMm4

sprite $octicon32_diff_modified [28x32/16z] rP8r4i1030F3bSRx_zU66OwgtBPcIqKYZV61VOV0eFW0VXhh1EhUOgMOKVcCYHKzOXqxtJqcTdIFSS8LS_Lqx-A-mNsx-sUvwExohilpHI83

sprite $octicon32_diff_removed [28x32/16z] Oo0JiF3num1y22bC09J2PI8__wWSUd3HLWuJZChXIxluqZov-GW

sprite $octicon32_diff_renamed [28x32/16z] jPB50O1040Dn9zD_jponSvdl-YPD8gEm87i818q5g1rR7J6ErXv3lJq6aoF6weXnjEyOJzJROp0bnTGxTacvONByBENNQtLFk6E216DhQ1Av

sprite $octicon32_diff [26x32/16z] jT970a1040LHcLN_-vzMfbgEKzl7vAXFL4M4G3jLDoWt-Ie8M9Eq70f2reIi2LaJ8dbQoKm74jqJpTqNHWie54Y-dm7X_ubf9-FrhY3hf04

sprite $octicon32_ellipsis [24x32/16z] OnXXW8MF7mlWWmfZIl2J0K3s89DK4oS3uF8Nhd0OQUa1

sprite $octicon32_eye [32x32/16z] {
pL954iH02DnneOR-_slZ2M6DQ_g2Ew_dm1LYWAcwRzRGSQ673tE5GjDMF_264Uwv3rtsYsi-VEDbZhiYdtBM3bv47U1tQKYqpZ0slWll220dCLsAvTNCAyVk
hlMGMeGpIjI73cjIVF9asQtyHd-VytKrdxqVsU_7lRnn7-E-zd_O_oK8JVsdyT-FmGm
}

sprite $octicon32_file_binary [24x32/16z] jOz50e1008HiFSty_xKMTYVRSDhW9gayfy2Zry4EPXG4_3hWrm6_3grt2sSVrfx0cyNE-QsVdMT-nPdlgrlEF6U__-1__Q-yYL9jwYIuIGK

sprite $octicon32_file_code [24x32/16z] {
nSz50eGm58FXDrxF_KyxE24uAxByVgIrYtiNw5pdP0s0oHpWr3NGDT0rq3NGDQow7RjxjxTtfkwGh5w24tV0JsyBa1bQ7vY1xbPy6dw0q_ywyjOvZ-_5tUq5
golliivsSHK
}

sprite $octicon32_file_directory [28x32/16z] Ow0pOE7ZHm1sL3cG50AWoY7pIPB32VXO-F58yWzfC0huy4Ky7sufUkS7

sprite $octicon32_file_media [24x32/16z] {
jT454eGm50FG5Tno_zioGUlUGErb_7yYqswGCvnEDXN0Hyh0GdAfe9iAkgcW6mkwgH3zVTLn9j2RnkpROlG1Q0p-0x0OVERP48P1y0RC8as5Viso8REuVC2P
vReCf_yCa-S-GoyGdSt2xMRavXEP7G
}

sprite $octicon32_file_pdf [24x32/16z] {
bSrLeaCX40JHlaBmgVslzWbXubgVfn5zMJ2kInevtmwWOmNR9AKvk2z0bWzdtwVxSEi-k6_pHn_S1Hnq7d3liCkxy0BR8--G7lWEs0Cln4QyymMM0Ekj9wfK
wUkD6q5Q3D8XnY3tI1zpPcJkngOjLMCsFL9J1wivvhDl3Q24-MV8pG3Iq4MNCJFfeOV7dlJGYnvwqWCt7cR17hE-x1S
}

sprite $octicon32_file_submodule [28x32/16z] tSy33i1G60JXsft__gUjRUDDkFcYrHxEGjhSlY7T-jRTksmsB9aFELMeQvtqi6irrTZ_t5jLsspcyPfrKicODopc34jxk1G

sprite $octicon32_file_symlink_directory [28x32/16z] {
lT750KCn30DGVMPh_sdBx8RXdS8neB9U-3RXY_0JldpEW_QCfAUPC8kHPcWFynwmMFOmKDl75ZVwtH4F-jq1nhq5J_hD1XYsusyiA_h3bCCuc7FlX3S3jObc
HsW3fHVp5Yex0m
}

sprite $octicon32_file_symlink_file [24x32/16z] {
nSz50iCW58HX4bpd_gUjuJnIMVNVyKsK_PX8c3FPCzC1O5Cc3zd9a9qErUcGdGwZss4O7V5akSK1TU5mYtCRyIgUerlqL7U7hQiCv3a9SE8axvNmv-uxhT__
LpZooHMjRkfnyVF2sHyyOLiIQS_in-u
}

sprite $octicon32_file_zip [24x32/16z] {
jSm56e0W50DWktNtFwrDTyq0_dsyAZ3z0J7JvuJb0gY4TNeBsKb1pl8DrKaXpo65xAGGvv3OdMY0bvxV05XgnPi308vQzlNzOv6T_1L_u-ya-Vs0DaT_wBaA
p0K
}

sprite $octicon32_file [24x32/16z] vSm53e0m44HH768pzpyj3dLlj3-wRvBj4fj1jUtnXys1x9IsP_XS7JutXi-DuNQ-oOFgt_1SPdMTIYvlyN-wWzOmmyfJbzW1

sprite $octicon32_flame [24x32/16z] {
VT45aaGX34NH5_f3utV_gnr3sgWv9RWaqMOwIq57WQGJntd1W72Uf-kJ1_3wKE3qGW2WIDBbj5tyoP9hc9OxGv0gLKjYCZdsl1KcFowqCTsOudmelKwpmxX9
gcosdgfIXAqucqDl7EN0dzPvqSONk-DD---w9dLUZ4_UrxUsL5SO2MhkJ5S2FlFQv03SMzNme-FVofPdsf8spyg_Qs1Q8cHDYQB9UlFQN8mQ_4slJA--0G
}

sprite $octicon32_fold [28x32/16z] Oq02_420p1-CSXpySC21AOafnS874O198bXyG2c448A6I78W6OBEHXL0aK9JZIm5Ps1AOVeDuH6ySdZDnEiMV7x0vtTyOOOlhB774U6u7Tpfat8

sprite $octicon32_gear [28x32/16z] {
hPA5ZiL024KPWmh3_V-lNI4riZIsxqGgbDip1Fe02koKKm6WK8e005EawpWY0VMlh9yb09DbmZ4H0t0K3Gbw_YTXq6lZ38B0seZQ2WJTnHtQOUOfGizCBvtQ
CByjh1v85nuxfT8EnziEskc30tg0G5xJzyoDggGkokNr364krjEpSvpPtxb4BBP5ZiQ91Bl5ZEL8dipJT-9KuxXBGpj5E0X6IjpToEwH_-SR
}

sprite $octicon32_gift [28x32/16z] {
xP9L0iGW30LJt9Av_sdNtVrhfmKY3qVU8oeqjxHS0qso9w2rmIAKe5Kbx7DgYseQnCYOblxOvwWRYUdAgEnpkWv527j_GoOUQpQBYSP5B8Xm3LlcPCEf_QNS
5MxdzYETM__S1Upwgx0WFsSE
}

sprite $octicon32_gist_secret [28x32/16z] {
nL653GCm32ihJI7_VxlGU1CCBR3hL5OW_0jf5g4oqtqDY6OfamZkQuiSwpwIJaWF8e-0fv4U-ZwazpDcULRnwf-G6Y9tH0hk0h4bQnAtEM5gXy5-RIp2xfZK
vgSbW956-n6EyL2LgZXDL1FbPbJQaPqXQh28Mytenq6sIC42ZwVgPjNp3DL4bsnFxMvPelM09d4Ph-Cx_1m7
}

sprite $octicon32_gist [24x32/16z] pLB50O0m43iyhsR_QV5wSGtKpaqEeb9CG6bon20b0V9hEg1tZmwo52b9MFf4XZurtJxrJTCjMTyNw0jsblmknxcSrz_glpGd2tDLoiFe

sprite $octicon32_git_branch [20x32/16z] {
dT454iCm34HHAJYL4ltxdxOKibpk3kvBpF9jrC6RJ61697HQaHOhRMaMJunxQHnCqzW6t0bjObaZpTq0DDKy0FBIZ6LiQSlSivQspAsIJ82GR0DWoPQXVR8-
W5asQqzJS4-tM9bHQejUAfj6bIMwz6xf2ysuGteFU_qUlBRNOtLv3vM41gRoJou
}

sprite $octicon32_git_commit [28x32/16z] vP550a0X24HXO-lS_xI_qzxpDWRDa1ZOHY1QfXA32rEO71vSBIfvdyf8neRURtg_SHQscoxZ7OYRH1S91Vws-IbRBsUdb-uC_TdBdNLstTD832i

sprite $octicon32_git_compare [28x32/16z] {
tTE74OCm44JH8yDgHh__Qfrll2Qe02-PHr2CVTQup8fTz0LA_oMCG88-oQqmH0oK982gCPv1pxqm0jYkB57lRohsE4Rq5OdwKvQk07eN57Prw83wl0JOrnrW
RqziMFohhGrZFLe5kkTrehM_WF904gtVHZA9rj-RutwSR0sBKTN8ncKcoSQpsRgR1sPhNEP8Tm
}

sprite $octicon32_git_merge [24x32/16z] {
fP855iGW30K9wn_AtF-qQ-chU-Vv8D6m5qkGubY31AC3SGdXGXfwvATRVV9_DFIn85762KM07CRmupxZYqrxAflsv1bFkNfZ1BBQP__hUJMh_dcR-o0QlCxQ
XmTEqnVt_k_O_xafby4_3OEu3KsU1kCnDk_cvgjpyvtV4oj8amd9z_0a7m
}

sprite $octicon32_git_pull_request [24x32/16z] {
tP57jW8n30Hb_K-I7kxxtnQddjTas5AxAiyucd9KaGmHJo3Ap93SQg2MdhKd_ip-43rtQloFtaeZq38vtNKPY3bFcWwqgRpsTS_RkYM1COUZ8ViiJMlNtdak
SUbslElazxkZuOpqTS_LcUd1zrtG-Oxiz6Sz-RuBkWCHig7DFT56ZT2_vG8
}

sprite $octicon32_globe [28x32/16z] {
fT47SkqW44JH5XanSFU_sX_mcqAsAliegnLf_LPiDdlDjOPNKip6gdTMmP8UGht-RzA8OmHWN7BHvdvG8zN5Vojw17pjzoWD03yH5X3qSIssjHzhWCcLoPSX
AGCKZpAu9EthgcVZPAR8V_DyrX7Q-QpSI-EX6fk5_Qh5mpYVbRcv-ponuQg23EnaY-DE5x0cc--vrbQJOb_yDusdDRJjS3I-QLvdXnhvHd8GDNcwFAgOb7co
KrN-TFHwuS0-tRx2vct7LrOWUZEB8qWLabmmtD0riA27FFsHOSsY7q8R4sR9KR_r5m
}

sprite $octicon32_grabber [16x32/16z] OnXWm4y0Z2ppwGy

sprite $octicon32_graph [32x32/16z] u-Tdm0k6bZm_40nrUHXD7ta4dmpvKNdAqo-5W852

sprite $octicon32_heart [24x32/16z] {
pSt50SGm34JH7qvaIzD_jSliPNxd0JwljP0FhFHPOHrBffLKGPMqOXMODZ9aRIGwxKoJThgiix8Uv3hBJMTPgxDQGkV0g3Ccm5LmW4Q5XgMsF5thTAHdgMXq
x3MXZMWuLBjMlEPObIKfLnHCCiuPH_xN7
}

sprite $octicon32_history [28x32/16z] {
fT873WCX30LH0qBhWEsv_sbJ4AaGjHtrl6p_ShQitS5DowzKuvNN-QFAlTG1mbgp0B0yZ3kM02v5HaM1ACFG1_Kahr837iZeaAyEY2ooqaIRfl9RWohiCO4B
Vr0XoqUy4YcW_qo27lIz6GvjRmr-xVCf7DkRuKRiBUWAPMS5j82kDf_T8QsMm4KgjDKQr75373yslv58ZedJtj_sNW5QUjbx4mC3q7LBesph1jzLNxQxRhvh
bhFT
}

sprite $octicon32_home [32x32/16z] {
hT05aeL038HXl8Bbl_zfrv2c9jddZVEDflfip6ups6tU6W2aRB-NFF1sbmVUdfj7rYeWPpN8MGroLeF8yK_E-XSvDZ2OgoGpsCQicQ-0QQyXm3w5qqPkSSqq
H1-qAcCynjHSepRLiKHVw0wl8JhKrH6dARt1hwNeI--PvOR9Bx-qmBdqcKvUuwKxTQKu8LvTqdbW3VzMlW4
}

sprite $octicon32_horizontal_rule [20x32/16z] OnWWmC-FH8818J44IO4O721uC9gszb8z_AWC1YeT

sprite $octicon32_hubot [28x32/16z] {
nS_5eLqn303HiIwJflzgaq-FcS_6AE9JwdvUT9dxcZrTgYwBQdOxCQbZKm1ACshMco0T0bPYq5Lehmqx6ktvrcgm9xG5YjOSgBN0wC0HWoD5IvtkoVhxldKa
FP2CjfCDIgHci5gLncanq20oWrYjIhWewEf-jIgeWgjyctNrThINrTkn6LPlnrp_vfzRtcwlbvwKTPv-uit-0m
}

sprite $octicon32_inbox [28x32/16z] {
rP85ZiD040HdcQV__zjJYoxGGM7Ax3ALrlOryK1m8js4PD8TDu4Vhh6Ls-3hC9MRY6O5NRcEOjPGb2jel3afb_YgWw1Su2V2JUAmIAyZOkPpTKHkJD0HRJ11
HupD11sndGawmYy6Im_fRSV61TSlpU8N44_y2Vo9olvOsPVy0G
}

sprite $octicon32_info [28x32/16z] {
fT57WeGm30LHEJ0OI_vr_zDEHftOTMq8Z-1WxzP621IZFSk7oBJTIrq0YZbT056JEi3vhJe0-XtDObcPYHNOxQ4TgFPT97LfImmpss3QNmBPNnCsimNbrGei
Qp1ol58_pmUq0SqkQZ02sMKY5fvV1FMqO3sC4fGs8UqxW7jRnBK5Az2r2H_Ghgp1Nk6uiWEgBQYlLc6PRU2li_2_7GmOpxCV_0s_wCHiWCev9BnQLXroy4t0
qVul3a3Dpae04Eu1W1UxgmTPT7kgxXvI-5xjtRu
}

sprite $octicon32_issue_closed [32x32/16z] {
hPC5TWH124HRLcZZt_-s2O_8CkjIu_Eh5KYVKvMvO0qfb-X-yQUrtz8o0NJsFXLWn3wg0b9_FXf0FSL0poUzZM0e2iSKTCJ-72IPvXy6y3VvHZimmnvw2jnL
SRuWN-1PlLqrL-0YFYhJdW8rSC4Q35Z9VPgs76cWFkfYHcu6K_dzrpVS3JLTuMxOsovTxDyaXcI5-MqbZB2-AD-NY_lZQhw2Q_kRVN-kngVx4gx5zmZpTdve
kPfVkGFrMduM0RHUpkys562Mv-h3-nsXlZwYBm
}

sprite $octicon32_issue_opened [28x32/16z] {
fP97biKm2C2mqtWOqFrFEttIywksikdoBfrwGBXsUpC4Cp6iJNM0T3DF0A-pwXBGxZysaDs_0gp8J37WLzQ4IJPCa3zXVLO0i_Jl2i5axyHW40aeHrSWf0EL
enE5gj2TkGxKIJbpahJ0pvqJOEVEu9Qx5NEkPK_IvXvsTA2tUhynirkplh6ZMxkzSHCtRkds3Tw-tPcgBI2QLdcNJm
}

sprite $octicon32_issue_reopened [28x32/16z] {
fT874eCm34JHnKvHR5d__gTDLPe7fh5q7ftLtXJh0uPRdUNeV3AEkTCUiwK3XBVc0U3bQPXK0xZajQe1KP-6FQWl-cHfm0Dvvgo_d25AMXB01ptDPbE3eqYS
R84X4YUJGL5cjWgsPGfwqDVD6T3MhG5isy3NhHDEQ2i6TSigs7nDWsSqO9ai4HsXpPOe-Te_IYknyc_JL87ssuaEKUrXsILxT-cINJBqIF6_3cQpJDdTmIT-
tEXyjwAzkG4
}

sprite $octicon32_italic [12x32/16z] lOp50G0n20JZ3lHVxRcxPbwmnevnHBOx3LM8zWxrBKSziGuJ76UNiTJDTvEgkx6wknbUdTZ9ghhZHZLcgxhgTWVL-vG

sprite $octicon32_jersey [28x32/16z] {
tP1L6iCm38CTA2Vn_M-x6hJoyq1RMttwWo8LgwBOO9vSO2KHfN9bnf6VMGLgH8q3K1GsWot24bYMiGaionePhETACX7JQE4URDI0-i9S1mj6iC8JB1OgxW9l
Io31GIUfvAZPLWehcaz83Zq5xQF8xgl6xJjvF_ExqUqh4Dt1RSc_CT7stTYbiurTz8siyOCQKMuFABy
}

sprite $octicon32_kebab_horizontal [26x32/16z] Oo0FZ09EVdvER2mG0H70OF630OYFpi8jWziqt2wW7nW5

sprite $octicon32_kebab_vertical [6x32/16z] Oq06dFpyd202IF4Z0OW8H1OL3BnU

sprite $octicon32_key [28x32/16z] {
nT755KGX40NH_ehpyezst8fnh-qzQDk7waEHIkWlKD2kO6r9XzBbLMaSKxkoFrcnmlx2ij5MZSt2GYkd9kufskbTQ5Med90N2o3MNwTmdTApgp0ZaZFq21a2
mTvOPP17Z7jwkuAWFxO4
}

sprite $octicon32_keyboard [32x32/16z] OnXWmCh7ZmVm0QNn0g0qFjFv-GdB8qXCJ5YU4lifincV_SJAKsu_5SCV2X0ymlAKsqyeVH58domCGnm

sprite $octicon32_law [28x32/16z] {
hP45jiGm4CFAtF7zJ_iXitfUPXSZXLDz8RCqtrOtfKfUTVJvubpwq27HdxjKAKqX-UTQTj7X-h2hEgcZXpDIRT9cTq8wRPiwt2dPr7NQS2PPgPHm9ldA8WwI
j9Hn9WKMW3EH2CvavMV1cTIXagXnHwHUiuxdQK9mpfEk2yxgCapXMXjotjQAjf_a5m
}

sprite $octicon32_light_bulb [24x32/16z] {
fT15Oe0m503HYM6HkVzfgq0XsxvLz1kdkDQklQwHXt1uEmANFFGe0K8vT6H-5QsHKwXQ-9Pqus7L1D3SUTbjG7Om6MOuN9cixj2DJA8T56OA6fW4XMPXKcom
kJFPtI1gO0uJWUh6osOzvn2cvublrOE7mtgrOUAMDDu16xVsI3TSE2qERkLlCrvjTZC_ifs7nVrgTU4XEgumaITll7ZZNvgdnalnL7ZR_B4notMCcZbz0W
}

sprite $octicon32_link_external [24x32/16z] nSq50a1000LHtVpxdrOpkcFqis6yd9kfhdeFH9bmVZH2mTWf63ibPyR3E9pWGmxQvupRjnatxsCF-62TXfj6-y8uNN3fBy-qMEPcY-mOBrS

sprite $octicon32_link [32x32/16z] {
tP9N4iCW34H3P-Boxd_Rp6h6DWeVV2VhAkq2Qgz_GDpWmXOdkk1GPhg7omXz4fpKqQoSZkviNh_HH_CWUpvpZ2Q48HE50FAofOclwAq0hapS_WNnYTqoQL1S
V06QnTSk-MdvNGattlOck4mADFFiA28eNvbK16qaQwYMCX7IPZm4It7YrvLQLthTAUs7xtHUJCfgqduV7m
}

sprite $octicon32_list_ordered [24x32/16z] {
fOzL0WGn2CNe-1J9_K-xxcKzd-YBV4bV8QlFWAGSwyeTUgxpmFDwVcTMK9M6oXxvcyw8AQah2dss89KvynLdoBnMDFDTyPBuLZ2hqi2U-CgiowfZW9MsFiJY
B9AnxklswDk1bSIhr61kwwN8WBU-YWQQv36Y5lcRBG
}

sprite $octicon32_list_unordered [24x32/16z] Ow0nuE7dvuRGA80RH834-T40Bd5Svj38sVJtxwX_UGR2lm

sprite $octicon32_location [24x32/16z] {
RT05ZiKm34NH5sh0Fxxxt-seIZN5KmpRrXAhJPXMeowIyS-IT6X0Br6AfGDLou0MT0WDXdOTJxh8JfTK8EacGP6SJGyRhi8yDZQmuvX97jJLxG0UjAkCITJE
s1sXH2P8EvQpzTKVmB_tSQEyporOPPnnZjMjGGsW5mWogXug9XLS3qxPtyy55L-7-tlwxdTVqFYjdmpnx8wGjNJcsJ_fbntRkSlbj0pvyRUqep9XhJmPlnMQ
wMuofC7KGuJMyAYd393rji6cBxNgz0S
}

sprite $octicon32_lock [24x32/16z] {
vP433WHH44Hxvblrxd_QjQrmNrHfmtRCPS0eivrJs57Ep8q3xJ9QhUayOmP8QvK0vjFml9NfD660zbemzlgqMmLExFMava_jGTn0f-PJDcQx0XxRuGtxNzKN
lF40UNkJ9G
}

sprite $octicon32_logo_gist [50x32/16z] {
tPC5ikGm30ND45lg-zzsmwdCTrApHGil32qBpV-aC8c2jkBCLtATKzDN0B0OjpvEoF92YQ-48fSpVZxIS2cNytvNuCDxAuIVHARjTr3CGCz40FjxH47CY-nF
eWsYxEesQmhGomoc1iYiP6GGXk8Nymeg2bXJH1HqLZPAVY0QarqTItUlEAeLoof_40urfuP4PLK-24z_8jAUvZnBBiA17H9wYxnTn7mlERXHTki3OJS_U_uW
Als1c9bOceBO6n71ZebTJgYVdPXV2HEHEr5H-qe4z4vOw7PCt49EzCi6cZOuo4fi4vMspAQznXxYYIWWeWgGDaVdZnoDMCzXbJRjJEgitrjUxTf6cRrf2j1E
3sC7lStEGDOEdlzA_G8
}

sprite $octicon32_logo_github [90x32/16z] {
xPM7TiCm24L1GXvQ_F_Vra1gSYhPtJshjoDFWvkb0N_7FxYLpjnxtUbgHZW0GoBUJN5sTdRfMFS51AVAcDL5YKNZQ4dm13P-OdrejeavVj9SsD5gqY13wO2-
R5xOQBNKhiBqQaRj_xAviR0X21ZbNxVIRvhZ-UawiRGTlsrUhNhag-P0YVG3o3mi16ozzmAuP5PrQt5YndQGfMEJ5CsS6mlIhoK4pmJrWNgDPDDA5ef6crNF
5qTgDcoWlsw19HlBbTcvDniBi80wRkI9cJvXhjKURio1aWOYWW-RDpptGxyqZsk3kp0tHpFJkKMY_PVFkPGwcAzMtRsvQAhsSIlqGsPB-h_yXfbOY3zdzWuM
EdtDtARcQgjYOwLiwrxVc865E3SZ2m7WiGXyrP643hOB7JUVGwtHn0oiYDRDelIJ8_HByyv66itZNPJVj4LTsEdfoOpznXoyvZGtlwWDsX-AeYkx7DWGwa0d
sEe1WX0aRX9sgqbuT0JPQWLIaQw-W8CX1fY10Qx1Y9E2iU-V5m
}

sprite $octicon32_mail_read [28x32/16z] {
dP054iGm30E3nSJw_szl78zxBiEMkoC5d6MQt0cH08g7Qa1Zs9jG0A44PyY43PJLgR9I7Q1lkp_zaUlvuGlOSP5rADubuCWnYSGfrX5EdMA_thdZJjwnsLlZ
Pzwrbl4JPAt_lS3aTLKSBL5CBBBLwYGwyjie8UCaIZcJXApJg8JUE6whATLTfuG6VXiqQjSm1zS8irq3Xsfo2wakQyyaTOP1zqph52q62ATGfbELt4T-
}

sprite $octicon32_mail [28x32/16z] {
rP5H0a1G2C1w483xtrOB0F0fWB5N9J-9fEqkeWLTXQ7YN5WuhyAHX6hykOdsA6e6eYoxIv3NCFz8rqXTvKoat6HK-DF4H9UCGZLQ9eQNZAQR3SDBHibatp5p
aLovOwWqvodNdPDSJ9WRCkqc5zQAUSnppd7htgdsEcoQMK-rKvliWXfXfrCgnW5-7Zn8VX8z
}

sprite $octicon32_mark_github [32x32/16z] {
RT874iCW30J04xth_x_D88s30MzwZewmkDmwSs_PuKQPNp9Xb_YGjiwDBsqDOGP_60QADBuCWfY3zpAsgCm_srgQ1yAOcvjR705mpoA99olhW33q_vi0tRV1
GVCCiF0uE1RFvzhilYcdmqTSWWIvwJ0V9AXTjeiFqbDYxj_vWW_QTQpb7pHkn_QF0sXPFt2fkZ_F8k3WdtDb5S_JKN8_oJVcdXn1kTXPPS0m3wkRhH25_upM
no2v3WTXZoBkSnnAEQohLsrTfSNBKPzItpN6jEV3u46wtYtlX9TqvWaxazzvDhZz_oCiFm
}

sprite $octicon32_markdown [32x32/16z] {
rStL0O0m5CNGY-iZ-s-BkyDNWtCgShp0kCYk6Hh-dvfocd8rZN_MBWFJXVlWNxdYM9Sk_V5ukX5fA5euWHJqR_Wz-oozyhngyBBtSkKKnRHlegQKfQ_U-iqk
tDHiTbMUyopZcWExPZbU3G
}

sprite $octicon32_megaphone [32x32/16z] {
jTE50OD004DH74x__jFMKq-zmNd8QVFpJBMENhiCLCipr17yoyIsSRu0m-PuyY6VT2Ym5v22j4jmScaUzjflzS9FsYq5vUJIPf9SkhuySD-L_CGnZlB4_VUV
b-zv_RPfbspRH-c3Qry5VF_8NV_A9s0qumF0ZI_vlhPrzAxnxLppmxbY_0zP0m
}

sprite $octicon32_mention [28x32/16z] {
fP85aWCX44KR6Pn-zx_j5e6EfsnVoGXyGUIEkzfGTFRivHNVUT2VHrq5HexUXLW6a1-Y2TM94GPKUrVcQqQ5j0sLBiPZy3PxCEI3IHEHWZhvu08d3k8fcyVi
bsjD5agIOevHMJIcB1fDzCWYQ0gNmjPbPa2jx5onmTQTq4ApqhiH1FFfUv7ETiA35TMnunBuyskAvId-MDgljbywxSHqczuevfrCXzfU9J6ZITnMXFChxrYA
3FAnc45YPoypiJBAEP_2ZHI0eTnc15jpcZ3YcNHkWThn6pxbT0ujhHQ_cEjiV-11VoeZK1xIAxqe9z3NpVMnABnAa_AWV1YNCO5HB_atVm
}

sprite $octicon32_milestone [28x32/16z] Oq02_420pAUc7EM0bOyV2-00oo6aC2KHN5GU1wOSaYHvSXnut4B83vG3a5b3IsvK3W

sprite $octicon32_mirror [32x32/16z] {
XP053iGm40Et4Bwk___RKy4AArFko0v8pHRZ9dEC0cg4T67WPb9nAjG0Hg7dC7m70RuDmYAt5-ah0YC0oq8VfcT56wQlAWw6iyyLXuWoxBFthD2SyCWUNjX6
x-yd0NpZFMeFNtcF3f_zI0D-xTVzw_cjrxVUdtv_6qyEu13I-Jq1GDh7VWl0xpn_GDW6tWENkL_CXNv-Jg6MjLQXhlI6FuXJN8R-7j9lKh7vUpAlvuH8dkxh
uov3zdZxTCYK8_q1
}

sprite $octicon32_mortar_board [32x32/16z] {
tT2rOG0n341HcLb__sc3nrWdhpcmXVAtU2-tJ6m0DSW5cpgB5erikJmuwCdE9GlNHdOYMQ4gaoWIsD1S04rtvrIHKF63e-qabAuSQF4o0vpBuz3P2bgRLh1E
jl9GfX0Je_dTXwnqNz8N1VRdskQMfvVZUU90LW3svLoK7JsUkyv6TyTp4P_RKD3HiXSvdZzeqEI_-WG
}

sprite $octicon32_mute [32x32/16z] {
pTBL0OKm0CNG9xXb_sbnj_mMXtEfVqBQqZfzummGHXXXX14UFSkdZtbsOQQNV6J8Fd73OPk-ao-tXejFCgUu-XIO-Du_-SJgMhwrp_fduwFZUmhu_4f0rvS4
T7q7jdK
}

sprite $octicon32_no_newline [32x32/16z] {
xT5LeiCm44FHCJnGwEv_jSMfolGVXNFCZbXJDSEi-eH5HWzv1BKeJJ3wv__-1X1YwR5F0tHYqgbW1cgoNSZSX9BjCyqSZJdv8c6E0dTCCKVS-JBJpFVjBrt8
79VZorGmzvlvPHtpSh4-D-jRudvzx_Vdw_rTimK
}

sprite $octicon32_note [28x32/16z] Ow0pOE7Znm7u45AO02Y5oqIWBCtaq9s1JuxQzX6IewPznClHEnxmfGbyQObXY

sprite $octicon32_octoface [32x32/16z] {
nPA7egiX28D575GBll_RtaRmdhrNkbA-y3lJdwiibVoqd4LNWP5rqw27b0Qg0djTMzA76epfwEArAxYk5wNluUDbFi3xoxnZflOoDqffhbSq4wzNnV8w5tsT
g_bFovGIPIw5tJLljBEFJtKla76Cfko0rN1mUMEa6ggte3a_hk79yxGZZROxHzW0h8yyx0yA5xnpzDU7_HKJs4Zz3w6Qjk38MtJ7PposEgynqFG7ZW14Zezh
SVu8I7eYSHpMHcEYqyvjcD-Eg8WzkHeIwH3topptUrvwJj-aVm
}

sprite $octicon32_organization [32x32/16z] {
nT053aGX38JXyjpetF-qgzq6X_KlpYG_1Fg8uG2E8Jilk5aehOFeqhKDOdDhi-uMmiQrAwYe5krkBRr3jUuCmUbzXLYJkpvvYslk3PoekJzaevemSh9tJitg
F38UnhX6Cnoprh0PkXhX6GQjyRLcK31VwoKZ7IWoZAAviXy3euJ9mvKzhF50VtO6
}

sprite $octicon32_package [32x32/16z] {
rPC53iCm40J3CS__VzkSibN3Wl8A32FxkFgawjxdxFlw47OkGGa1IAvRitQC0B5z7EBO2WwXG4gWsyLdmxGDcCdPE62tpTqPGbKXRghjBw1CDyR1E4kNP1x9
UADNCjwE2TcP-V9L24Xs2-9oEilK8JVLOAuUSzsyW2iZnrpw7zxNnxpkxRHkE5Ys8y7wAovQ2nR5ZDPVwvA3cY6DhU2wkiZSvNnyJZS
}

sprite $octicon32_paintcan [24x32/16z] {
dP45aiGm30H7fe1X_l_RMtapLO7Z3hgDal36IkrahyLmmZPIR0QHIEuv027l9DEXoyi678ITB1gzuCJodc7Ivmu3DkwuiNFpuU7k0sbb3azhROCShQvfJYYL
MQSN6p9hP_61Mmu6MCYRjmexNuoC4tcu-yxVrt7ySz_NTHhaF6Vt3Viyfsj_uuQRxxnTjSbNashjfQiyAKUghQzSZ6TlnweyaAzczU755rvhomy-6ExJUEY4
oQEEubptY7_n0G
}

sprite $octicon32_pencil [28x32/16z] vSqf0WH124FHe0gN-zzsLAr_Uc_NaJmWUZCHcrJitA2qEu8wqeunrdbs39mqBA262Mf8wWW2Wc0V9DbI9redcZGIZOGk6EXXVW

sprite $octicon32_person [24x32/16z] {
fT170W8n34DHJozsfFkVbWvMXWv_-T9ZlpO64EDMM_0Ksjh1IwXuugr9FT93dT8_ZcIeb_IYxkckFgVFwcrw-_Z1azL1RgELl8tK1Iz59-gK_3goSDEYVwo5
FbLpw_cmtX-xux63NuOdFE0nsvVj0G
}

sprite $octicon32_pin [32x32/16z] {
jPDNaeL030DjWaiCGVS_xUxBfYQGwLz9JHmvWDboJc8vNoaCAuM6YmKDN2gq4zzWOHmLed5KYCUEbSUX6JwvCSEayY6Vj-8WZOFCmOBT2v5zeH0a0R4z1Wls
w2bpSSt5N2VIKCu7JhK8Idd7GVqcC_VMpPyYlJVpnqnp7MfnaEJGnTDLovty0m
}

sprite $octicon32_plug [28x32/16z] vT0r0e0m40LHN9VC_MzBWtyMwP0fy-BHImEuPN73c5Y7QoMQB5EhqB4rgHK6-nORU6Q4tDcp8CJUNOpSVGF8stK7qpr1_bfixDH-KWy

sprite $octicon32_plus_small [14x32/16z] OnWGmCzFJHu_7a1b-mOT

sprite $octicon32_plus [24x32/16z] Ow0Ru0U2uI_EJsCmGiAJRW

sprite $octicon32_primitive_dot [16x32/16z] pO-54S1G349xEOtlFstTe0FqlzCeC0s0Q7Qdobbgd-XUUj_uQtfkI0EYM6jYJUKNtbUibVNO3_hbF9ptVnO

sprite $octicon32_primitive_square [16x32/16z] OnXWm3_2mK27Fm

sprite $octicon32_project [30x32/16z] O-NZnmduW99u052I0IS0oXEGXP2Oz32J7PM50hhBeW7QobAI5_3dClmv5

sprite $octicon32_pulse [28x32/16z] {
pT15WWCn34JHQaRxt_-qCqcaiBGBlKs3BTHRjSgjNHx6eCp2h4G3Mnv6oSD0iHcWpSEiqJ94OKnMTmp2MAK1xF0XZ5rDzGHNE6qOEyIT0XP2Ky6i4m-gLln5
usEO_7edQS38-OzPaTQcYEKRbGgCIgnioaorKMRezSF-0G
}

sprite $octicon32_question [28x32/16z] {
fP87RiLW2CR8QkWVmFS_xTkVIlToTYmXblsNnICXmvUtPaiGkNKp1q356540CR-4Ay0NnGPgaGB6P2Qc0TpbNB2RTNQeMzYGMeEANJAk6SAmAy_SgDKk3DZC
4gQcW6kq2T8My5j048TTS9ZzaL80oprd7ibxK7O5e3-jE9Am3Zn-1AaiMn-Ux95fTri1kCdrc0N4PgQOogMZN5H3HpMezfw_QbVFkbFFrElcr6lDg3dDwAlP
Vh4JN-tIrpluzUwAsO-4F7os_t86
}

sprite $octicon32_quote [28x32/16z] {
jT053WGn20LGg3ltl-rc51hO-FnONntWoqItoVCOEmsX9kGN4ILJWOuib2AKgA3bBaGmDCyBdsyEgNA0F1X2le8bDpOmjGuvK_x005FvKBRL3WLRStjkwiTJ
G4jqf-5_qRJ5ZL-Rvgkbr5wHKdenb61x0HPBRiLTt4DQ0Go1owqc1ALFyWC
}

sprite $octicon32_radio_tower [32x32/16z] {
fP85SiD040G5nzJ__sqkKxuohO9ZSI-ljsrp-sPgTxebXiq7QLuzz2lEZD3XdB6IUqGkpPmdzEbEd1_gBSbntbohCkCBA0dbatRentmeayoWK3fDxtBl07eQ
iczqo09oHphbq7K5oZNFy5ty3BCLTrcVXwGFHdyH_DVp6VEH-_nzECyGrbi7_x2Vn_gaeTRl-zN06wnCntfOof2IEh45k1Eum5veGB1vXQhHD1FlwAyGWCFY
KK1coU8TbeQ1JnxatdbUSIFc211U1bRpZmf6yuzgHlDvlQJt4KJDRgciMlwl3m
}

sprite $octicon32_reply [28x32/16z] {
pT8r0aCn30HHqqV3tF-qOKvswqpx6bjIUBO6sOeX3648GnZ24AEkHT3LrwZetA89UjB6o0PnEAB1-lNtL9RAjV9hPd7bNFizwzG0YjZH3bIrsmh8csYGrIqb
M89gOG-oLhML7dIxiHp-g2C
}

sprite $octicon32_repo_clone [32x32/16z] {
pT550e1028LXR5Pm_zFQyMGAP-Ll-zdseg-851B3rdLdmdQ7TPUhrleFxmzv7O_1RQzZKlW_lG3tz_KXt7Pv9B_7ypj5-kgwL-EYqSHyRSjzx2lalX9prfc8
CyxtpBO
}

sprite $octicon32_repo_force_push [24x32/16z] {
pSx50GCX503HzKN_z5zj78_xdE2Xat0cESzmuAu9xl9bEUi33EVSWp_Z1i0qld1egNpWr52w3-uBDyJCl_ydZAzxA3Z0UG_pC_UypUNykpB9EPUfEtJcrZVv
5W
}

sprite $octicon32_repo_forked [20x32/16z] {
dPA54O104CHmX-s_MZmpoFjYkM1lMMYAKHgB5nVIC4YdX4ULMLPgF1oiuQW67MVOv8Rp-Qk2Y-NuxdBz0ouaYRR0n_LIiDrrb-fm7H9w8jU7H3qbwY5HJ_bK
pvQbENfFdgFqo7Da2UFiSyyP9SosQON4PGC
}

sprite $octicon32_repo_pull [32x32/16z] {
bPC54aGX5CEwtZ5o_zEkEz9v-O84bqDZG3leIMD8qnC0TK3DG-yTF7xx8U3WyN_x_E7WCJnTyAdzDBuqlxG-zVLLmVzGzZqLhm5Lpvswp_TZSh_sUjEttmFs
qblomllvwxa
}

sprite $octicon32_repo_push [24x32/16z] {
lSxL0KCX5C3Gv_ZD_jFMyRhb2mww25UIwmmd7hhWliEp_jVxj-sgJp1Tym3XYbi0s_d6gQtnYKjJxI5wgDn2pBR_YUFx7eiESDtZ_CezNtEv_guiSirb6MBD
hT_oFG
}

sprite $octicon32_repo [24x32/16z] O-NZnmBu8CAO02pCW060WdZ5WPX8SQgQFse-6O012o0a3jD9M1nNkiAH3ba8-O-30wiu1mC31nPn3YY1

sprite $octicon32_report [32x32/16z] xT8r5e1054FHu5G_-ryjaZwZ5V8wpWL6qTaIJ1JYH44Y4Pdt_zcKyFVCFwZqrfwuW8wXIF7knqcmN9pm92F3o30o3Cyd

sprite $octicon32_rocket [32x32/16z] {
XSzN3iOm20DWTnigmlrF--yH2KBz-Z5HPPLpZDFHt6Mai_epwt3qYor72l3o8sqrRy3-z2dXuma4jkQQiFZli6MEV3unh8xitYJV_Gi3Bp_BVxVUby3Qyz41
FKHgFWDhpMIvcztjjYGy_rWxpMvC6HOzzXjrvA1n1Zru659nxIzcuJNZWd71k61aV0S
}

sprite $octicon32_rss [20x32/16z] {
nOz5eiGW50HnXxh_QRyCzFW-dM3rt5mavcZPlR6RPh7FqFdO5f3VCuGEAxnJFxwucWJj0uRr1RgrmvazMS40GVrLqSow1SG6g8-Xugv3EYt18qQUdM84PGzC
8tNglYoSc9DZ8zDFpdRAH1gi3IFz91neSiVK2R23tyuBz0i
}

sprite $octicon32_ruby [32x32/16z] pSmd5i1G24L198xzhpQzJfhCHxwvXsZZihYKtuAaPu5FcxmyNrSvYW2E8e2Z2BxywtyGo0QoWMmW6yW6ie5i81l81hA1R20Ro0RmxzS3

sprite $octicon32_screen_full [28x32/16z] Ow0pOE7Z1mDaCOW87qWAKmugYIgAgeAG73yMG2ivJ1SX-CD1ZjxXIMwyuqjB-D8WlVC3

sprite $octicon32_screen_normal [28x32/16z] Ow00yFDZYj1AZXy4-D3b-FXXW8y5NOu5BCb04M05cO6mWnMxtPXkuqS3nCiX-BIIezoTc7x74sOibCK0lhZ5boRecZuf

sprite $octicon32_search [32x32/16z] {
lP9L4iCm30LbPhtxtxOJJgIPShk_NejfmyGsWD6Y8TAOWfsY3O-9Ncl7X1VFSNhqgpefKVsE9rj4C3BYv9zgA3BU5A6SltSIz5E0gEibVmhP0580ZLR655ud
68TQIL619zxlnUSdwhlNNtfYFdVcMv_Opvtz8jox3o78-nA2lCzgWXAs--QMfig48FYZm7HVOBedC7lwa1i
}

sprite $octicon32_server [24x32/16z] Oo0HiF3nOm5y465C01HcO435499eSJ30BOxBNbpkfAT_2Rj_eFqxwby

sprite $octicon32_settings [32x32/16z] OnWKW9yV6ukkyd10lZmB7pyOyB5WbmTAGnMG9OzfFav0l3nXKn6k8buUOIOo6xjF4O2mFARvcB5AA7qDflGty

sprite $octicon32_shield [28x32/16z] {
nOy53iGm30GtNBBz_zTUkPkILE6D8316aDYAj14tVEvjey_-d60dbdGc4ARR_z0497rM3XFkKIOif2U7ZG_kSqtrcF2lWtBCAm48Lg6y2YQaKWFl6HEPxw7m
VbsXkEFQOg6r7OUEaynmcextfwbPXB25FYbbXyUAC_6k8a1vLSHBRSIZndLKdSE5A5jIn0EnD-jhCm8
}

sprite $octicon32_sign_in [28x32/16z] {
pT853eH050JHlwxGzpyjRfLci1WLvm6Z4OzSLlw8ffw8hQdgVmya3GQbKMckRjsJRzAkcLBsxBzs-offcQRHTD0osDQv-1fyxGVshEtavdSmcwDxQzS__ydk
VvehZGepXPa6AW4
}

sprite $octicon32_sign_out [32x32/16z] {
rT0t6W8n50FXjpauwFwtXGhP7qEkcFRN1dkkkglESSlS3kowbgVeaZht0jqBTY_ONUl72rSPqRtHyi9rWAkjZEnk-SdB-Ed_yVduVdwwt_W_TzLUY6VxcFb-
tPp1QM7dXPqNTbwaW2u
}

sprite $octicon32_smiley [32x32/16z] {
XTC7aiCW341HKH9P8FZtF-qsp6nm6RyfYRkg_Clc3PfRbhDWVB0WgmsWbqtLIWVObeSTi2IxP807cMA76kL3hD3dcT11vK2Xxszmk8Zu1Jv3KxcW8yW0LIvL
2286KIv5C16mlmC7Z-i_0ycGzY31rty9ij7b5t_MVz8nfznVBzI6oTtxnMYWSXUVACphbnGQczmoseXluqH7V2C_BepyHdsS4n_r6VLDd2GHWzcVDwpUUtzc
VtFdGy-pltC-bW6tiC_7BEthRmwrE7ZHCEVhQJuVv_jvFzRziklzUjxFiT-rGQlBVdy3
}

sprite $octicon32_squirrel [32x32/16z] {
jSy5ZWGn34HHDuKCTV_JBWRSj3ZpXT6JOfkUqCO6Q9vlL57BLnmmuZEl7TqFfN1pmQwF7JO0UVjquFH1naSoNxZwXHOYCkmZCYpBcAP7tp1SYFZuVu9hexBt
GXakwK_cjjAMcGjgS_L4jBB9IhLOFLHV6go6ieorIlrfTGweeIRSzkfD_W9Jz0zwSnR38INVp3WMFEESE2-uo3b_un7db5nszknzFVli_JnXSxYTlfVbThef
nwx_xnK
}

sprite $octicon32_star [28x32/16z] {
nT550iCm40D0cOFM_rzR3AdEdafp2opZ4qA0QHpjC3AOOQGLw7dZSMhWpM25cO4z7teqNEGYEYnSIAKVPufvx4iAhj1Ka6X8029FHTo5oaODUFAr-UInSgzz
EXnKYOAWm56Wa9rcYgnx5hBlQNct_3CrhOmUyEFIZ9nr2ajRapQJE4Tiuio4JSaGkU0VhW
}

sprite $octicon32_stop [28x32/16z] tT8d0W0n24HH92xtF-tsycTB6YxZ9ay5i5Wy8VvFYiwgJObTYIyaHQMq10Y2xGXICvTc8pIcR9cMcLbkrfaTPNQRkOdCBMLkC7ExkPkFPGO

sprite $octicon32_sync [24x32/16z] {
lP550iGm30DLTi3M_t-xQvVfsYbgmWa-OaX5Qv4-WgnMk68JK8YWCnxGIhQknxbY5ibh1U-kZqh-vw66du36woGiDEuZ9v9oqIneuhtvOShLI8r1Erpe1XGl
V41Za3CD08j9dH7MbFJk9zBcPcVI-vW5mtsM94SVs6gMeTby9TcWCAYRbtL_JZgo_TCq-tMVzRJzvtCPyQSbg_A0TGXOWCasBTluSyTIgfOqu2D-
}

sprite $octicon32_tag [28x32/16z] {
lSi5ZaGn30HHV-Rk-vzsTyXILCDOWiH-ShnHkyZxDDUaqTxMVR9xN7chyolWugI86gWjmhOleTSq82mHfW2cPINIY59SnTdjLQpjvYhsjt2mBg7Y6hRUMoB8
RG19YQGIQn0G12o9M1An9691gBT0F-mV
}

sprite $octicon32_tasklist [32x32/16z] {
xT355K9150JHHhvBvHyjBgDzM6ArlQDFOSqernv6pp1wfgdnxiupGPFKRICMKHfOjm6dFWBhDk3a_8PJwrf_MWFObpUUfSQpr7YMce1jCqbJx6IzuFxyZ-u_
loC
}

sprite $octicon32_telescope [28x32/16z] {
bPC5aiKW40K7T_h-jzrYvnlKrnTFfwU2oKD0ZfpiXwz_Y6l-5KempVFA1g0yOz4k3woSCOqkCe1seW0GBfTJMfaY7SYRDD4aiSpqA5LkCU8U9J_lQ6n4oftq
yEJ_bFYT9FqneBcTk44I1r0F8aP_h53j-gMzvbo662NGp__8MfqER69EHcyAaIK-2mXq5Oz4Ye1_AdRSKf-9RWaWpyH2_6VFHD2JYkUVA7iYTfoo9-AlQ-CF
}

sprite $octicon32_terminal [28x32/16z] lTAr0O105C1G7AgV_QV5gO9RsWVdoS-LmKQnJH2GR0GVMjDiMW7DzdyBoXQq2MN28nDTM8l9UsTEPoRx-_u2RZoqA9AVwm

sprite $octicon32_text_size [36x32/16z] {
rPDL5iCm30JD3FS_RS1RcKg_xPGRMQEtJs7_WAqNvNDDgZVgKmcl3VzDbPvaN5xmIPNkEhdKX7gH9vMLJxBQ4FXXMekooJHgN5SLj9QhAcN8e0euvrQLSpW7
bKPfMLLIuXm2vFYSPF7wrPeLg21rimm3q926BaagfW4CFZoQgXw8d5I2XkGjpGR5CG-GxmwcBkIXAl6YtB9OLmJ5kk4UPCYWMadpZcJwadG3dX6AX0mgC_9U
mhqdj8o9YkYXtNRTGsRd0TAsnXgoZ7RJFQEttRFirpW1
}

sprite $octicon32_three_bars [24x32/16z] OnXaW8SVA-3c9n7WCcSukN_K_PG3

sprite $octicon32_thumbsdown [32x32/16z] {
VT9LeiKW30RXFr35Pl-hlNhgDFFOBpL0Mx5mgQvHHvPujbnaqQKm_rsonbyvw5u4QRjRdHec7CyChg_Cha-ihaUAwqPpNGrpFJEulZAvFh6w7Yd9SwDj-qEP
z0nEEr_i-NrPMqEbxWDpux-WFIl70Br3OOMokpfPO_PSaVhnfcwLy3-NzROXdtLrlH3xNlyWqDGFJ59YyNm0Kxz4jh2jGd-5WApNR6tNbty3
}

sprite $octicon32_thumbsup [32x32/16z] {
VT570eCm30NHB-m0RfhxdpQz9zOiURZhColEhcdc06tgbMQBiyqSJCfWaQjDjp18aX8-yKQ-_nRwHfdDl-XSdXmnCNJ9_c_0dYU7VzpfclkPXptyLbjUdCUB
jJct5bdbNZTzLMXs_zFxgfyC7gFrByE9FDD3NocX5zRGEpbqno8tKEIP7lfA2RsmXTx9ge4x9lFNKt-LG9BL-n_xb-xldwpmtfyHgN-OZptft0a
}

sprite $octicon32_tools [32x32/16z] {
ROy73iGW40DDDeMw_lzhhouwvCkefCn81hn9jW7AMJ2vI1P93Z9ZaadwBbe3RgB92vD2icEoan8ONvXgbZbnBRNzD5ZneNy-HR-SHn2vQlJtpS_sEytc31fU
d5pmf1h95t-gZhdWMkgEYSr_6Mce_d2sqQlJ5fsW6DrQw24wTWn3j7285dOoTtg2fNlD2wbjs3dIhSxpXHsABJe2qMKv8zdaSg73Ix0vAuBpFx3G4iI_L6Nj
2X-JB-rXWinWY_jSk0yE08FCK0e_s7ji608D-dizuvRBlIRW2G
}

sprite $octicon32_trashcan [24x32/16z] Oo0JiF3nWm4V2weuK1WgWQmI0H2wK8KHklZvqUq2YU4InsKEBdiXkZ0nVSL7nH60i3WVHZJ2KXP6x98C

sprite $octicon32_triangle_down [24x32/16z] vSyf0G0m34Mn3yFct-qCF0SDxDqTuoMTq1rwbDwXb-khzBdw3_sW_jmAk-i3

sprite $octicon32_triangle_left [12x32/16z] dS-f0O1054F1Bt6l_swn4mbHaxtt_kU1mM0m60m6Wy6WTitkfSnTb7aRPVv2cRzJxcDU

sprite $octicon32_triangle_right [12x32/16z] dO-b0G0m30Ghtzt-szOMmb6XfzKi7Jt7m35m31m3ny0nS0mS0yV0CN0CTYyJArDBfZUPMMHcrvhN1W

sprite $octicon32_triangle_up [24x32/16z] vSaX4G0m3C30mRBwTxiBVmSD_BoxpPXtnzmGDyWDSeFS83V83NA3t8WzZlK1

sprite $octicon32_unfold [28x32/16z] {
fT852i0m44JHUeibzpzjVSE78JveU9Mi3Cnn3B4StXzn0We1bOWaeEO179EsElkKcPsT4IqWwlsCVJ0q0qcdI4GXrCtwavRwfX8nLKEgzbJF4hrUMkUNtWaY
IP5412c2544TkG
}

sprite $octicon32_unmute [32x32/16z] {
pT95WiOm28RXZzIWalV-fnslChyi6razKK3tQiCoQ6sMsO5jQRNC1n-PCs_UI3EUUFM1LWKiywzttnP4PhvLFsQG6Qd7lyqqqKfjNMNr0aL1hvwGAbUN4sgP
L9WbiXlBpzJFp2uupkmr-UFpQ_RXyBv7__FrVpa-0o6hbD_uACUt_ms1mTFyEF4elqud0tkxFd9z1VFJ-lHgh-hx1kqJ
}

sprite $octicon32_unverified [32x32/16z] {
XPC53iKm243hahLm_zFEIBsaxyj6S09Y8296mI8JlYJ9g0tW3vX5fOmB2Il9EwCwRSODkLeqzK0kxiYWI6yulI6zBV9bbP3QGv4TwNqJYGk9G6Bg9AE_EPKs
X_JgywH7wWfGW0EwIm1oQBx4bD2aEAabkHScTQRoMNmfZWbWvcb6CkT8L2m7VDMQiNazfXiB-iGX-aVWz9xqZellJljntA_pVfxtc-x3-lu-md0Vv_igURZx
vE_x0G
}

sprite $octicon32_verified [32x32/16z] {
XPC73iKW28PnOqBb_gTzYyO7eOQ_kv-32KQJUS9HYVWZIWTS5_-qgaEvTYJUej5hLlJY1rrxX60_uCQP3yh2wubNuSqJnE-z2nyU0w0ylYAF9PHajhSO-cr0
NaVCAoddFVxkCBN56ekcijXYloW-uQbMHNJnc41gWCC4a9OUOF5A__YWnrnrVD5XaYcudR2O1rXtq6BkKNs4zHNNPrpVqXzjwFv0rHznVwbzN7z6_Vq6
}

sprite $octicon32_versions [28x32/16z] OnY2W8MF7mdmiI3BGQGGaX1HLg0m0mC_6a3em9I3w82eWQc5iO5IEEGWlE4dHzZl-CACK5ZZYoDySOitJGmH

sprite $octicon32_watch [24x32/16z] {
hPA7Ri0W30KVLWZAylt_rtQ2x2ojzZHp0JprGtKwNfLm67Zs9FxW2ucYmUImLfEihk1JrpEifewjCF-UXgP4WqbIyQ7ZXnTfOHqvgREog81TlK5futZoMcaR
zUuhcsDtRpZexWNPnnSuTlU6Hzn4POiy4oijwWeCIlGXM5dU-lRQv_UvtEVuClT_tgltlOqzZsm-0G
}

sprite $octicon32_x [24x32/16z] nP6r0S0m4CJ2AM__QSEWW6f_zTAPNHMizX_7Z9S3ZiaL0Dk4mRXXktO82EofGT0Cg1b08u1c02tUrl5z_Pn-Bv0-3y7V6Hee_oZ_Ngnc

sprite $octicon32_zap [20x32/16z] fSYt0SCm44Mnpvnv-s_hnegl54heBM9K4skphBBCiJhB0ckoBB4soohB7AkpBB0EzKCT0akTvLYgB6rMOcco0akTvLYgB6rMOYbYVW
