' Octicons{height=24px} (https://github.com/primer/octicons) MIT License

sprite $octicon24_alert [24x24/16z] {
XT254GCX00NH4zos_shZE4ns_9toZ_yfjMGDUi4dm3cx0t0JttowHmzV3mChVgdUK_Pqjcm0_VbLJCCNrRcg-zPzOK7hYEonzrY7wHnTXsdACrc-UQqztrmT
fhxdDrDOUJWaEM-C9wSIozBEBsqMwUlOz0G
}

sprite $octicon24_archive [21x24/16z] rSkr0S1034DHXO_il_-sQSBSvdMs95sfXd0qL8Kp9-WeyFtfd9Kw4_R8jGBQ8-ZX6MRR9xFB-S-UBKUjf3xizRes0W

sprite $octicon24_arrow_down [15x24/16z] fSor0G0W30J0nntsdnQtFjV40o9f1udDbi5IIzr_nbd6dcbHVWBggzIv_9xvNNai-nKsbdkL6GundpwgF_q9q3K

sprite $octicon24_arrow_left [15x24/16z] Ow02O4BXiV0ZyzZuaRcS_4XSHcv-92uJBpy200r11cpy65mKnNp8N3IZe1QXEmEF8nc01g9xa68

sprite $octicon24_arrow_right [15x24/16z] Ow0OCA5o-LXGkFpyRAXSVavKBZyt8uY10BnCA5n-e87yA80DZOkf664KgaMudS66nmjC35G

sprite $octicon24_arrow_small_down [9x24/16z] fSQr0S1034Mn7pwot_xJXgctAYaifNG5-6TE2KXf7hcCIXoIf0fKxJh7Enr6Hbq6nMq

sprite $octicon24_arrow_small_left [9x24/16z] Ow02O8BIRFmGceiVp63YvUVdv-3WOEE70ZW3BWLH3DUEC91Y

sprite $octicon24_arrow_small_right [9x24/16z] Ow0OCC4O_6mm1ZyNaEJWuE3dv-Tb0d8XW0tEW4b157EYQGSAKmu

sprite $octicon24_arrow_small_up [9x24/16z] fKwr0S1028m7P_zjtwN77Uw8qztzuq_rfxcT9M1tv-p12q4UQFHy0Da1VBcPWspt003Ye18

sprite $octicon24_arrow_up [15x24/16z] fSor0G0W40D0t27xJujhpLMl8V_uqqd8UmVWx6a2aEXg0vemEuV1zSvWCJtqa3tquCeOCwECCUfy6zBzjS8qWdmg

sprite $octicon24_beaker [24x24/16z] {
ZP053W0X40FFSVh_trvmbuarWtQF0EZHXJx7BXGvoJyKabfCE390KwWzHTy_jEF7zu3sF36z6azm-iHqxZKFjrtuadvnnn59bNoUNpmXtYWGmNEKN4vVg62z
AHlSfz50NQS6RRnklUbseOEfBrfjglq
}

sprite $octicon24_bell [21x24/16z] {
VS-54GCX54LH9BE6tFwhZU5wnhyz45lgb6FHu_kID81HJUqWEDlQK7rH72MZ8aFjf7Q7egFcmsjewHBJHPqm7drecJ47VCWPaovwZpWOdSoSCsBZB9yff0Uy
52rjiLf47m
}

sprite $octicon24_bold [15x24/16z] {
bS-r0S0W54LHtE7jFss2MyUj_eaWv2c3MWg6BTPKOzJQk69HwKaf0dQZpiDY6SmYJm2hJDQwi5RkETePOqpNHjHcqywI1_HYcUp-zg048CSLRCmAnmK3tQxl
E7di1m
}

sprite $octicon24_book [24x24/16z] rT230GD100J0JLxdxR_QjstCsS1P_eub3PyLWOYYP4nJ9GHHeK19pFRx8kDd_I9Nzelog2pclhBFddwVOnmGDfzBKOh-QD4-JfS

sprite $octicon24_bookmark [15x24/16z] lP250S0W30G_nNt_QN5Te5U1kBXqiwMN-8hV6mD_Yn9oNGDXG66auLtYEnrlKjfGSzsIXupovDQs_gnE_nFrFRyXaDaJCZJOc4zXeUfQ20To1G

sprite $octicon24_briefcase [21x24/16z] lSe52iLG44FHV6aROE3kVxLrcpwqTj28Rl4D8BvA6cpJA36Iy7efcJ2P0omo-ORoo12UIF8aM4dYTGqbwveE

sprite $octicon24_broadcast [24x24/16z] {
PP05iaGX30GRJHR9tF-qNoYgrlefdK7XqCQMOba6dlJGyjvjIEDPOJvRBLJXa5PKdWorcuuJhkOz0JnK0BegKBOYfCS9Re0OW6aKI5qxGLQ7fWn5nY7j2Op5
UTY3Ir63giHsA2hWKcIO4r137Im0BPU12_xbqpjow0B228Tw_gMJMPpy7904VKXX6NV8AfW0f-iGM0BJtGIudc_2WH7f6A_u4e0f0rdZU3cIW287eEd1SvsK
c70Bw-dhQN0e--dDuCdJl_Cydo_kUNBv1G
}

sprite $octicon24_browser [21x24/16z] Ow0CiFDZ0dP-7WuuWW8UVduE1ZY20Wv-h02XYmD5EphW67w2sFsEBP0vA8mu

sprite $octicon24_bug [24x24/16z] {
hP1L0iCW50GfkkZU_xODHBR-rOaoo1Fp0m-awm_o8DdcJ-26_3BjUBrGs43QLnsv6AyUrDi8MucDnlZi1myq4MimPXeSRuksV2UBVEjalPc9HPTd2KR8GytP
a6yuMhIS_EBpEIB8Ltl9-dnEXviwiyFAOowR-Ljtd1zNDz9CKUrS0UtWiEQ_t04
}

sprite $octicon24_calendar [21x24/16z] nOjL0e0W40MNRhZ_RNrhItmx2WmnjCRhNa3pNv4LmZyunP5Zznh-2FdM0W81luGFHt3eEp8VKeVdmqFw7sZ__7wUBt_jVyZ1c8DLhjj09RA-mqcQiG4

sprite $octicon24_check [18x24/16z] lSY53S0W4010t6N_RHiSFbBdueTsaGI4Ye60YD712EHI40aZHBK4SZ6c6e58IDLYr8XHAQO2aIh5MYc-TW

sprite $octicon24_checklist [24x24/16z] {
hSm53iD044FHKNZHzxzjbsrLMFZXfyZshxOCzj1lF15FBuB-e9ny5vVK_xqJwRlkFCiF1Dr1oEXSNljEwp0BWt7qdS56BiY_3_Bqit21mVJDTemExW6Xl0cN
hgUbs-yTojfns9Uz
}

sprite $octicon24_chevron_down [15x24/16z] lSV50O100CJ0uCxsN-sv5W1vPVYmeRlz6RAUdLroZf9sHzs1jnpnlfok889FpgZaDocvAZYekXFC_9m5

sprite $octicon24_chevron_left [12x24/16z] Oo0JC2EOtFmi22O_FpE2oOLWSYAO70WcEuB9ne3EHgZ1q8im4s4NkXiGRaEucNG

sprite $octicon24_chevron_right [12x24/16z] Oo0TC2EOBFpSS55-VWI72vd3YSpXGEQm8tFO41m46w46eHTX9i8kL3SWt8PmCva

sprite $octicon24_chevron_up [15x24/16z] lSk50S0W30J0Ud7stvRyumFWv2B7vlLCKb5DYiL5yA00Dvd3m4LMVWjJZbqE5lgJF3tBK366YnWjN0a

sprite $octicon24_circle_slash [21x24/16z] {
VT654GGW34JH3OFRxx_QSylPZi73YVubvfAZaz2vfeU7DM3KKWVGRZQXN5lMOEgSpdekwj0bPRQvZSZI9hvQIsmbXZDfaZh9cn9zOTvaB71s3e2pAoxCstbv
9tbJeYUcDmsIDibPP4iPNiqs-V47juHrwqoeThK2y-idVo_7zy9zpn4
}

sprite $octicon24_circuit_board [21x24/16z] {
dOw53GD140Fzn-p-gttOa0EYZCXQ7FnYowK489GNULia2r0eB6fHoK2sC5AQzrh5INs4HWFRMWuNxWoRrIQoNJYnCAswkUz9jiVDBZSvK-htxtdmFrHUKNcZ
gDAZ9l9I-veiLdZ8QqtafIPgFshBHPoa8cI7Nnm
}

sprite $octicon24_clippy [21x24/16z] {
VOu73WCX30JtEft__pR6ifQIv8O-mWKlRC-phUwemh78b8yZfo7E2TK1iWcQfTH6se4zwRM8bCE1FF8qEK0vOj9Xmfcqo7EI5kOcIVPx2h_L5GUSZk597QDu
4KSOdWR7yEMdCUTqobfTMVeSCPdSH6hIrHcD_
}

sprite $octicon24_clock [21x24/16z] {
VP654GH120HdtRVpp_QTz-io2eVH4J6N7DyyldEZU_CrODHI1z3klWdbRXQOkj1PLYI_w98os-aCe3DkawLDb3dFHBOIGszE3L8dVJWJVU4-d8u5-d2AT_DC
bS3ApNakjq7ruKnqMyaO95l-Z2rlPvwnCtyzvFww-lcwpoV_bkEtSByv0G
}

sprite $octicon24_cloud_download [24x24/16z] {
XOy54i0W0CDmX_p_jNFNdFNIRe3umtZlzDrMHfevwmWrXbGX7BMZsIbOiBkMOFR5SPwt3Aq4EQrDnc--CMAdNpBw7HL1QyZUNoxkoVi_J0ZcS0fIp0G8FrvH
C_xcLSNFvmxCVamPylYecTdFESplyc5WzaDmHee3ix-Y6XDDtOfTtufPtufPtukxljC3
}

sprite $octicon24_cloud_upload [24x24/16z] {
hOv7ZiCm34NLAwLt_ziE22g9xQtdhOZVGFVF584zoqCDWY7XAllDojw5lDZ-eWlZNDCk8xA_JIZfKwdqRmQbgzC4gagjwL-r3X3T1ehAqCxOeZLMr5lbhn5O
Yv_yC_IqH6i2qbeu-id_zfNAR4XywB53S0l3T8ny_h_gMvftFqm_lD1VyWS
}

sprite $octicon24_code [21x24/16z] jT3L0O0W04LHk_NkFwr5m_kbuT0qrK8Vwc3iVxqJjBjW_ushizQUmF0s1k1i3Hx6h1vc8sDMpKQRjQ1RitWBkaXKozL1wahoykgPwaFarrKB3m

sprite $octicon24_comment_discussion [24x24/16z] {
jO-5WSD00CCSTj3xJ_lVLcL69KSwj1vG6w0h16rEMGIE09nNVHSuzvcyPhhmflDZVyWxhcMMuDNoAWyP7NTbV1RJPBdmCdwoQzK-f6EsI-8w0JPJArEMKfS4
VG7w4lGbw2Vv1m
}

sprite $octicon24_comment [24x24/16z] xT0b0e000C30uSx-_rhS9L6vk3XUfVbDF6OVf93BZVdQ_nuxoWbRT-dosNp8-IPbOTaQSwUFcPVCIoRcgnu

sprite $octicon24_credit_card [24x24/16z] Ow0IuE372ZZuUJYm01wW31vJA0Uup2T77CrWk3YQduWq1rCSefr8z_1WzoqV4pksS6PdOg0n

sprite $octicon24_dash [12x24/16z] OnWWm844-740P3K3vKu

sprite $octicon24_dashboard [24x24/16z] {
XP05bbmn4CJApDRzRvluTx8xF7fKJuO6VINaKf9_aBvZp7Yhsp6jrB5XIChzM3UXEbsauQLEE7co_EsVQr-wiUmozNh1zjSnUCMZQhozrS-rYcIbc7-rTn8u
_ITkvZdTHO4f8zTcNLukqsGQe5jcgr0aAm78CYXJhPDoUSjifVzl_OOgYomvjXwmcfFue4rbveEEziMYwXQtIJO5-LPFXgK4pJsimZBGujbNdZ1ktdR-ivDk
yMKizcfHnXy
}

sprite $octicon24_database [18x24/16z] jP035WGn44JJxcNT_xHhZ3t_8KwXTAFc4MxwNb5UyEEIL0AufZ4zZjZo2WG0AZy83nftfX6j3MggqzKV4l9sA8-fNm4SGzzQ6iSzjR2LLhlL1nMjRku

sprite $octicon24_desktop_download [24x24/16z] {
jT254KCX44NH_GOt-lgl5YVkSiOOODKEaB0Bhzzx5VHxL7XjoUP-FvDjJsBvunaTS79_yi15B8Vhm_t90s_qOF3A3hVSiDKzTrxsewVQATbH-T6QISLav-Pz
Yv_FhpcOxQ48
}

sprite $octicon24_device_camera_video [24x24/16z] pT2r0GH1049HndtelzgJTOrMN_Wpm4aSfrmRHQoSmv_-rtKFN0DKuGOuRifybtRg6aJSxe3PwH1vDR0EvqldHqwY9IqkzWK

sprite $octicon24_device_camera [24x24/16z] {
hSy53a9140FGhZkz_scHxyqIGLvyVF0lziP5jn8sZPkMJyairRDN60jEyc9TaklWf1aynIaCrpWI79MnVAae4kveN3Ylwy5LCXAl65m4A_61jBva0aL4VOKz
1fM3Iy4iMLMyiM7m6ublPVp90m
}

sprite $octicon24_device_desktop [24x24/16z] vT2r0S0W50JGmvtRVzguMvMEro5VyHF7HuxPFyYanmFVtFtRVjwyl5Jf_AnmKFpCIImK9mfdkYxn-dpjDngVUW

sprite $octicon24_device_mobile [15x24/16z] u-171kpy-0470m9m34CkLi3Ao8h4um8gvCBWOYfcHmqu

sprite $octicon24_diff_added [21x24/16z] Oy066Davq04x8ny_9k3Zvy3GpC5FXY3GB6eAie2S31G4KImGGH2901ou136rqygT50OT3xReOC8ISKnOenW

sprite $octicon24_diff_ignored [21x24/16z] dT6r0OG000J1zyUl_sx96Dmsd7GVqlDVpFi_kophKZpc5Rc9dwGOa0MoVE3O88CCCiWWWso2HHXaK9UnMTlnMXdtUaWz

sprite $octicon24_diff_modified [21x24/16z] hP550W0n20FhNlZ_QzTzqnjpn4aKGiVq9MhYFyJfrvnOAkYY-mRTUWMvLz3mZda6on4ipo2TPyCWRiUBy4dZu-LLQiWE0ump2Z43

sprite $octicon24_diff_removed [21x24/16z] Oy066Davq04x8ny_9k3Zvy3GpC4_y88iI2vdWGY2I0JWm2U8gNqGUfC7MtGmOOau9gnH3

sprite $octicon24_diff_renamed [21x24/16z] fP550e1030FNVPl_lnPtSe8vrfieXexfITI2DuBqQaxu4CmiYAP9469940YNe4iJcCbdCE6WQHgaxNmHFuaVpz_yALrZTXXYd56C4G

sprite $octicon24_diff [20x24/16z] {
dT7L0OH000DHd3bD_zMUXc3xjOC_79fFo0rD6lZtD6xhZ2ZT5jGTTmsAd8enjaNRG53Oa1TpSxGFs0Qu2zXOdZ6sERV2KeMLdYNV-MyCftCzEzcTRPhpFzAp
-zWR
}

sprite $octicon24_ellipsis [18x24/16z] OnXGmCJEWGBOcNZuqG0VFpO0LClFmy710sQ00T0qVWu61Wum0rC4KnSsW6axfWi7DiG

sprite $octicon24_eye [24x24/16z] {
hL7L0O0W5BIbsNzQkk7-E0LUvx4PDnLA2_RqqaVe1DbgY6v0YvW7zlR1FCKRiKhkZtAC26ImUKgc7EhDX4j2ijbxN27N7SH1SGV1nSFZx7H7S2H7SK1UK2Vk
2yy1pwsVCzZBPbW
}

sprite $octicon24_file_binary [18x24/16z] {
bSu50eGm44FHh19qxd_QIWPtFlw0jjZqAZXMI3gRLMSnOemYoOmaAqfYAPsTydt3T6QJ1PNUQWSbt9NfBtu7iUdiCi-5J9hFyx-0vL-K48zaExjcyVF-UXfR
rRqBBYhUs1G1
}

sprite $octicon24_file_code [18x24/16z] {
fSrL0e0W54JHHpUp_zNQZWgVNlj8o9GAaOL3EbwLNH25nOCe90g9GXf4CaQ9bsGbel9B2go8Gw4K1Evz25TFAATOTBs3wh2dNAJQ1gViPCyRHGnlXx0_KZ7K
TOYVWfQf5G
}

sprite $octicon24_file_directory [21x24/16z] Ow0CiFD30HypGf2VXmC2-DcH13aG38GW5i21nXy5xDX2YSA80m

sprite $octicon24_file_media [18x24/16z] {
VT254O0m04DHdA3PVrhgalQEZp-yGzUu8xTxULbrEI6673nv4V8Yv4Ke2-3tJcOXwK_y2G0LNv5bQUMzHVnw4Pb8tlxPIIxQbd8z5hfkq0OlCaAm8f0FfRk5
TzeXxTFGPG
}

sprite $octicon24_file_pdf [18x24/16z] {
PSg5aK0n30DHXTdglze3Evzt-CtYaolrhAXCtXh_mggdC02LuvH45XXjoIf6foHiCWbaXDPf0jARr2sUp4zfdEifR97rBfa1W-KcQm6kSwqrnh_eakhWhiBB
6fHUKbacZPJYeVcqpuYpgj3naecN3FUKoLVJb_geU7pw1G
}

sprite $octicon24_file_submodule [21x24/16z] lSy30W0X50JGQPdd_gTTs-nbz_5EpewFnqbQsM8-cPHZPvpS87cB5-W9rqzAo1wIkcudsHjVb_r_94Uo3y7E9tk19_EDIObtIW

sprite $octicon24_file_symlink_directory [21x24/16z] fS-35G1130JGEIwJwR_Qiut_i8pmZ-50CqmOROzcSMaNcn4FM7xWmb4ccADBvCebAH8qah3CXr7aA8vNovyPYg1cdLCHzjMzF-ZJymbpEDi_DG

sprite $octicon24_file_symlink_file [18x24/16z] {
fSm53WH124HHfjth_gST8MnhV7_y8NHq-T3pB0rJ-HC4wWMcBfswTEhIgKjLz9NG1N2yz9DB0qX3L0PNbOXkaA98_SOVEBcoI9g8RqGIF-U_8f6-70qn97Nf
_IC5MqtviEGL7Jq
}

sprite $octicon24_file_zip [18x24/16z] {
bOi55eGm5CHm1ftxdnQhVLbDFQ-f7FM8pFYObOBbDaJPmQNSgw9kyzpZiSWggbWXgPcgUYwgYaPN-AFYqcapaPobQNb_wuGP2O2ZCE0DYb7yPbOQrcQ4Ocmg
nma
}

sprite $octicon24_file [18x24/16z] nSi53e0m40NHZzTx_zFYr6MZlFWaWyomCMUxYx41YPDbSDYTN7795PVEOcykdONTy13sB15MBioPts8Tzkz5BSecpBYno3OYSm

sprite $octicon24_flame [18x24/16z] {
NT250KCn20JGYtjk_srReChx6WTW0hnu8fnxVTVXyNF8Yb-9v7IBo0t41XCsTKwy2-BvGv7GEI0oXJGMAHs5wa9xcimmsq9WaBVfPUcdqZdQNo-_v7_1TJ1X
yMD9-58UdaFL9dbWieMLvFKog15sCaBexxAH0RFVVtbN-yw4jnZmzG
}

sprite $octicon24_fold [21x24/16z] {
fT053iGm30NHg0fCqVU_xTfrIB0yml_A3IqH2LF_OmP5o3CkbrZNuhFOs5NTTfkSSW1HrIm2Xvmwej_Xy6kZ7UmQXWLJHcRMAdFhRUZ3HximM-mw3A7h8LPK
4zLOFwm0jxa2nPzlvlhsr_sFG7ZP0m
}

sprite $octicon24_gear [21x24/16z] {
VP255SH020LPz_tzTti1BYuJH-U5Feaft686mBqGGE0aANqcyWF0y2QZIwpYJE6WnncdxM1QRleaeV2huILDkbUPGGglMz91cbRl80CYXDNEOEKUZFVswfVi
l2rwKQ9sakyISpZZjVkCzdTa8x-kEqgphtP_cK1NLfaJ8KNwv0S
}

sprite $octicon24_gift [21x24/16z] {
nSv5WW8n443H7_VK_Kyx0xJR1dsRI2dNVB00oWV3fBNIgy9BB-8O-0RKQkyVhZC85L1T0c25WHO3X0vGCaF6NYH87DJbGXG6o-Ngyxpy292uAPV0xp_hPldX
Cyf6qxpe7m
}

sprite $octicon24_gist_secret [21x24/16z] {
hSw5ZGKn34NH6tOoyFhlTYqD2lRp2QFDJtGB1Ejm9sbuuwveKxWPsWnkccqQZ-LPXpcpoNQNULSiqBRO9O8hOvN1sB8qhQFGv0947o84kTQt6oGV4zkBNhIj
p0VRpbI2t0Ap3pCiSe5LpeBaWicjK2KNRttbIty
}

sprite $octicon24_gist [18x24/16z] fOu74iGW30D5x-Z_lxtHfITJawKlO1iFJCeNafcyCPbn8VEBSUkq6yy25FhTU4uBs2abiufL_KtJ7r7OrbzDapwqzPTK0fB4dhrvmBTdXPzCpnSwCszalE87

sprite $octicon24_git_branch [15x24/16z] {
PT254O0m00F007NB_jjoTSiPJ-euycZzJ7qCWTzWC809WxdvE6RvtdwCaT-RsjnW0HjWI3rd5Our_M3UCRs3-KDXqfFVf28JAb-fFVFlp1w7bGg3JWkKl2d6
NBJuVDJhWjVrhyUvdkxA3m
}

sprite $octicon24_git_commit [21x24/16z] pO_L0O1G30DnXzj_Mlnv1kZzr2ML1PfvPv-R93VmCKIv3ZYs0-X2SlzwHjZVUBgPONw3ntaIV7H-pODCod5tQFmFoPVKyrAc1Iu

sprite $octicon24_git_compare [21x24/16z] {
nP473aGX24JNtkN-jrt8I68vm9yqV8nA-MsoKIEJabbiviKSzKuEZ1Hs3d87OyqYryY9Mx84JViuMUDvqt7AiuqeRx_pCIdKEd5K27q4eprWGchQ7NgYuJW6
rQx7DfurdsqyVP-aAVDnYfut0S7sFMgTgZy
}

sprite $octicon24_git_merge [18x24/16z] {
VT073WGX30D0wbOl_lzlJp4gGCHPVGHfmIUUPveW4s0P1LS8rpSAixqRvRKt62KrmDuDkKWM9yq9NoTyawQjPvHyPazDlOl9TR17aqX2WaJJIco_2sryCqux
Ik_LVRFfzXhG6tVLl5u-Xl_v0G
}

sprite $octicon24_git_pull_request [18x24/16z] {
pP273GGX30Glai7zT_lB3rQYWLkbqGYS3iyLdCuOpob6MkAsrkoMC3TDa9g4Cl9yRVV_dP5nhJTLRqYdphYeSyi_Uc1YUasE6EPnTgDymN0D1CmrC33NmC3x
cxqEboVmdXy
}

sprite $octicon24_globe [21x24/16z] {
VT175WGX20JGCYkYTV_RJlE4xVnDjuc4VshlhS24tAxgg4ab8moxqjPI8ISUPRSJIPEV3IDayoWq0g2Jn3DfxCebrKFpEMZy98_jgl0pW2wTOHsQbiYhTFvp
SYqycy-bqpv9EJJtCCXEG56IH_X4BtagfJ54NuqDbs41HkzhqutNLty32HcetDvUI2XKF8iHT70XPA7fQnUOKFleEU6F7m
}

sprite $octicon24_grabber [12x24/16z] Ow0Iu4S274W0btfaDSXwARAB1W

sprite $octicon24_graph [24x24/16z] u-TWm0geByx2mS62JPo37yYciJY494SSnXxyuh0GHf1uumK7uC0167

sprite $octicon24_heart [18x24/16z] hSo53GHH24NHE_8Lmkk_sdKbkd8YE7ofkg81j91NOEhCm6v9rTKOkggknAKib8GfiQAa4Ea8Ibw1hXUTiwc7oTNGpO2RfelAKxazVR55RBnRL_xi2

sprite $octicon24_history [21x24/16z] {
VP455eKm3C3QOPtc_hVzh_1n2Huc5VcY7wUnFvcGM4X17FCBo76o34INc6IOL6OcA2wfrB0lL4akGML76-CixHG6JU1gCuEii60oa2QxIgN2LGgmo_sjeXUf
rCHmaGDf85-aXzJeLxa5BoDDLxccAPAeOP5hGPmoHsTcM-cS26JRYtnlntVZhlm
}

sprite $octicon24_home [24x24/16z] {
XT054eLG34FHuYcM_QyMRoVlQqOv5xV_g-lFlAxrHoQF018ltBP721SsEy8OBdm6fYT7GCaPK7A6jVx04KxkhLX_X9FV_GWzG2_T2PodphEW73ljNFw1kBvd
hLx7ynfswXqRkqUeW_cWINsQmtrLNrt-bKm-iuSi-FDs
}

sprite $octicon24_horizontal_rule [15x24/16z] Ow00SB0mCB1mW1X0mCB0pm5ayGEv_4300UT26VYv483GoyF1mGFcye3CngyNxWm8Wu2RKG4_Ne2cc9Am0W

sprite $octicon24_hubot [21x24/16z] {
hOq5aWGn30CrxAISzFzVU-1XAjhje4dID-ZCAzMjEwISagPnIWLVqnFUQwPtflWOfXsBR1-vOxQNgkkCLmrq4qUiOyX5U0AInUsev995qiYeDkw4Si74ceaR
6PZMsRZNvCLeJbxOaxtzqv-J1gp_jt6tAyx47TDd_08
}

sprite $octicon24_inbox [21x24/16z] {
jSr55WH120FGb6CDzp_jkF9gst-99DZhzAy3Q94rO3h--GJOqj0OK4b3KS0f3Sc166au0YrQ6jucCqeQbXZao9pKa9aUWaoECAA6hqPayL1-MZu8RnHVJ4yS
fx7DpEkYR5NiN04
}

sprite $octicon24_info [21x24/16z] {
VP15OWGW302318BE_rzRWMozEvUuoXE25YiQlhhIu3BIXwy1mweDeBblGdMrmZpAO4Lv41T3H0hxz3ViJDmKaKq-ES0ToXOzwPxfxRIZyXsbBy9LhVgum08F
m_9K05U_QbxkJY_lb1_EGbVc3-T4lovlIKGo-_FCifdXSQPqzfU7RBhVXOKxs61us83Ph4t0Feiwb-wDdAHLappZ5G
}

sprite $octicon24_issue_closed [24x24/16z] {
XP5LWWGX5CGAsmUp5Bd_RSTTEd-TDAujSeje-TM6EU5ujCNWqVjkWSjDDvYNhpAXNdI1hXiTIw43Fkj-oNzPWtyfcBhxKu4ccNBtaQKA8MMicmzMlYpN67UV
5sknqu6WtxqEWQbtVmYMSdkOf_PUTN3fqDfztGTCrii-ZpGiVJZN9FJX7WR-V6-KztkkXlRwBZ4CBXll-FBk6-m1
}

sprite $octicon24_issue_opened [21x24/16z] {
VP65TGCn44H7pFhzLnkEZ_PvXCkaTuYvv7ZX-Culkd_n6Z1ggGDeVxm9vUzROEeRdNKO-KMNbDbEae3lnssoj8awCHNPIWnTc1gaJhen4ttXRap70jsO0fFv
Cg-rlinVWLv8T3CbAtcpJBCXVwshzzRTcsoFmnwSZKy
}

sprite $octicon24_issue_reopened [21x24/16z] {
VP455iGW30LJJT2v_sttXQnNfi9_WuFSiUwwhpzcpWHv5iVy0qfIAq1oYKa1dMIWK5tIQFDde4Ps2QCPuCNKsOUqBoahNNZPbvJ25k5RRcIrVpdHu5yAdCh6
5D7C933DR79WetntDnpfh5yohEpqdsqoGluxa5Xb1GirAHGnF2UWcAP2LDl_TLnSt1KF
}

sprite $octicon24_italic [9x24/16z] hOgr0S0W44LnXxV_j95B4wyu_QOkfQCzm02tVmi4KGf5lLT8IGi0v5je0W9a0Hc2W0PsKlQ_LW

sprite $octicon24_jersey [21x24/16z] {
jSvL0eD054FHuEFP_swRmlXdvU3tOH13MG4u2kIEnZDPxNJI8axU4guI7R7ovZLTSGi9y7VSSMYxnQ2TYGowNddURQ53GtiVBWqRbnRj3oPqDleLXccxFxFd
lIKLLu31qEGzt3j2qRGLvf-nVRt5_Zzpd7mVBvf989R8sVK2
}

sprite $octicon24_kebab_horizontal [20x24/16z] tOU55KCn483uSR_zfurdY9OJ7lmWkafSZbBrooeY5knKXPCoyU2NWPrnFWLgAW8dhLTCbBTBE_-50G

sprite $octicon24_kebab_vertical [5x24/16z] Om03LdOc1av-VducVY1WvmKIhCoy_9mCQ00i1fO5gmFh0Ei50vAC0W

sprite $octicon24_key [21x24/16z] {
hSy54WCn04BHzJZS_xJrGbttZsLUl7lRk2pZ3KtWBaoNjl3KOXku2sCtWeCmSLVS3IAJi1ghaDvE8QYqCj8bcnjaRhatJ3SMzNTRE87D8AlnthWtTxlNlyCD
3jZPqAtQ5W
}

sprite $octicon24_keyboard [24x24/16z] jOy50iH020Evgqqr_tzjtLrdNO34NWAjWX9MI2Gsic2IZ7aN1fWxxUpbcNTrUTn9x-zdIBgK1p2EVJNqnzvNms6UHAja_u0LWhzzJ04

sprite $octicon24_law [21x24/16z] {
ZT070eCm30F0JAQ8_l_RHiRfNcf1-DY4hybpVh5AiZxZtd5_nhNZ-ennvnuVQU6PnUUoz71VH3ir53-efK0of3OEBqHV2rLWiMfgny86gm9S4UYpIkwehG60
8p1EjHPQQm_Fp8QpJyjPqJ2w1IcoNpF3R4JurqSkLCgTn8CZHnoObrjo-9GB
}

sprite $octicon24_light_bulb [18x24/16z] {
VSz7WiGm24JHhp0sCchg_gVjuCXgtfPOx1OFnRJAgOTUmyobSJOe_lWfcoP0q-JIvS2CmitKgLf8OcDH8Hd1AZ8JNOt49qL6eW4UFDRVHDFABNmVVQwDOsdL
ng5UmUmwvr78qtcZ7Pl6lV3A5Xit7OoR7Jh_cDgbdguV9sckbx7x
}

sprite $octicon24_link_external [18x24/16z] dSYr0K915031nHTz_LSBV3dFRi9XYh40ZEIbIbsIE0plVfwHfeftcXHFJ9C2J7FQ0zo7ynwGXXFT9ECOa_FIsYkCZapv0G

sprite $octicon24_link [24x24/16z] {
lS-5bGGX44NHH-Fwyyzs3wsLmCx5dU87N2odwB2YNf5FK7ESN5FWjGQliSnsiySCijv9SCf8FPol7foIu52YbA6qkvdDg-_3vwQscoP_zjUzjgq6RggMS7RB
T9pQ1AXJ1HNmt8fuZC7B3fA22IEPFGhlj3thkXxTOVbSjkpvVty
}

sprite $octicon24_list_ordered [18x24/16z] {
XT3L0KCX30NGO17ixZzjtGXjt_b3ehGhIYi3o97hpS3BkD_Wm_x79ZhJ9rRLJFyn8AwuD5nZNvZ8fgjUmEjDGI-1YhmKmAVUHJFNeFQ1w3yXhDkeQ6lrG1cy
_Ebp8j6dm1Bfm1a
}

sprite $octicon24_list_unordered [18x24/16z] Oo0ByFBpWaau03618ln805CD0vK0AmShc8G3LapRCKKmTM6QFFX30m

sprite $octicon24_location [18x24/16z] {
JP3L0GD124JdP0sR_hlDGMpV3wv8cZZfql3XSeRCAK6_a7H6Hz6SFGNrm1Tb0yAmOO71ghrLx-h9OVRkzL3Tp6Ab33v4QZCuKx8e3rrIAXyqDN7nb8UHTbIz
T5v8hezW1mKRGc3nn8-J2pWeUqesczNfqsMcECBnmUCeUMTnidXZrohonJBxtFzok0Fk1_OzLFUzgaVrskaT7ru
}

sprite $octicon24_lock [18x24/16z] nSk54OHG54FHXrlOz5yj_br7z-A7YJoD836Ahjduj3LARW1k-c0azrQalUmRWhpW8XBoHExwroTglrNBJAyRPZlmIdHgSzrzwMTF_hW2lNxjD3jDhGIT

sprite $octicon24_logo_gist [38x24/16z] {
nT474iGW20LGiA2YyEz_sns7xNrgVdfyTZeYUHXWiwTlg07QkYxO_gZlKSMAHhWI5U2f7ucdEzCjsXwLhMWAWvxpgXJv3xNm-7UtdDG1L-A-03EhPFQWe4GC
Qo9zCOkuYKWYH9Eoaq9ry5EF5uMT6agDdjIbHsQk5zKWdqTVBeeKyDduOINIYoAkVSBvfWJzMKKIHgY77NfMyNfHWidlLCRkP3f5Edo8j65RcIKIRI8ZnYNG
MgAH2G0sPR-xKba0V4GFud0w82S
}

sprite $octicon24_logo_github [68x24/16z] {
tPC7SaCX34HNTFu7SV_RHkm4zpubvIKsWzRpwFXVIDxx6Dgou08NOyGan1XmHah9WJ0VYmpaqK-YQaLsTOo6KxmbvRIty73slGCIGf0t77qOhPQwAnWrS6hn
TGTN4h7OnWXlEmhtuOW0hpl4CstMaQD1LOkKMLJj5uvYeG396iT5MtLqprIdbq2iMcTEw5WqR1oECpV7Ge6fWZN4l-beWqjYUkw0ozPaxvuuAk0OwCKy6CMJ
FItPkEd8u7OghmScvS9nUIwt7Rkr31AC_Ab3-NELbntkUYrjnaQ9QJzn13QNZi8foxOScwpt5SVYw73iwOKZiSY83dOuOKRVE3gupCdHmNCH7UJoZarSPQZL
0Qtt3ACopRqtmNJsRchVPhKaAxhMSkfp9So9E5mW32znvrN1R-8B
}

sprite $octicon24_mail_read [21x24/16z] {
PP272aGX30H3a7ThdV__syE8vChGT22x97OfizWl5QZVoYURwNOHd-X8XfB1QK2MY78QP41coNh4I4h9Tj_ZMNWVNrA7ScLV3Cyj1gk3eZyJgod-PJ5Bt8Hr
4dJEGVCM9qbfXKsnb95FOpUcVA2xUOVdIX_HSvg6Xtp8FRTu136Px0m6_on_wPUNMvAy0G
}

sprite $octicon24_mail [21x24/16z] {
jP1L5e0m30GJDB1bz_wt9G-tNwO-zTWFU1zFUgVUKApjJaqbxSsrIa35nOK8AHmQ3pSA7YdDGiKNvMKPBj8QibwkO6E7D9_KvXMJsqM6Yf0bJkd8tH1oFtoJ
3PTxOhc9pI93i1CeHJBObI5DqHjM7w6hx0Tc
}

sprite $octicon24_mark_github [24x24/16z] {
LOy74a912CN0xJNtFwqLXo7wMnPuW_pGkWwSLLN4qG4OmqyoWMowGgJ6wjYXG9TsuHouHJgW8iCQLUnMW24Aq2p9uxHQa5E-PW5R0WjOvniRQC3nCN6GnyRW
2ypenqSl00t-0glX3LvEKzXmiXXv0w0oMRA0Pf7O08Kk6nuV_m2mmF9n7_k1ByNskxrKzpHV4DmN-QFJ_GpBg1MLltq1
}

sprite $octicon24_markdown [24x24/16z] {
jP054iKm20Mt7c5uzp_jbxgFPjiO3XIc6i8DGsMwnVHC2C4bfH1Cid4V0Lef0q4A43OvmQjREJNtScxbFT11Y8p4HQw6D5fs09rMkGUDSg-Wyask9N86s_gI
rew6GM_OW_XfpXJc2m
}

sprite $octicon24_megaphone [24x24/16z] {
ZSvL0iKW34JHgQVOx7-rJt2eti-397ZLkfxfPCZvo4AtK0wNBTM0vEdPi9C4ei-6WLV7uZyrCp2iyjFYGR47A-uLmjv3zk3Yuy7fCmSFZGUVuy5kM_ThXjRc
lYadjSEVP5VabEVEnR4uIjcdE0P5o-te-3rnmy7F4X6ywmi
}

sprite $octicon24_mention [21x24/16z] {
VOu5WWGX30I3MqZz_xStX7EhtV4skSIc1djaUISkq3ccWYQvLEZ1xqA3udUD5JvCnj4MfdmYeO_Zd3upo3A8RfkcjQrpnmYCQqALQx9TFJTYpwLVWTgqSvra
brT_oLONkk-wnCoch-gtLmwenxHNdrrzi-dN_XuIZE2PNbuCeaIboI386VDG2nYqqz5yVEjHfEeUFc1Ra1yKL7xIsKbUYUzl6woQGinjcxmJ1nUjyfbKMyrH
_kC5
}

sprite $octicon24_milestone [21x24/16z] Ou01Vdv-E9km8070ne4Ac41Y_6Y03oZA0MK3vH6Yc8ByFDXLic2QYTLs0W2eSQG90W

sprite $octicon24_mirror [24x24/16z] {
TSy5ii0W38JXnOFk_K_x951l_p7ccs0uiatmKYBPx5rjOsRjJFVXxa51thRimy2_mwyj-_1oh2txyEvhYvl3ThcTMog4kcai5zqZX52Pc0bbSsNAh96oNFcS
VFltET_tVh_pzg_TjT39R71prrXi79IBsyhg_Y6D4NStcSrZPeGzJDVLdaxLVzUTvsmX4HEUkVeB
}

sprite $octicon24_mortar_board [24x24/16z] {
lSx50K9140FGhFka_sfno6BNd-CRnL5nUVJaFj2NoLj6LYdKnIsp-2isUwYrQe_Igc6I_LuO3br3S9cPYZQ1emsXBjC6a3f9wqa_Hgxh8I36sszF7yztOcn6
ykcTR5eldsJwux6B--w8RHffiqLi7l0ZeHOSdpC
}

sprite $octicon24_mute [24x24/16z] jT550e0W501HktNkVrknStOcyJvDzFMJTCqh3o2CCCAJftCzkp01w48zfuqgZcSIkYNXufFr4zzy2aoiRkFOlBPEtzSHy7EJWDxB3yy8

sprite $octicon24_no_newline [24x24/16z] {
pT250O0W40NGixtoxp-jHJC1t-JHq7ZP3R2zrqdXp0QTGdb-d_CyIR5zHOS6ljuNW3smmh7_ZE3cWPNCViOx2DvmP69ydCEHMx_C8fENSSvZtk61jshUk9B0
rJhZlepPoxxwSnWx3m
}

sprite $octicon24_note [21x24/16z] jOsr0S0m30JDAEdttpPDcCbNFgflH6o9eBI6WBGffsFHpRfk41CcqhswcubfrhtpxfPYcdKtzHSYOOkOcDP4enhG0G

sprite $octicon24_octoface [24x24/16z] {
hP17GWGW34L_21CwkVzj_SIkZ2lV9htYt_1L1L-Gkfn2dHHHAyHKYXC5p2yyWCSJVxhvqzDysJV_bkfNkEkLS6yJG18vqlQNwMe8J6F3AB1G6qYB9ADxXdQE
1w4eaJMvZm3rqry1OPGnZUCco8mNwEdHetER2g8pZEEITGP_nNm9XGnEoO90Sfq-W43x_lAQhlWaPIl4SiBVl
}

sprite $octicon24_organization [24x24/16z] {
hOz50WGX40E3E_t_r-v8nksqTGe5jE0B6xp2dI8ZzgQzJFGvHv5gjkSpqp7FITDtUWzefaml90AEgPry08AGQvruydpLrVKzqZg4fQuW_Z3-53MrcniKlVRo
r5b8jyi2QIzEzDAtQgvonw0--gxacTYUVLCXBXGvWWtL3phWJmm
}

sprite $octicon24_package [24x24/16z] {
hP455WCn20M9GeZy-z-sB7rrbrdDH07wcbXLyfKBfIrqjjVWT91P9WmjmIVPW1g94cOh8N47C7oXxL-9tU_d3S1Mo-P10bs7aHHumHXZyxQgh-Bx6er8t3j9
1fQM1iZ17t3psFCzNpZHFM_yrpFIZGyAIW2qnfFtzEhXPrdo88a7u7a-r4KNdC7fRXs_PGS
}

sprite $octicon24_paintcan [18x24/16z] {
RT05OiGm34JHCKjPINF_sxQcuhxm3njJLITTAuviv2Foa9OnbOYEfKUKUKLumf4yFg-ocE6cC5Hs_D1PbKXDBSWmRG3LdnxaIqNqHKP_d45lEDey97-No-PT
ncMGg6fEkca5AH3Y1mhU5i4P063iCjSzviN2hx8FrM_nb7mMyfRfHncdgE_lcoF67sADwt0UFd2asiVeDU6z3m
}

sprite $octicon24_pencil [21x24/16z] nSpL0S0m24NHLuy1-qzRT_VSpuFWRXbb2rCYecOMbxPKLMiy5jLgFDbgL4siqQcrEhVvlpRbto0AhKrHkSOc23MpsMsRAajnfW8

sprite $octicon24_person [18x24/16z] ZSp50GCn34HHXGGBdlwh3Pln7R-0UcxCjomSU3kIiEDhZoVu2uVYY_GB-yA-t7svzp-JBnI8VnmvlBaatCl71_wEtsj5Gj_1a35Y5FWeoua5rPMxY6RaIfKN

sprite $octicon24_pin [24x24/16z] {
dP254SGm40FFp5R_rJw4DHDMqBjdb7jfOPy3SPVN0n6n9rG6TeJhm2ouU4xOAKQiQ7y0JfxxTy9ToHHDmecGe558y2Wid73Qn8LJqFeEZoZJK8GjuZm7Jsgd
B_EYbu8jzviZTV8sNm
}

sprite $octicon24_plug [21x24/16z] nOz50e0m0CDmvld_Qt7hk28vjisaU1bZp3q4TCI2X1qRPc4D8y8fgzvOyh19a8SLeQvI5hgqD7fxCak5ieHb4dqAbxIRB0dbx_yp0W

sprite $octicon24_plus_small [11x24/16z] Ow0AuE0dZia113py89A57muuY3K11bWu6AWE

sprite $octicon24_plus [18x24/16z] Ow04SF3pSmo020S4yF3pyq2P_4G0J5q3vGjA

sprite $octicon24_primitive_dot [12x24/16z] Ow0UOEFXv-TX0x4OkVd1W9kHWG78X78OsFZX0AWM3g1CJ82i1balafaeTY7SG3q

sprite $octicon24_primitive_square [12x24/16z] Ow0Iu1zaW5h-0W

sprite $octicon24_project [23x24/16z] O-V70dYO-7auC04_Epy70oRWvm0A0tMXagF2K2OOK2oC02GBuuWq756CDK7mCG8

sprite $octicon24_pulse [21x24/16z] {
fT230SKm04NHLyIu-q_xpHedDhHRex7UQYo7YOcaYObK3NN0wAG4T58R1XEnKYR-JyJB0_5l8kbLw8Q70hKmy9nLcyXNL0NefS3TprbU0nwAXYoq4mzr6alB
Ft_U5G
}

sprite $octicon24_question [21x24/16z] {
VP655GGn20LPZMVwx_RW_NERrU1Y_zZFTEulahKYwdgN5Q3bb1jGJ7H89X9q2ohZuRGEgdzEvkAVepEo_ooJqsmIIGj1g7Uc7RImGuHhuwWSohNQ2ZCCg8Cb
ikRiRy3V2mCUcL6LS1Tce9c4SbS4BqFkIdH7YLJIFOjAKl4FOHIlDXz2jVbr86edlu_kSyY_r_5Ot3yk
}

sprite $octicon24_quote [21x24/16z] {
bT053WGX30LGtA7tl-sszCDQR8Yzr8Dv-iALiu0TvC143MMBQ2WR4OKTOz3ONLsOPCXYb5rNMCkB9YllM9JOxiYigWEbnHqjBBujuGuqWwb7rjjYMUsTLg7d
VsHIahoPS0PHTmXAdmPnw4HKJqU-WzvugEjuqWENgfh3WKtuEI_HwV19vrIRSZJwV4xEF7el
}

sprite $octicon24_radio_tower [24x24/16z] {
VT35WKGX00JH-e9BvH_j-WxZxuRJ3V7WpX61PEDECx7f2P6B2ATksGB528G0H0jKy_1WTsumTC0stJaS2i4CGJL2De2-ckylxidMf----EU-SetQvifrwI4u
ft7riCBNOkVUfY7epfsa6vgvC-pGdTmwjEVSzUH6yK_bXiuTjg4RB55h_b8qmjAzw2ox5dxacmX7Ilo9wU2TJm
}

sprite $octicon24_reply [21x24/16z] jSY53KGn0CFGVEPc_sdBt6Emo7hmhMXRUSjuotZBUCkuBqDX8R4K5dcorWaMBLRxbtJCT9pNtOv0KdkJkJafN0Tv8IfyEzb7HUZaZA28nnrjouaR7RTmmXzI

sprite $octicon24_repo_clone [24x24/16z] {
fOy55eCm50JhZUV-fyK7MHoc1VPz6OZ90m-JuLzT1kfwQ59eng2k6qAplbp_c8Nw3S_6zu1uoEBvvygmu7ab70OFaF406O-I5Jp1J0ZKSUjx3QUGUkXE8Pv_
5aPUF8f9BxDK_xsgdjHA
}

sprite $octicon24_repo_force_push [18x24/16z] {
XOm55eKm30Hn5itzJrkNo9U1jlic0bBiuO1pHpjmmCofpKcdD5i86pSJHIPcdcIURaxAd6pF-D8xYirN21StAH2wMIYpDBCX9c0h9i764qW6AT-8BCaim9ts
gobZxDIkDgSPFfNuRpm
}

sprite $octicon24_repo_forked [15x24/16z] {
ZSk50GGX40F0dEAa_su_V-uuEokuhCQOPWywniXEceDe0Hl5EL151N4EBjNBB2nf9Sp1bORChTHcqW08VqyAqkn-rchEshqB455Bpq2_gMU3XlrA4m04yr95
e3RsDPW1J-i7
}

sprite $octicon24_repo_pull [24x24/16z] {
XP472WD020GlVG3H_xysFR723KtikbY1zUPbHSJ-_XKX-B7alnw__ZFkVzheqVkaLdeCVJ17Zzud-asyJy_7flxxVUh-MB-tzc7xdyhNByn_Pirz-5vQ_GBo
yfS-ixuXjZheaSd_UWZ5zm
}

sprite $octicon24_repo_push [18x24/16z] {
bOu55eKW401_46Fk_M-hDDWEFRmDP8DT5pM3ivyQwmsoDOgDUH7rtqOfKQtvpZ9_6-Cw6sg3E2X6IK1zYCRWRc2ISPJm0Dw4vuX3UQDWTB-RgBtPHzbjPXTJ
eWetPW4
}

sprite $octicon24_repo [18x24/16z] u-170nmWZ0nuGA8Co02i1qYYYx1m88aCJLsOW8S3FJGu6D1rSK3r8aHueE46ruKPpZZSmCV4WIh2nWGKXVC

sprite $octicon24_report [24x24/16z] nSw53O10343HukVTVrhS-L7inPgw2CiQ0veyAGfg11ZTygKn9UJ_YFaVyEXTtXzCRtfd4zJee4_hWPcc-dJAOHkc-pocnN1Q3AUbXdG7

sprite $octicon24_rocket [24x24/16z] {
RSt15G0H34LH043wxtRWW3_UyfA4lP8-FjHa8lzdIpK1g38JbHEm9p9jm5pAqrWXxCsvCNokfS6utT5CdgnevYOPLokJ8ouOvPFBlibF5h1xiXvQ5BiBypUK
--g_YnoqADsnoa-lJERXyoms6PkC0Ny
}

sprite $octicon24_rss [15x24/16z] {
fKnL0aCn25kznNB_qqw0sVSBBidj0jPeloEUuFcTQzyAYqMYCQJyBWRiJwCggYldLp4jhYmz142lhsKuFc-qhEJLE7WBAqhgi3SLS_cYnja8mLUdiG3oQev5
tdk_chuoNy03
}

sprite $octicon24_ruby [24x24/16z] hScn5K105031_oG0-gyMW87BRiFPo5arKWLtrLKtLXUtGUqsv75fADO1hyw0OsIaF1XoC6I7x90TiaDso0xP8Jja1voj6G

sprite $octicon24_screen_full [21x24/16z] Ow0CiFE309mBvd7myt000LmGnE412cDevW09ygC2KWH1zi9jXxFf9aYPux472DQWmnh854OS

sprite $octicon24_screen_normal [21x24/16z] ZP430WKX500_5ddkVzerSisoPtmAYC4x3EBy8ZoXe2GKGZ1xmfbT0kxd2NyE-1IPnCtqodXvfC8J2azen8u9XSBxAGdBxY-YK5Ac-2BPWMH7rpdv_E8Ah

sprite $octicon24_search [24x24/16z] {
VP350SKm34CLB4lxJ_lHnS2xc14_tB1IN0S7N1cqC-32BCqHGFmgftiIWwc1cc14oMF7Iz7KLHadMQkj8k8AzLygsQXpYMGxZhWoQcZvMtrQS-jxBesxVFqF
2jM_IJm3WmoEb7YsTSD2SHs0S0bSQGTyBx2X6gZxuGUF1cy
}

sprite $octicon24_server [18x24/16z] Oy00ZEmSA82TaOyV3V3nSp304P3FmC6F9iB1Woe21ZmOvZ2XsyM4wHvsT5qS_3n820mmxS8KmTI5QJAcxPWknFG54RPJBJG

sprite $octicon24_settings [24x24/16z] hP3L0S0m24IZS5_S_jFMtIMlZU7W2WBs9p4y_ybxjlAWQ92TtDWX3-G9cpXNxVW-0COwHuGzerpGe65hFvYP6zdAntesSJRpAJpdSjG

sprite $octicon24_shield [21x24/16z] {
hSq53aCn30DG5pyqhUz_soq5_MM2uHC6ZS7dqahskCIZSgX7d2kqxWVy3ma8Ggiv0AxHsA5s6YVK-SOvAu3APmwEYt0e0ChghTyHG5gfSGP1pQ0ulykkP6L6
6lFJGUk0AdnKC0WlWkKmjqjgL2t1o4B9c6u
}

sprite $octicon24_sign_in [21x24/16z] {
hSx70SGW34HHmIRozD_jCZYGR_utFTc0g8Gk8xaV06lk0eYch9MScOgLAvO-UT0trXk-cD61qg6Bt9I8KrkSVzzVj7_Ivl6vH_27laJKE0k6_RGmPUhlPvKh
LYRE_Al37m
}

sprite $octicon24_sign_out [24x24/16z] {
jSy53e0m58FXXpkz_sc1QJEFySU_8jkAeBiN4u1pPLZeE4TnOQLpYLqjtll0uHrJwaQsoEsHWAiF76ngUFoTzdyjBZndvBtaNNvmDbdV72mwpRhnZEuLBQch
XHul4Rm
}

sprite $octicon24_smiley [24x24/16z] {
TP873iKW34EJNqIAABpxt_OBgtiy3JR4DcR2SstGQdOxuGMWDO1oh2JeyHkzNtH8wtI6i9s0lExkavsOkauuQFgq06vM2BiH57EwoWmTIg52EvwrVK6t9Q3g
GAwC0a4rpG2ZN6h3rlci6kaQDzegON4pNzRY6vf_qD0zCPy8tJFU3Ix4U7VKEN5X6dLAryo9MRgigF3pj7nOVKiLKTFgs-wpfvoJhpv_vFAPutVkN__a3m
}

sprite $octicon24_squirrel [24x24/16z] {
ZSw5TK0X50FGu4xstxO7X_hz2Zp3_mXjdVww6zXK_McxSB9er3oFt2G0IneqF2BWsUXtlq8pb5coya2Y75Ceb3j-1sMakxxV1whlL-t8Aj5ODZwjqINW68qS
W-U-xz19dpdLqjy2aysLbu159Du4fio7mSIN-ojUyllwiD-61rwYmkByv8mM-CC7
}

sprite $octicon24_star [21x24/16z] {
fSq53WCm30D0bo5g_F_NZaiQRoSC6gyPu5x3lSI4EqgzwqMIyNwHrFl5PTMua8eqNZKfAJYJU2yXtFK20C-TnvbJJkfmPNNsB3fX9nYMJNI6ay7PoAyz-ogJ
B0QcaCmpfrv3RPr9rQ5p5Vyx0W
}

sprite $octicon24_stop [21x24/16z] jT6t0O0m44FH8rzbxJyjMOWWb_poWNDKQvEriW9MMbaVHptrCgbCAWD0FOn8HSOB8_4hPkO7MNsutRmzfhiGVtLKcNyE_t2-1G

sprite $octicon24_sync [18x24/16z] {
dT1L0eGm30JGgKli_hVTj8l-yd2g4tmNEujGZq0gS67QOHRhyD_gxqeajX0G_0T7kCJ-Hm1_T6pPblMO-6kJlNySVk4X1J76czd0GwVMgEDXcEADJK9wnJ4R
VYdFXZ_Fas1BnjPtYXM7qvb20q2s2DCEd7RFSbSZm9MqAaP7nJxx0G
}

sprite $octicon24_tag [21x24/16z] {
hSb50W9030J1MVVD_r-BGwCt-fJKw4SkrLFPFLlSjavjovZRxNeKAmzCfbXhVDMwLEtyeY1wnL1A47h5UsZU-bHdzOjcAs-Q7njLquVwFNHNREeQYg4OYg4O
MZ6XGt_f2
}

sprite $octicon24_tasklist [24x24/16z] lSo55SCm34LHbSpsst_QSdL-cNCJayXSNTWj3HQtmwokmnK8jkAaMoeUjeJBK4vXhG_0E8JF1P2m21fMGSDgVjYJM9cBg2VnwpcJMI6wkOHwKl-r3G

sprite $octicon24_telescope [21x24/16z] {
XP45ZaGn3CLUEHzz_zkkCbHOih1Mmtg3gPDV3ylg6FgFTiYPOWzeIvMY2WGDX8Eg2pProWstCX0_ttOSqz7xpJTFOi_u_0PtBwtZgQxQbOMCgz9LlDYqSsOf
V_BvhnHTdTYGyF364kSupBFNxJOmpM264IPN2KPOlfw73CrV4zdb_7MxvNB-sl9J1ajTBXVy0W
}

sprite $octicon24_terminal [21x24/16z] Ow0CSF1Z0Wv-7Wvqm0CKnjICHv292OiWBnyJfY0BFrmK8OWGHGWYH3452Mj7Y64wYGFYRrJ7iu0zpW8K9C7lM8CEQo1J674

sprite $octicon24_text_size [27x24/16z] {
jT7LWSGm301HcL6U_gizKCW7dxiJfXUITxU08FyL0AhyLuN5agUSSnHBcMqN4y3brRYB0o2TNX0UqK67OHxOcPUO8KvmvdMH0lNnf4AMS-v1Rsz8C571ssiJ
Bg_OflD0_cfUuhHJE-JAdPuUghfWA7S65_QyDQ2QHwjVsINzV1qJFI1oNPt5yYOM6C_lS7AaK4JlKnVCxT-elBnF
}

sprite $octicon24_three_bars [18x24/16z] Ow0IOED00wpyH01CNSFRBie1

sprite $octicon24_thumbsdown [24x24/16z] {
RSu54aCn24LHubXv-zzj9wdtSySF4UXK59zy7LhC30Y_4eSJrG00g_HLno37ZduB8MHkdhiWzucIUaDFlM2cJY6vctlg4ZMmi_RZ2YfphSKtZ2UDjPP0w9az
1mkxmw_1UOglktdk4sN_UFltVXuA_VUnlQ7_-zhlQ53c7VFY1I4mkbODLkZP7G
}

sprite $octicon24_thumbsup [24x24/16z] {
RT1N0iKW24JHiOiGPl-hVRqQxbzExFYMbPfmAj65UlR1XCeUEjInrrY0ohfxlJjyxTwP0AnZTpVScjnOcICtjjUfxWcG-XXZ7Yy6xfz2oSvRhWM_BHhlOKkS
ePl5xX9wOW-zieRUcK8N8dGpMEGkUDvNy_-sxVa-avJvJeo6Lsdnari7S0K
}

sprite $octicon24_tools [24x24/16z] {
TT45ZWKn30DG5uVQ-FwtNHNonqiHHS_b0a2f2LBfsSr9jlWoAO65tKVZ6rpaBKpUqITGcSNcbeta616SOKnZg-MXBwx0GxlNeAoCJA_aVFYMQtXeoa3fQ-xc
4vyA0Kylmb9Nh8Cl8R-e_SEXN2WMV_A0GbeG3XycUtYvJqQZ18EPl94WBvQWZRwIMJRosuKTwpSEkVqo6fm8BVsyOUCDV04
}

sprite $octicon24_trashcan [18x24/16z] rSW50G0n30F0ZBdnh_QPGS2kNFnG8KuiJiA5Nmujl0a8Z5ULYCJLT5hU2U1Puvb50s2yPR-VQDSyFujphxpmcEWG3nuVHW

sprite $octicon24_triangle_down [18x24/16z] nSYn4G0G40110D7hlrjpuMdWDzoIQftFQd4bMg4KXLAe21MX8bI4Yd0fyZm

sprite $octicon24_triangle_left [9x24/16z] Oo0CE60qFupcXz7yC9eVHlF3Q7uOpG-b4Go4548nZ8Km4CP2M0fZ8Ho66m

sprite $octicon24_triangle_right [9x24/16z] Oy0DE60CVWuO0yRYXx7uOIn-68iVnkA7iVXXB7G61vfY3ZG3ET0ivO0xZ3

sprite $octicon24_triangle_up [18x24/16z] pSYn5G0G44H10D5T_zrw6_vjW0cdVA4rZuXcaQb2g10e1Kg1Kg0Kh7NCAazT

sprite $octicon24_unfold [21x24/16z] {
RT110aHG30JH00h8_Myx4K3_gPq76hkgbzgqUlEjBirJrLHx28FUlWNQ5Pwnutsm-aBK9hP4Yw_nYlPpUxk_xbPxBEVmb1QD_cvCmsTxcfsN0RU6oVZGvS_u
hHwGyGnr-Utw1npHsqGnZJIjLP1-
}

sprite $octicon24_unmute [24x24/16z] {
hT550e0W40NG6Rh__Kzh5xLJoKS3_V_PBC-2hDW1xYWeg9fFPuhWYWytHJ1ynOTpYMJ13vzk8saeXY4kfvskDYcUqZxcwnGJ-Rm7Lxi3sJtCV3RFRDrsd-dU
PtCkvfpkSzNt0C753-vDLFTMt_FiNVxxLW
}

sprite $octicon24_unverified [24x24/16z] {
TP873WCW203TM_d_RmlKG2pfPP-3wOHoJd6M3iXub8-vRc1sJK4-W1_kTs3mf8FraNm2fWMCCu39vAjSGHeGrI6SoNGkmiBKs6_K0uGZIVGdoSJ_CEKyMcuT
zPkq-AA-DRrKg5-MyStpvY1tjjI5DCscai_sVY8VmH38U-l_pkKIaiunHqzA63VsWzsJ3m
}

sprite $octicon24_verified [24x24/16z] {
VTA50OCm04JHU8ZU_jisLk2mts8F5x7dQdNYNa0h4abjVS6eUAFs0-2IcuvRihEwk-vkY99j8zlT4mjX0T-z4BSoIXj7vWbXNMHc1boTO9XHk-T-LSIeupYc
YUwSZbiEQmLn_5-d8Ix7VPc3rtrPZEp1Ss-DMwgxlFlNU-afSxn7gwKu5pi7egVlv0S
}

sprite $octicon24_versions [21x24/16z] nT2r0O0m54NHXyVl_jFY3YLokiXNlIbhpAp9j4YiqlWfOSHEtXWrc5A06G41P904Q4JFwBVB-vRkcxyTytuXYtnRNQuNT

sprite $octicon24_watch [18x24/16z] {
XP453iL020MXkigx_sdRBl9T9aOcmUc21KgRoDdXx65IcFJLS0DAIWLeh68MsKZPH6Pjr3dIkSiLDnbYIQQaqGnDIV14p1aKHa5kvTdKXlHi4cxcmWBFMjA5
PMNG4yZMtR3kDc70qjwtUDyqhb5JgdQDlpVyVlduZkXtJW
}

sprite $octicon24_x [18x24/16z] hT170W0H343HiTFT_xJJaUHletkwmos4jDifFD16cL16kocDCQdSpVJKasPZjZPCch1fmgGD5AxYpZoTD-Gh-5B-Xbku

sprite $octicon24_zap [15x24/16z] LSU53G0X04Mn7zpPVzfpuJLQBOp1AZO2DhcCJODLR3giOpDWCvt2kSymd48wlRi5J1rpc2fcC6LCNC1KCOFj
