' Octicons{height=16px} (https://github.com/primer/octicons) MIT License

sprite $octicon16_alert [16x16/16z] RSc54KCn3C1GXyc9zf-s_SmwV2VvJlN61Eb20s1E5u1wqB7aTYk8W6uCh2Qk7hl7minkyaJB9IlIE3zDF5VZExUwtgtow0y

sprite $octicon16_archive [14x16/16z] Oq01tFn8W9iVMOeVbSU3ef818GbaOl8Wob3bgCZZHdOAAW

sprite $octicon16_arrow_down [10x16/16z] XSQr0S104C0mXpdUVzhd_bI9Y4Muo-7YiNbW-Yo-2PX__MUgLLUwVIUK0G

sprite $octicon16_arrow_left [10x16/16z] Oo0CEA4q8pS_XC74omzXiV130Hi_9ek1XG_AWkf0c88mcI

sprite $octicon16_arrow_right [10x16/16z] Oo08EE4iVcv668kVbmb8GW0V2v051Mm85bmMhWDk2jnamW

sprite $octicon16_arrow_small_down [6x16/16z] Oo00-FbX91S_470nyFBpyp8mCF7pCm75sTW8wGS

sprite $octicon16_arrow_small_left [6x16/16z] Oo04k82OYPUVWO6D7mGW94W4Aai

sprite $octicon16_arrow_small_right [6x16/16z] Oo00kC0aFoyJ0py8i458i0XGd9E14

sprite $octicon16_arrow_small_up [6x16/16z] Oo00sDY011C_FnC30oy_Foy35pyGS34myFC3nK4a0G

sprite $octicon16_arrow_up [10x16/16z] XSQt0O0m4C10aJFQVrfmgjzN7LthsZBhN3AgxmWCZ-epm6LnSTWSW2eGB_O3

sprite $octicon16_beaker [16x16/16z] VSc55GCm3CHGXJdUVzh2bV47zOmOVzWDLtQzdrhxzzoUEqmzCu3qh6dkYDyWs-cfTbFL9W9Gdhe0-wat97kM22_po14

sprite $octicon16_bell [14x16/16z] ROs35G0m34HhO_zfQpV_AJWW06VtZ6sCbeo5nWRjdz2tWEicuy3KBSH9MSXQgfFlJI2azgPByTvyJToqPODkHcNO6mk1jI43

sprite $octicon16_bold [10x16/16z] RKt50G0X32kSLhF_j3W_ycgZT08w_1kNYWBIhqoKWNNHlZ8FTKPIl_Xdw-VqCNXT3tHTYdys1oAjjJ_H2HK

sprite $octicon16_book [16x16/16z] Oo04UFX1W8-53qppCF23HPducS0qFvGFfq0G2A0KrUKn-Jpyo807wcec7YO6eW

sprite $octicon16_bookmark [10x16/16z] dS6r0G0n300nEyot_xJFs4RgN3e_fN3ndjsmih63JH097Bogvn0OWKdTsiukoYP2LJbeNG4

sprite $octicon16_briefcase [14x16/16z] Oo04kFdvkH4yVY222IC03py3d0raukSX04m2o20HeDgEp_a

sprite $octicon16_broadcast [16x16/16z] {
HKw50GGX32jkbVst_UJFSW8ng01rc_jfSY7hgHIFPj9a_JQwKr3GOMu3WZ86QML92mHde3kM46lGTDX9D5GI0auUV0FavYRqiVBTw8C6X7-_RK7y_c0AvupW
Aqqvhb4GKal_WS_D5VG6-OVxlZz-
}

sprite $octicon16_browser [14x16/16z] Oy03kFcH03S_0mI20JyQGDP61nwAotZm-G4

sprite $octicon16_bug [16x16/16z] XOq30W0n40DphkV_hprRdNALw0cuyNQmPvoRza40mYbcFQVotX1C2GWepPGgJLpZQ4hDhF4UhF78IxqwpLSF_TNVoB066GO

sprite $octicon16_calendar [14x16/16z] fOor0O104C1IOzb_Mk3Toi-vic3pbuX6VwA0sMCF3WyCFiiwStF6CZjjN0ny

sprite $octicon16_check [12x16/16z] Oo09i22O7FmS22QOZM2om9XWPL0cX09Xc4fqRJ0EWaaO

sprite $octicon16_checklist [16x16/16z] bSa55i0m30BGp8r7xd_Q6UrSgVvWRu4h27PplT4nltevHHfwrXn9nzXEJ2oTIFLCKwJYxChW50tgwM9CId4TYCSC

sprite $octicon16_chevron_down [10x16/16z] Oo0MCCCe3dus48ETduE37yHau-VdO00oMLb130OG4ym0CS4C21F880S

sprite $octicon16_chevron_left [8x16/16z] Oy03c7YOm1GVFpU4ucK4KpoCC44u3HE7gOD9mSt11G

sprite $octicon16_chevron_right [8x16/16z] Oy05c7YOm3GtFn-OmSWBO_006N0f60qLXwg32iBCmGC

sprite $octicon16_chevron_up [10x16/16z] Oo0BS7306Fpy7306a0bXiB82cI066mC36v390MG00JjGa1cYZPbecm

sprite $octicon16_circle_slash [14x16/16z] PSu53WGn049HncbIuFwd7MrNV_J507zHYOYxsUQoqfulfE1EEUa6HWRTKM2ABu0romjOa_K5B15V02lz0anO7SNNkXeojsVhqfxXtaab_Ze

sprite $octicon16_circuit_board [14x16/16z] ZOn70W0X20Ep9xl-_xUhqc-E5KY2G5iBMCmkk68gKEzTrWQzOxFlM3dbjvKlQEOcSmeNN76HEPCBflcY8_03

sprite $octicon16_clippy [14x16/16z] POw54O0m00DnXzz_MyY5-YDjfD8rJCyp9VLCq-FP1LnnWByqWbH4gej8EOtAR37RFc4N9nXdIOdKb9LsYQ0B6j_p1G

sprite $octicon16_clock [14x16/16z] POxL0SLG34BpjDHW_sbxtSzN5B05tDADL7z9_7uWlw7HdgQxVClGIA6bWLOw8swq3fT-hVkfT1xVfSihThX0gn398HboT9-J9HzTi0K7

sprite $octicon16_cloud_download [16x16/16z] RKo50SGW47l1JhF_j4XTI0MYdncomlbxKFKIk_JVAFbYYMtSqt84GCDm4HR-3OaHoLCubqYtCB0S4NVEEl8X31v6FuozJfRNPLdUyXSKT9IxiD1J67I61W

sprite $octicon16_cloud_upload [16x16/16z] ZKm54WCn22JJABR__sq39sELYx9AJzPGE9SRgi-sgTS9bwSaTcBl-LL0QwZOxvnKQcUqvRqMci3Cg8Ovu44qd64WFzRmrnguHhv6tmPvN2gTw_JJ5_nzlG4

sprite $octicon16_code [14x16/16z] Oo05C78pCJ0mSJD2U3pyF1021BZv-K1oVFpSG0uNc0FcSZ5mW3bGBWSg3qKbkYa86z1i9mK

sprite $octicon16_comment_discussion [16x16/16z] bOg53S0m4CHE4OJV-qzRPgv51zOLcPayT9Q7On_KJH_Ytru0C0U5vL4mf4rNGChW3A182iDXGLlOLmtrbXO

sprite $octicon16_comment [16x16/16z] Oq07FFn8W9k1WHzPaf_-V6wWCnWueExXWOXoy36Xg4BbCg1n6H1SJ

sprite $octicon16_credit_card [16x16/16z] Oo00UFXH00y_gZG_8O2k7fEFK8fR7hT-TFSna0W

sprite $octicon16_dash [8x16/16z] Oo0JyAC1Siq1

sprite $octicon16_dashboard [16x16/16z] {
RO-73aCX24NlUugchFl_Vrin3LazJZRW7sB9iFcJNgSksKh1q2Dc31GFjZ-0HmayifKe72K08wnyJ75Pr7CPSfNav0V0Jb3AdQmBmhRx3SeRtwXL_XO7fUgt
78xkhnh85zt_KleHUxuqmU4B
}

sprite $octicon16_database [12x16/16z] hOwr0G1H24FptP3zjxqEwUyrE0aY_P2e2fsEgwTNeFQZLprFt90slstwPYj0QVFzjX-zHJu

sprite $octicon16_desktop_download [16x16/16z] ZSw30S1044JHYS-__sfZ-vsvgmbeTLXxUjEQdcSz_pyQHcRTDzDoNSjCotKjOnxoElCS10so12dJeapqKgaR7G

sprite $octicon16_device_camera_video [16x16/16z] Oo00kFcXW1l4O-FZXmC61aQG98BF2f9402v-oW12FwRv2FlXJk21k8-1H

sprite $octicon16_device_camera [16x16/16z] Oo04UFY1W1lEvUP70K0kI1JEHqWmCp1p8t4PkS4O1e1o83LmFWE2n9H7w4St7nEWYV4GyXu

sprite $octicon16_device_desktop [16x16/16z] Oo00kFbH03S_gZG_lVde0CrzF61LZ7py_7oCS4qiG2vGW0MR_m

sprite $octicon16_device_mobile [10x16/16z] u-670cv-16200XgoG82F3seV7mC37mgB6oRB0m

sprite $octicon16_diff_added [14x16/16z] Oq01tFn8W9iVMOeVZKSA1JCHbKUIAVZSWk9g7bGV0G

sprite $octicon16_diff_ignored [14x16/16z] RSU53S1030ImAEBIxJzjdyCMcfmRnWqoK8y_Z4c-CGdFIUOaSvAr6Tc8JAJTC1vo6W

sprite $octicon16_diff_modified [14x16/16z] Oq01tFn8W9iVMOgV88-3Zuy3pkC0cS01u_61U7oOF8HAJ5E8jnt5rJoeFW8

sprite $octicon16_diff_removed [14x16/16z] Oq01tFn8W9iVMOgV0XxCH0mUTMn0SJKFgey

sprite $octicon16_diff_renamed [14x16/16z] Oq01FFn8W8SVMOeV6uyJXSVFmuZCu-TZXlAW1h9Xy10gKKt1j06VMr1TZUeZ

sprite $octicon16_diff [13x16/16z] TSc53S1034FHhmhAzVxRzfZZW-J9W7o-ZPh3wr4gl9GBBuUg00MX3Fzvo2UZDZCm89-feSEZd0T-

sprite $octicon16_ellipsis [12x16/16z] Ow00SFF30Gy_2c1WW21qDW8WwwN43G

sprite $octicon16_eye [16x16/16z] ZKu35W1H49g-tVrlkpPx60Rv0rSQYrycLJcYgN4qVMS1sqZRZxeVCUpHBxJ8k3Qj6R7zHH99I1jQz6qwpwV_Yzx5xvBdalSL7G

sprite $octicon16_file_binary [12x16/16z] TOk54O0m5CLodE1a_stnUlDT7WcRByS0Vhlf6YGEedVSWznsEnRz5tSV-7HXx-r5tzLk1ZOIJW

sprite $octicon16_file_code [12x16/16z] VOl50S0m30ElpDN-quR1hvmPXE5Hvfz1PCumY3w8FlGU2UORxZdrytyKgNXV8EIyFzlU_XS6_QF6Yy43

sprite $octicon16_file_directory [14x16/16z] Oy03kFb1W0VAuuUH41ePyF3J6N2Zs8xF3m

sprite $octicon16_file_media [12x16/16z] LOU50G0X3CJk7S_-qxxXWRQ91WAPj4eeOzv0FL2Fx93Nv9di-zuzXUO6TXdp-Ge40qRW8MCO2ODgu04

sprite $octicon16_file_pdf [12x16/16z] JOl50S0W00E3Ezb_sXQ7UqNna3Yf4c3pbXA-cQu3DRhfsbEXcxrfSERcwEhArZOZ9gL4rqL9Mzbf_nojjgdPoe09oOAZYpmwyP3my0C

sprite $octicon16_file_submodule [14x16/16z] Oy03kFb1W0VAuuUH41ePyF2Z0nQ8AcO83weQgey1oa2M8v77ZSpZmUS7

sprite $octicon16_file_symlink_directory [14x16/16z] VSg50O0W54NHPxTt_sbjQJZ4JnKitDQlulk_ohMIqkDIlV7PkqhIz5LtRggXNPtD0UZuRHWBZbK59m

sprite $octicon16_file_symlink_file [12x16/16z] VOp50S0m30DLvjx-quR1hrp0ACdmaFbd2MNEKEGy5pcVKv5pzlZ5VDxXplb9v8xvodFM_htq_RNun3mpoXyQhmmU

sprite $octicon16_file_zip [12x16/16z] TOY50S0m3CCqvld_QuTbK9j4DW6RViuMn3_p4uGFjd-3xTzjU-kLljVPMp_WjAu7wvR8Dpas0cu

sprite $octicon16_file [12x16/16z] fSWt5e0W00JHUJPcv_wdLSbGyviDT2wJPm59jdz86-8l3QaSkydqNtbPNNG-

sprite $octicon16_flame [12x16/16z] HOg70S0G00G_JUVstpQwI_1DZKU7O8_sl5idmf86ebxJf0ESQDe3HJTnIBmUU5_efa2Ca1XKotrqb6rFttXLhkgUXwn6n4blUPjELeslRPhu0G

sprite $octicon16_fold [14x16/16z] ZOu53W1120CROglC_rzxxheJmMar0JhmNWK6mfXbS0iGpA44jt4wJio3vd8ffC92aSwpyztvvrcltUUP7W

sprite $octicon16_gear [14x16/16z] ROw50S0m40AXxko_RUD-qNSmG1y22x582xXOGxfbC9Sn9oK8m3XtSZTHdxd3OCmLNyW05KZMLsOkRHSgmNfwhIpmVHZm0m

sprite $octicon16_gift [14x16/16z] dOq30e10400dQ_7_rsQxvcujzgIc2QbQsaS6LLxrjaK20cj50F45mMcPz3vQqwSNzJkIrV4x6W

sprite $octicon16_gist_secret [14x16/16z] XOo53KCn30MVly9q-szRXKIbCwF-y3JdsdEh191krMVLzG7NODASVXDAKPelImcgu6HWSb0p-9auUSW1XcN8Di1FLphqCjlwmGi

sprite $octicon16_gist [12x16/16z] Oq02FFnmmCEF4ER7msRYOMJaOGApcVWu61Wu-9X0R1uUi7aywE88zSIOZ-mU1Xm

sprite $octicon16_git_branch [10x16/16z] ROx50S0m30F37D_-qvQvkPTHahfmlTczwbhtP-LQTmxiqSE-QNjbmUsLfgkjqfMqLbLOHci5abSFg7heiIVeJdsO0G

sprite $octicon16_git_commit [14x16/16z] Ow00C77nyN4nmJXy_7n01ELoyRCpCB3pSm6P_4301nBZ0x5GUKWgCKr1s401

sprite $octicon16_git_compare [14x16/16z] dOx55S10449PzwN_RlEOw3d_DeBWeaB4EQC6shISMnh8NTv950GoG2CIDq3UBkGpuSzKdsapWXejgr3KkqVPdqcmtls51kC

sprite $octicon16_git_merge [12x16/16z] RSx70SGm44BHOLTPGlHVhNEs_-dTm2uvDhURGFkoauBjIRnOvNGN_SyrkibecW8usIpKVdZADJed_Msh0RpiyklRjH4

sprite $octicon16_git_pull_request [12x16/16z] dKt50G0W43gxPVzfxNfxdK13x8Wo9aaMeqwC9GiWcrrtCII0SQEGYO3nE_AewQiMWEXbpvrhyx-rZ57sUkSj5G

sprite $octicon16_globe [14x16/16z] {
NSa53W0n20NHgIlzzx_j4kBxgXFWhvqpsY2K2giVMG6g5cIw9C-d2gJhPKn53SaDamxzMDILctrPv5FSm_Py_fh21VOxKs7Xpk0f52WFgi8bMSCpfgFSIfXN
QZtnzm4
}

sprite $octicon16_grabber [8x16/16z] Oo00-A60F772

sprite $octicon16_graph [16x16/16z] usT01KJo-Vb9vOCn9XzCKu-FwLuqm806

sprite $octicon16_heart [12x16/16z] ZSe35W0X50NGbrtxNst6mQ0RFl56nQW1tNwLAcFQhsFQQdguatfnSWcxKWiWZ3IW8hul4tHsB0pQu5O1

sprite $octicon16_history [14x16/16z] NOu54aDH30AtJZfvSF_JLh_lM1JWoEdHoH20kDgwtMHV8S-87vKhISFKcYIQMqzLlg3ERUrkcJlWqmsjdLfUEmlNt9NXclfsVtTsoVxVIGkEl04

sprite $octicon16_home [16x16/16z] ROw54G0X30Jl7KtwhnR9FCwYUoZsA3KgaG9pq_CabRqeS99uKGawbK0rbO0Lv9O2fm3TEkNUFW1arsFBrxANJzwskBsp7rIS3cGi_pYiH

sprite $octicon16_horizontal_rule [10x16/16z] Oy0B-268dnz8mH221GHuPB6QXmNWTm4

sprite $octicon16_hubot [14x16/16z] VOj50W0X30ER7d2Q_xzs5-V6e8t86uHgLWF6uCoZIRwwFXIiI76YXjCmJIvpKLmo9N96FrIZC6FE559kia-NDR5nfWDdwpGV_

sprite $octicon16_inbox [14x16/16z] bSc53SH050FHPRI--w_sBkoiE2Dy6hSs-3ISCmrp0H926j98jKcjzYpbZYX5c9UyaOpNuH5EWL-QRy0j_G4

sprite $octicon16_info [14x16/16z] {
POw5bGKn30FjHQrVBFNVxGNlqmGd2jatZfGIGmuIvmdoQA9dh3uwpDcabAPqq9OPCKuFa3fRf9wTwcRIiCJBaA0lSy8OTHAAscLxFTnQ4jhdpwuBp2gDkqZb
jX_-
}

sprite $octicon16_issue_closed [16x16/16z] {
ROw54SH030CtUBfvn-g_sgSmxA11m1EQx52pJ7scXa6PmpowBbzkcnRoDzf0HmHAvhc7bricpNDlLNVWOPwHFS0-eq9X_byOWzqFI77CgtdgKztlVKTbzYme
x11FV
}

sprite $octicon16_issue_opened [14x16/16z] PKx50SG02EEkXYRxJrltyWAYyXajidJRMq2xJe5sEMZRrpYVM0voEI4AEIw1bbwN9hlhwlYyZfoD-NHv93pJtyss7ARAPoO

sprite $octicon16_issue_reopened [14x16/16z] NSw54SG020NHZVzaEBR_Qi_zZUBmRzXAJm48StUM9TqpU1ZkTcUq0Bs5ZPfdH8URPvHo-KIBlz7jpaVwLOjAxy-8KcPl8H0F-VuipplMDl3l0W

sprite $octicon16_italic [6x16/16z] NKg30G0W4Cokst_QxEU9h599rkkXwwLyomA-NWtJJL5l0gq9f6sQptog

sprite $octicon16_jersey [14x16/16z] bOnL0i0m34AfUxd_RSVyR_AgIG009AE9kY4CLGlGgB94Kz4mh2etOJkxHVUgSiDEoHBEi1SIMR1WScud4OJsll2lEbFswkIjQhnf2m

sprite $octicon16_kebab_horizontal [13x16/16z] Ow0gOETZHn1y_7mC3302HOQ1TW

sprite $octicon16_kebab_vertical [3x16/16z] Os1WOETZv-C7OdOWco0N

sprite $octicon16_key [14x16/16z] ZSc53S1G30DHHr08EFjFMsRy9tmwF2LAggnWPWGNwW0WT1PdSLOEHUIi9kVq2CeEweuQOpE01s36uJKegWS

sprite $octicon16_keyboard [16x16/16z] Oo00UFXH00y_gZG_FnWX8AOy4WGX_9hviPiF0jZbqTt7G28

sprite $octicon16_law [14x16/16z] TOc73S0m3CCKeBk2zV-tjRfNc4N6-5B8SbKdTPKPbN3LLQJr2sZK0ATmu5ghD0GRrogf3LshXAHmhT947jScndKnI_FbnlrY0G

sprite $octicon16_light_bulb [12x16/16z] PSg50SD020NG1nSNil-qTI_w3J7lnpu7z3Mc7AkdLOAiPXa0mw824FM9lp9j1-oDTGJZYgn0LC8qUHooK0aSr_9VsqNU0BaUQ-8C

sprite $octicon16_link_external [12x16/16z] TSO53e1000F1JIDOS_t_Qt67czXGuIJGPiMglLtNLRPlBMgtUowqwsKn2wVxKxjpCXKJ

sprite $octicon16_link [16x16/16z] bKu53i1029iKOZJz_sldEutX3btIPDH5j99kjzk8Du_zzNkyNe_57OZ-zS5BxYLxzubRtYMdxYNKxVaewjC1L9PE

sprite $octicon16_list_ordered [12x16/16z] TSt50K0X201GMvhzf_tTyIvAXmlqIp3zpHTs_RDh-49QZtziUFGdJSVVVcPHuR88WwyiTZtlNdgkHW

sprite $octicon16_list_unordered [12x16/16z] Oy01-FY0c1yC-93Po6feePSVeHv84TOB

sprite $octicon16_location [12x16/16z] JSh5WSGm50Km9MRuSV_LBiFezW1jdxCRtB7oTUKLDr616lf0hHWz4kkSHOg3ym7djP_Lpx_D77v4jWjGDYc0I1WJvW1HQG7SJqhF3SWHcH-rWdS

sprite $octicon16_lock [12x16/16z] dOor0S0m4CJa9fpJ_jE6iRMU4IX3CXJOqvXDZsAmXTPXpvFNExCn-Syd7xQK6xVSJrxT__xdmme

sprite $octicon16_logo_gist [25x16/16z] {
dOn7TWCm20K7WRg0-zysJ-c9L_PiAB_m0iCpJkU1TGpHGKdbYxjP21zquHFr6nWyS0NS-2G4yqYdUxfhAeYPGGgXK3uJLz2zKqcHVApoAp1ZjQ_47lm8Y8qi
7q9rVeJBRXy2-nIGk08AaefyU6PanXBcvaH61tewp_C6
}

sprite $octicon16_logo_github [45x16/16z] {
jSy7We0W34JH2T8XcVlVTaEsz_xj-bJ0FrQsKLU2922wHZ-tHtiWRLH4ar62iK1I0YefmA0-uCqLnqnQhsq0TDnf7-59NeXInaTO130_8Y9hDvB3SIrbKSMi
89l9fYdPGGvSgZh5oQOt7KTwRg6GZgDySBb_8eEMv2sy86IpSopxxidJCJ_34r2E5K_cnrZlS2LtpezVfZpYc50x-6uOM2y6oFc8ZLxWA05LIUu2jN88Pp5p
t6qX6xcMoTBkg28Il9VWnzq
}

sprite $octicon16_mail_read [14x16/16z] LSm50iGm2031hIlP_x_sX7BIYGSXxJjVGzCsa4xB2VHIx9aKlLvEAiLq7UGH3jNPK5OtWCqLXI7QDBKOg7QX0LGinZ4gjhe2UMWSFQa_mjC_9pTF

sprite $octicon16_mail [14x16/16z] ZOt50GKn508dxg7_Qh-ixorpUGgmJDE3fi95aKOpUs_QaAZ30jXHa21E3tv6jecW61NOfzZTdAxljzh0McWLQPGhOEYLtbdc2m

sprite $octicon16_mark_github [16x16/16z] {
LOt50KD120LPlgq0qt-r4OZE2NaY3tGu-50f1XGZryM7bLy_dGZYD8PeoZv67V_xSD3tti01-H0Gq3uxXC7nNdUm3g6rQa1lzCdQHBO5qAIZOxKCX_wGJT_t
2cEchqFjNOgMGy_UEm
}

sprite $octicon16_markdown [16x16/16z] bOw53S103CHSvjx-qvRXJo-AWnOb11baNEh0g14aU9mHTznRMbW0bilL2ZGyn-1fTIrZNVC71eBi

sprite $octicon16_megaphone [16x16/16z] TOw50S0W30H33UVttxQuSsZywS1jTMzAzw9PhmMZO3ycNe0tu3_cOGf0jir3fD7i03exl7ESATVN1svq_LEFVdwmIVJwW45_i8_y

sprite $octicon16_mention [14x16/16z] {
PKw50GCm20FgXPB_lrtc5jmHegm3H9SRTWxJqYACGRZUioieMvuutPALwZbP634d0tIBkDgermwHkRWRgLISSMPQGDd0A0ipAqqCNHUQTAWFxaBs3h3Ss7g7
2U5yvGtT65MjFL_Y9qXlyeSB
}

sprite $octicon16_milestone [14x16/16z] Om03Vdu83UTX0ppySC01L0G2K8e3bOUg4XE0rD6B1m

sprite $octicon16_mirror [16x16/16z] {
ROp50KD120LdtQ7_QYChqJydUCOYZC0RKxlsQiuR9ADa2STqeE1cn4k6-KCMZpZ8yy_WP1xJHAUiP3ta__yY_zuxFoHDmFdZo3QFkFymYW5C6U7vzsfPsDgL
vdZZsXq
}

sprite $octicon16_mortar_board [16x16/16z] fOl70OL020LPm8nC_zMQTOy_EASNvJjAaOfs0T6TaVKp5z6h105WTaLY4pSv-7PWF2xHc-mupBsfRk7XEmB810xVqtDGlKq9EPt_bbPUi08

sprite $octicon16_mute [16x16/16z] Oo0Ai7EZS3du-T6u_2XS49-9Xmc4UO1i29-FZvMFZuaVnWSAyFCnCQ3pqTMZcuTX7rG0mxr40W

sprite $octicon16_no_newline [16x16/16z] fKt50O1G50BRb_jFQxV7pur6AIWHmfj6JsgimW1aIW-qgRBGN7bmeIrZeGjMlb1St4GNYlx8htjAzllU_wySCm

sprite $octicon16_note [14x16/16z] Oy03kFcH03S_iXG_1W-c3hSSRdrG7ZuRKDp2mq0q

sprite $octicon16_octoface [16x16/16z] {
XOx5bGGm3CKKHiVzTxk17IOTzBvEDhzeaYupIOMXAdrgT9dQVKD07Zlf0x4_zie0PW9Xnj284yTMd5VKKBImPRJdsLaJKtbsDYD3XAqy35QgDwkDhsBN2FNy
MmEl_04
}

sprite $octicon16_organization [16x16/16z] XSc53SD004DH1uxXxxzjvJBdYGpwi7RwgeS6jATv0lCoLtViEZ_zc7i6yjFlvpedIKi5sk9vkWwihvxheiAp8LwLnYjTT2wQ3fm

sprite $octicon16_package [16x16/16z] {
RO_50KGn20MZEBp-grtt_NEQ16_7J9el7-mbMy9vN5uIIffbDFhMa8RKtTiWgrHDD5mrhla0ZSlxrex14nTzlA_IVj-xVxql7BxxnxkZIQMkstjfbbpt9Qz0
m6bytNF86G
}

sprite $octicon16_paintcan [12x16/16z] LSsr0GH03CH07Us3VTx-gtt6YPG9KDefRbhaR6rcD8WZ3yT0oKigbwBi2gtqBdNegcsxD5eRAZkisFOEEJ4l1azkn33OKBZvqMCO-zatxTdXbm3UN_vS0G

sprite $octicon16_pencil [14x16/16z] Oy01sDYGE1py_1meF7us69i3n6L3A0EAm3aWBem3vf7FOU1d07FWF0O41oA30m

sprite $octicon16_person [12x16/16z] PStL0O0m301HtE7sdnQhnExhLTEuLbWp5u0b-Vfy9VCNzu_FH_BqUKfkFYVrwKvVVayJPchp9LQ4NNWqgWS

sprite $octicon16_pin [16x16/16z] NOi55W0X24JXsJdtF-s6BTzaWXQARk3lET-2gJW4ZlZnXmdK34KA2zCyZq5iun8gqoKOcjWshr71-cFch5fbjRdTSrRtAta1

sprite $octicon16_plug [14x16/16z] Oo0PyFF3MCny_Fm87Wy_300v730MYCq75GTpk1cHvFWOaVNnevZ9Zx2F0W

sprite $octicon16_plus_small [7x16/16z] Oy0F-34eVWZ08aSK

sprite $octicon16_plus [12x16/16z] Oy07-Fd9OlFZ0EIQYGy

sprite $octicon16_primitive_dot [8x16/16z] Oo046Bdu-BWO6HZv-860Zv6B7mouW5om08o6YSFKmVGH0W

sprite $octicon16_primitive_square [8x16/16z] Oo00-2a4XCm7

sprite $octicon16_project [15x16/16z] u-P71jpy3CY0dn-8u9ZkN230muK232wQ5z0y2

sprite $octicon16_pulse [14x16/16z] ZScr0SH034HHQPb__zKU69NPBngG9yMMD6nRs0jKl5uNGTVKyo9r-5U0mM9DTZC0GVzLVXIgt9XY36-RanU-

sprite $octicon16_question [14x16/16z] POw53SG030FlsT6dzlxJbY9iJnWmS4DBieYJjwtFH_Rx65ASLFRH-_2pwq4PUH-oymVhK3kGW3gVKQNXavaw_JocoHdKCemAh3DXfl8b_TBiL2SjRcm

sprite $octicon16_quote [14x16/16z] PSM50KCn409GuXxsdxRz5hy37euJCxhw6_LWoDfHP1QTmW8qDAa6aGM3p3XHMOBgy3xPA3UsuMzCGsGoem4eXSvwVm

sprite $octicon16_radio_tower [16x16/16z] {
POm54WGX30GRI8MWy__NdkjkbuvIZG_5AJBAIs4genCR8c07OsndELKAVE7xgCVuxVVn_4kbfESVNe2uzy4gJ_RecoycTzbNT-Mi_jLwaDxI5L3bRptrOF8a
gm64CcUk
}

sprite $octicon16_reply [14x16/16z] VSw30G0n30NGrExVVzepwbSpePEbWaMrGBM05iNYaFIva7Y5ukmGtwNrwUp_FqK4M14lG9UvH4y5dgXagSHeOGS

sprite $octicon16_repo_clone [16x16/16z] ZOq53i0W5CLUT0Ry-vzsrgHRdABDjrOGdkF-0PytylVvE1Zd_U8CRiR3Innm8Hx1wQaV9IrGxOt8UY-v

sprite $octicon16_repo_force_push [12x16/16z] bOh50G0X40DphZ3zLulRbzNOJwiFL8kCpxFX5TQA3PY2Nu1t8gDqIHLn-bqVyTSplxgk4Ni

sprite $octicon16_repo_forked [10x16/16z] NSxL0O0m303HmvtRVzeQJYLvFn7kqwvhUyIjgZR8yL6Z3PIeG8cx8upkK2Scr1GUIDG3e1pdQ0H7sv-E9Tud0W

sprite $octicon16_repo_pull [16x16/16z] RSz50i0W34JHBEl__gUjJgJ0sq5y0xVP3SoXD_6U57TC7aScnUkR9jzvF_mzdf_qwVmDvBkzvyQ6LPDD-RW

sprite $octicon16_repo_push [12x16/16z] VOh50S0m30DLvjx-qnPZUCKesl7QG5Q0C5pNnz5n2wtX0uw2Lu3Lyj_bAy6757h6MsHsXQwCRm

sprite $octicon16_repo [12x16/16z] u-670o2J0GRuWMn-69iMuYY00KaSeOuVsMrWFa8X1n220G

sprite $octicon16_report [16x16/16z] Oq03FFmeW8SVLPgVds8Q2iXK3t8V0nCVt7qWCIO-3XGr42w2ZyfbGE42

sprite $octicon16_rocket [16x16/16z] LSp50S0m30F0G26i_QSj6lKxWu9DAjso04LLZnr8ShgmuYxhl02iGuudtbHc-pYfbR8IaRQPMBwB5dnPq9HPcfWwlO7YxHcKDm

sprite $octicon16_rss [10x16/16z] VKr50W0W21js-__Ncd2bUuCginVFfGcrImtRavJKJZbRkEKv8DSgtGCSIVM4wczv3q8P3d3jWFKvplsy551b0m

sprite $octicon16_ruby [16x16/16z] Oo0CEFYXW0F2vME2Y3FnSI2u86cW05oM7og0paTLZp00neK9GBbm0GWN8G3X8WGWN8G0X4iO

sprite $octicon16_screen_full [14x16/16z] Oy03kFdv-I4i88C7oeG9014CeFD0qd1b3CJpy9c9QZkgo_3v0G

sprite $octicon16_screen_normal [14x16/16z] Oq03_706Ee-VdmV6u-67Ip0Wn800hWR2WIc3q3XuK81c2Yf0jnsFEz4

sprite $octicon16_search [16x16/16z] ROxL0O1034DRFj2Kx3yjdFixhKSSEqZiaj27rxvVV3JQZst-sUm9vavd1WT32Iv9NF1tyARCmNx7_B5VFu_QwI7DEPBU5xjQS5HM3aZd06JW1m

sprite $octicon16_server [12x16/16z] Oq02tFnmmCtF08LW184G2JZWmQ6N1qazpVK2

sprite $octicon16_settings [16x16/16z] Oo0C-144RZu32f-7dv-V1niVqsHkP2a47w690SKGkDN4kOyW

sprite $octicon16_shield [14x16/16z] XOlL0O0m30KlWfEo_xH8zPEhvWc0Rn6R0-XyN9LZrkkFG-GOau2CIK77TCAPFodVK8QiRR3bpFBT1lQz2sdK4_YO79ZRCFDXyVt3gAmHAnyF

sprite $octicon16_sign_in [14x16/16z] O-3XXm4U1WO68Ca2f40iC0_2H_3uWGmk91uJBpz4DJ90vo5KOZS5n23CGt4dCmzO3WvOU20y11_A

sprite $octicon16_sign_out [16x16/16z] u-670Hu6403IB0mG5fGF5a7mmG32vqJm8NAyJ70-r51MT3wQUZpcWGd2V3JtC_D0v160XGV6HuWWs

sprite $octicon16_smiley [16x16/16z] {
POy5ZWKm24GfOKacoDp_jblx_geuo4HHP47b08QRUH1RZ3RPMCUozf3BQ8XoMwy75TC7nBq2vI8ax-L5UxSRtyENFFsRbvh-20bUvXTA6td474RT_NXEoNS_
R_t-TVpEyptlFm
}

sprite $octicon16_squirrel [16x16/16z] TSi30i0m40J0RMFT_l-rGSq9J_YZaqYSZj1oa9vmMVLOk8Xmomsk15HBGhPOSQ5Al_e9cBKV3PbCK0QX-3XAlPOng2ZSQ2mILrk3uM699zxhiFVvp4M92XyQ

sprite $octicon16_star [14x16/16z] VOt50KKn3CDSvch_QJ_3OzqIamvmRdcrjfHW8LQeUc9SI0MWfE1COa5I-1z1alyUNa_o-yZVnXVrVGsO4yRxWYGbU1qkczTmThha3W

sprite $octicon16_stop [14x16/16z] Oq077FnWm07Xy361A2O-3XW7oeLo-FaXN7uW1ym3SI4K0v4K0l2Zce9g0uhjA2v3TJKw

sprite $octicon16_sync [12x16/16z] TOt50GH13CEIOLR_rHuiepv1s_AEBxrN9rb4A_GE0vL6rjzcW0kKwQyDGlkT5fIsji7xiFRdZy1e_jyNl8FnzypKtsdCMVMtoU9gwyNBEry

sprite $octicon16_tag [14x16/16z] TSV50OG04CNGluAFz5yj6XnooXFHroB2IsJJVAnQ5CgK114CpK7_75cQZgmsVa8JWHM20088O8Bt1W

sprite $octicon16_tasklist [16x16/16z] hOo30S1054DJkzb_sffdlM_YeExmfIQBEy-1Ygp1WxbbTPHtNU--_j_M_sSrP7WnoxMTbFzM

sprite $octicon16_telescope [14x16/16z] RSc54GCW40NHZ-km_LSREOZdZPoi33hGFtwaL_QPfSCDtAJAf0KjxCjrxfopOm5KszNyO1LjbU6BuenskPcbC9bwQXcBsnBn6NCJUiOPX2mUo5m1

sprite $octicon16_terminal [14x16/16z] Oy03UFYH00y_iXG_1e-T0vd7nCU1uC6vc3m41s4Ao3OWYSy-L9VXymC

sprite $octicon16_text_size [18x16/16z] {
bO_50GCW34M3Gv2t_xR5QhSMbtoJlvg7_FsYqEynbVr7Lzn-C81Te1mlBABhf7XpOGsxJY3IiHlKvgFpL96yOOaqPoum1lGD6lCueCt6X5bGLQuNtG2TftBz
nldH2IU1kzwi_D0U
}

sprite $octicon16_three_bars [12x16/16z] Oo02y2C07pAR_ken0G

sprite $octicon16_thumbsdown [16x16/16z] LSh50K0X009Gx8Rzf_qT-cu43aatLWjFgLbSJ1muel2XqPARNtE9QuvbpQvpoOQU4lEt4mTR6mvTOi2bdW_XHy1mpWQXJLb02rEcZmCJps5nsW4

sprite $octicon16_thumbsup [16x16/16z] LSk53K1H24FHFlUo_xJV1Mxq48gxoEMXOiXJMu2HbEcGXZRW-BFNUtFd-_MwH9WYHLZn57XGyELEAiTfdPjrozOpqfZkF0n_o-M5iqAvMjrZ1m

sprite $octicon16_tools [16x16/16z] {
HOw50KCn44A9UzX_svOVjtkS0hO4h6MQrPVP5mvE8wCn2Zl9dW7qBq0uxImsKhmGcLe3JUXkc912mCVOqyKbsJ_wG-gSgu_FhwvH2G_jgz2AthJwmyqAN07e
qop-HhDUmLSe-04
}

sprite $octicon16_trashcan [12x16/16z] Oq03tFpy_DmW1Wy_682v_71fVg026E01Sk6GLcmWWDBSS6kH0G

sprite $octicon16_triangle_down [12x16/16z] Ow00SF330GU2mu6GuK0euq3euK0O06HI2

sprite $octicon16_triangle_left [6x16/16z] Oq0776227qpmWmb-CC4F920aL0Gk2wOWkc0c8

sprite $octicon16_triangle_right [6x16/16z] Oq02762IdmDCWYb-CCKFflZ158BaWCjom7K12JG

sprite $octicon16_triangle_up [12x16/16z] Ow0KS70WcFpy70Wca0DZWZaG9fG3OY8u5

sprite $octicon16_unfold [14x16/16z] NK-34G0n4Dp9AEV-gtqZUxPmmPpuOLRDrLbTLDtQp_ZfdTfdZZStSk9s7-UflUe0pd4VpwHzT4k_atvei0C

sprite $octicon16_unmute [16x16/16z] ZKw30G0n44ljPlzftsPz2j2sN1fViwQU7ByGrdJCLKALQqfOaQmBI6CovL5dMS0r5rKGt7FKCRlDRtnkuBF-h5VapS_Dx_Vg0G

sprite $octicon16_unverified [16x16/16z] PO-54GDH24INGIE4_hlDXyZP6y5bCN0cumTnr2AO9hpNdtjNQmS1l4mAI3jc8CQ4mdj7buU0jU7yRU9Ns_p6_5sRN3jcqrZWkmMyZ_dop-NVYvwZtZS

sprite $octicon16_verified [16x16/16z] POz50i10308dPG-rbF-_jkuxjoZ0ZZB5HQZrIglOozutFH3sGu1yCfN9WlOg6ufRz9IHjd9RpAjqfbs8yIoTsbSvIulslbrfGQVKZYe_bTygppVl0W

sprite $octicon16_versions [14x16/16z] Oo0HSFE30JUGoSFFm0y582O3a0TImG-aoE6Xcu9g0yHs7gXrnBiN

sprite $octicon16_watch [12x16/16z] TOu52i00548LrdlW_K-xxdZKJrKIcK0BMNZMXi8km1BDkcrGDJyj1rGKUrqGxxMpribSBpSB1HLxJNNHl7hzvhbc7W4

sprite $octicon16_x [12x16/16z] Oo06iFCoWYX6NdO61bv-48SHI458HZ310E50c10Eb8bWewf1w4Ks4yKkOW

sprite $octicon16_zap [10x16/16z] DSl50G0n30D1-J2S_giDhrvZa4uUu5vGG7MW6WYWtc36WLMvWG8m80TKm0lqW0u
