'
' Create participant that represents kafka topic
'
' Usage example:
'
'   kafka_topic(A, FooBarBazBooBa, foobarGUID)
'   kafka_topic(B, Boolaboola, bazbarGUID, compacted)
'   A --> B : foomsg
'
!unquoted function kafka_topic($id, $name, $key, $compacted="")

!$keyico = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAQCAYAAAAmlE46AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAACCSURBVCiRvZHRCcMwDESfO0yyQ8le/QpNx9EcTUbpb0KygPtRlRohOyaQHhwIc49DMpykFhDgpRZ924UWIKqfwAjMQFMCxUBfjYBcCuA1mYOZu1LjmjRGYFJHPvu6ehjIWo5A7nGGTHjj9x3VUJ/bJwft6hAUnGDwgp5uSdO9Fvq/3hRQQX7csJ4XAAAAAElFTkSuQmCC"
!$compactico = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAQCAYAAAAmlE46AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAABGSURBVCiRY2AYFuAoAwPDfxz4MC7FDHg0wTCGYgY0jegALo6umCiNTFh9RwQYGI1HGLD7hSRwmIGE6CBkCDZ8iFIX0hEAAKeVMPx3fNfcAAAAAElFTkSuQmCC"
!$compactLabel = ""
!if ($compacted == "compacted")
!$compactLabel = "<img:" + $compactico + "> compacted\n"
!endif
queue "$compactLabel<img:$keyico> **$key**\n----\n//<U+00AB>Kafka<U+00BB>//\n**$name**" as $id

!endfunction
