'
' Create participant that represents kafka topic
'
' Usage example:
'
'   kafka_topic_participant(A, FooBarBazBooBa, foobarGUID, "{userGUID, userData}", "", "k1:v1|k-2:v-bar2|k-foo:v-boobaa", vert)
'   kafka_topic_participant(B, Boolaboola, bazbarGUID, "", compacted, "k1:v1|k-2:v-bar2|k-foo:v-boobaa")
'   kafka_topic_participant(C, SimpleFoo)
'   A --> B : foomsg
'   B --> C : barmsg
'
$puml_ext_include(utils/data-structures.iuml)
$puml_ext_include(art/octicons16.iuml)
$puml_ext_include(art/logos24.iuml)

!function $_kafka_topic_participant_entry_horiz_key_callback($key, $value, $arg)
    !return " **" + $key + "** |"
!endfunction

!function $_kafka_topic_participant_entry_horiz_value_callback($key, $value, $arg)
    !return " " + $value + " |"
!endfunction

!function $_kafka_topic_participant_entry_vert_callback($key, $value, $arg)
    !return "\n| **" + $key + "** | " + $value + " |"
!endfunction

!unquoted procedure kafka_topic_participant($id, $name, $key="", $payload="", $compacted="", $entries="", $dir="horiz")
    !$keyico = "<$octicon16_key>"
    !$payloadico = "<$octicon16_file_binary>"
    !$compactico = "<$octicon16_versions>"
    !$kafkaico = "<$logo24_apache_kafka>"
    !$attributes = ""
    !if ($compacted == "compacted")
        !$attributes = $attributes + "\n" + $compactico + " compacted"
    !endif
    !if ($key != "")
        !$attributes = $attributes + "\n" + $keyico + " **" + $key + "**"
    !endif
    !if ($payload != "")
        !$attributes = $attributes + "\n" + $payloadico + " " + $payload + ""
    !endif
    !$content = "**" + $kafkaico + " " + $name + "**"
    !if ($attributes != "")
        !$content = $content + "\n----" + $attributes
    !endif
    !if ($entries != "")
        !if ($dir != "vert")
            !$content = $content + "\n----\n| " + $keyico + " |" + $_dict_foreach_value($entries, "$_kafka_topic_participant_entry_horiz_key_callback") + "\n"
            !$content = $content + "| |" + $_dict_foreach_value($entries, "$_kafka_topic_participant_entry_horiz_value_callback")
        !else
            !$content = $content + "\n----\n| " + $keyico + " | |"
            !$content = $content + $_dict_foreach_value($entries, "$_kafka_topic_participant_entry_vert_callback")
        !endif
    !endif
    queue "//<U+00AB>Kafka<U+00BB>//\n$content" as $id
!endprocedure
